### ISSUE TITLE
Support for VueJS 3 (URGENT)

### ISSUE THREAD

**Issue by eugenevk** [algolia/vue-instantsearch#1001]
**Feature ⚡️**

### What is your use case for such a feature?
Support of most current version of VueJS needed.

### What is your proposal
Upgrade the code / dependencies to support VueJS 3.x

### What is the version you are using?
None yet. Install returns error "Could not resolve dependency". Am on Vue 3.0.0.

**Comment by eunjae-lee** [comment]
Hi there.
We do not support Vue 3 yet, and are working on it at the moment.

I'm closing this issue since it's duplicated.
https://github.com/algolia/vue-instantsearch/issues/890
