### ISSUE TITLE
Multi-index search with different configurations crashes Chrome browser

### ISSUE THREAD

**Issue by TomDeSmet** [algolia/vue-instantsearch#1007]
**My goal:** searching through multiple indexes at once and passing different configuration options to both.

My (simplified code):

```
<ais-instant-search
    index-name="products"
    :search-client="searchClient"
>
    <ais-configure :hits-per-page.camel="5"></ais-configure>

    <ais-autocomplete>
       <!-- Code to visualize hits -->

        <ais-index index-name="customers">
            <ais-configure filters="sales:215010"></ais-configure>
        </ais-index>
    </ais-autocomplete>
</ais-instant-search>
```

So I'm trying to pass the `sales` filter to the `customers` index only. As that attribute is non-existing in the products index.
Same idea would make it possible for me to get 5 product hits and 20 customer hits.

I was hoping that this way, **putting a configure widget inside the index widget, would apply the filters to that index only**. But this crashes my Chrome browser every time.

How would I go about this? It seems logical to me to do it this way? I've read that in v1 you could add more attributes to the index widget, but as these are replaced by the configure widget, it would seem that this is the correct way to go about?

**Comment by Haroenv** [comment]
The code indeed seems like it doesn't really pose a problem. 
Can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch) (you can use the indices `instant_search` and `instant_search_price_desc`. Thanks!

**Comment by TomDeSmet** [comment]
@Haroenv I created this sandbox link: https://codesandbox.io/s/eager-bash-cdooz?file=/src/App.vue
For simplification, I just pass a different `hits-per-page` configuration to the other index. This also crashes my browser (Safari and Chrome tested) when typing in the search field.

If you take that configuration out, it goes smooth again. Hope this helps to solve this issue!

**Comment by eunjae-lee** [comment]
Hi @TomDeSmet Thanks for providing the sandbox.

https://codesandbox.io/s/restless-cdn-y6xej?file=/src/App.vue:543-707

As I modified yours, `<ais-index>` inside your `<ais-autocomplete>` caused the issue. You can put it outside and `<ais-autocomplete>` still takes it into account.

**Comment by TomDeSmet** [comment]
Superb! Thanks.
