### ISSUE TITLE
Nuxt ssr + nuxt-i18n + localized indexes names

### ISSUE THREAD

**Issue by federicovezzoli** [algolia/vue-instantsearch#1010]
Hi everyone, 
I'm trying to use different index names for different languages with nuxt + nuxt-i18n without any luck.

I'm following the [documentation](https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/vue/#with-nuxt) and I'm using the createServerRootMixin.
My indexes names are like: prod_content_it, prod_content_en, prod_content_es etc.
So basically I'm trying to use $i18n.locale value and dinamically compose the index name.
Problem is that inside createServerRootMixin I can't access that value, it's outside the scope.

Anyone has encountered the same problem? and maybe solved it?

ps: When running in client side only, everything works.

Thanks!

**Comment by Haroenv** [comment]
If you use the `data` + `provide` workaround mentioned here: https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/#combining-with-nuxtjs, you will have access to the `this` variables when instantiating.

Another thing to do when using nuxt-i18n though is that you'll need to augment the default clone component like this: https://github.com/algolia/vue-instantsearch/issues/936#issuecomment-807074775

**Comment by federicovezzoli** [comment]
Thanks a lot @Haroenv .

Now it works, here is the interesting snippet for future reference:

`data() {
    // Create it in `data` to access the Vue Router
    const mixin = createServerRootMixin({
      searchClient,
      indexName: `prod_magazine_${this.$i18n.locale}`,
      $cloneComponent,
      routing: {
        router: nuxtRouter(this.$router),
      },
    });
    return {
      ...mixin.data(),
    };
  }`
