### ISSUE TITLE
Transform items fired twice

### ISSUE THREAD

**Issue by TomDeSmet** [algolia/vue-instantsearch#1019]
**Bug 🐞**

### What is the current behavior?
The `tranform-items` on `ais-hits` always fires twice.
You can see it here in this simple sandbox: https://codesandbox.io/s/romantic-shannon-dxrvf?file=/src/App.vue

### What is the expected behavior?
It should only fire once since no filtering has been done yet.

### Does this happen only in specific situations?
No, it seems to happen always.

### What is the version you are using?
3.8.1

**Comment by Haroenv** [comment]
Hi @TomDeSmet, what is the impact of transformItems being called multiple times?

**Comment by TomDeSmet** [comment]
Our client has very fluid prices based on different parameters. So we need to fetch the most recent price of a product every time it shows. So every time the `transformed-items` is called, we fetch prices for the shown products. This is an intensive process already, but now every call is made twice because of this, doubling our overhead execution time.

I already added different flags in the process to limit these calls, but I cannot set flags to get around this issue, because in every transform new products could be shown which we need to fetch prices for.

I already keep track of which products have an updated price, so they are not fetched again, but as I can only update this status after my promise returns the new price, the initial call will still be fired before I get the response.

I could try keeping track of all the calls and cancel the previous call if it is fired twice, but I have had very few luck with Axios canceling calls already that I'm not eager to add even more cancels. But that is a whole other matter entirely :)

**Comment by Haroenv** [comment]
Could you not memoize the heavy call? In this case for example heavy only gets called once: https://codesandbox.io/s/stupefied-fire-7dr7x?file=/src/App.vue
