### ISSUE TITLE
How to disable auto refinement for select on algolia instant search

### ISSUE THREAD

**Issue by lohnsonok** [algolia/vue-instantsearch#1034]
I have this current code for integrated algolia ais-instant-search that working fine and i want to disable auto refinement on select input to keep list and when select to return hits for only this selected argument.

`  <ais-instant-search
    :search-client="searchClient"
    :index-name="ALGOLIA_INDEX_NAME"
    ><ais-menu-select :attribute="attribute" :limit="60">
      <select
        class="select rm-raduis-select is-fullwidth"
        slot-scope="{ items, canRefine, refine }"
        :disabled="!canRefine"
        @change="refine($event.currentTarget.value)"
      >
        <option value="">All domain</option>
        <option
          v-for="item in items"
          :key="item.value"
          :value="item.value"
          :selected="item.isRefined"
        >
          {{ item.label }}
        </option>
      </select>
    </ais-menu-select>
    //hits display ...
  </ais-instant-search>`

**Comment by Haroenv** [comment]
Sorry, I don't understand what you mean, could you try to rephrase? The filtering happens when you call `refine`

**Comment by lohnsonok** [comment]
![image](https://user-images.githubusercontent.com/60504466/129560313-1847db6c-5ee5-411f-b3c4-9ef8713e7413.png)

I have this search that use select box and input. when i select a item from select box and type to search in this segment it auto refine select box also that i want to disable

**Comment by francoischalifour** [comment]
And do you still want the query to be "search-as-you-type"? (as opposed to triggering the query only on <kbd>Enter</kbd>)

**Comment by lohnsonok** [comment]
> And do you still want the query to be "search-as-you-type"? (as opposed to triggering the query only on Enter)

I want all categories to be visible without refinement. This means that refinement should only work on the search results. 
I am facing the same problem like this official algolia [demo here](https://vue-instantsearch.netlify.app/stories/?selectedKind=ais-menu-select&selectedStory=default&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs)

When the search term does not exist, it returns to the selected option "See all", which I do not want (refinement also in the selection field).

**Comment by francoischalifour** [comment]
Right! You can implement this using the `ais-menu-select` widget in the root index, and using a child index for `ais-search-box` and `ais-hits`. This way, the query of the child index doesn't affect the selector which is in the root index.

```html
<template>
  <div class="container">
    <ais-instant-search
      :search-client="searchClient"
      index-name="instant_search"
    >
      <ais-menu-select attribute="categories">
        <template slot="item" slot-scope="{ item }">
          {{ item.label }}
        </template>
      </ais-menu-select>

      <ais-index indexName="instant_search" indexId="instant_search_results">
        <ais-search-box placeholder="Search" />
        <ais-hits>
          <template slot="item" slot-scope="{ item }">
            <article>
              <h1>
                <ais-highlight :hit="item" attribute="name" />
              </h1>
            </article>
          </template>
        </ais-hits>

        <ais-pagination />
      </ais-index>
    </ais-instant-search>
  </div>
</template>
```

I [created this sandbox](https://codesandbox.io/s/vue-instantsearch-selector-search-4fizh?file=/src/App.vue) to see it in action.

**Comment by Haroenv** [comment]
You can change the limit of categories using the "limit" prop, but there will always be a limit, the absolute maximum it can be set to is 1000

**Comment by lohnsonok** [comment]
> You can change the limit of categories using the "limit" prop, but there will always be a limit, the absolute maximum it can be set to is 1000

okay. i understand. Thank you
