### ISSUE TITLE
Use attribute filter on search ais autocomplete index

### ISSUE THREAD

**Issue by lohnsonok** [algolia/vue-instantsearch#1038]
I noticed that the search is done on all the variables of the hits but I would like to limit it to the name only (searchable) since I don't display all the data. Thank you

` <ais-index
            :indexName="ALGOLIA_INDEX_NAME"
            indexId="instant_search_results"
          >
            <ais-autocomplete>
              <div slot-scope="{ currentRefinement, indices, refine }">
                <p class="control is-expanded mobile-input">
                  <input
                    class="input rm-raduis-input is-borderless"
                    type="search"
                    placeholder="Accéder à une startup"
                    :value="currentRefinement"
                    @input="refine($event.currentTarget.value)"
                    autocomplete="off"
                  />
                </p>
                {{ print(currentRefinement, indices) }}
              </div>
            </ais-autocomplete>
          </ais-index>`

**Comment by Haroenv** [comment]
`<ais-configure :restrict-searchable-attributes.camel="['name']" />` should solve your issue, documentation: https://www.algolia.com/doc/api-reference/api-parameters/restrictSearchableAttributes/

**Comment by lohnsonok** [comment]
> :restrict-searchable-attributes.camel="['name']"

I tested but i not work properly. Same as here demo []ais configure(https://vue-instantsearch.netlify.app/stories/?selectedKind=ais-configure&selectedStory=default&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs)

![image](https://user-images.githubusercontent.com/60504466/129918408-84c22aac-dc31-490b-958d-455e365edfe4.png)

When i type ****google, it return approximative result. But i want to return exact match result

**Comment by Haroenv** [comment]
there's the following settings that could make a difference, although I don't know exactly what you want to achieve

- https://www.algolia.com/doc/api-reference/api-parameters/exactOnSingleWordQuery/
- https://www.algolia.com/doc/api-reference/api-parameters/typoTolerance/
