### ISSUE TITLE
Dynamic routing on parameters

### ISSUE THREAD

**Issue by bootsmann1995** [algolia/vue-instantsearch#1050]
Hello :) 

I have a Algolia project where I want to put in a filter before rendering items. 

This is my query: "?Products-da-dev%5BrefinementList%5D%5Bbusiness%5D%5B0%5D=Fjerkræ". 

I want this to be applied to the initial search, and then apply the filters and show result based on this. 

In this case would I have my "business" refinement filter, to be pre-selected as"Fjerkræ" (added to the url and shown in my ui).  
like this: 
![image](https://user-images.githubusercontent.com/65391517/130624998-c5469b5d-bb8b-4484-9f8f-53de450d72ab.png)

Not like a "filters" property, because I want to give the customer the possibility to remove all filters and then see all my products.

**Comment by tkrugg** [comment]
Hi @bootsmann1995 in your case I'd consider using the [routing feature](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/#basic-urls). When using routing, getting InstantSearch into a specific state  is just a matter of redirecting your to the right URL. 

For example this sets the initial state to `brand: Samsung`:
https://instantsearchjs.netlify.app/examples/e-commerce/search/?brands=Samsung

You'd still be able to use the [clear-refinements](https://www.algolia.com/doc/api-reference/widgets/clear-refinements/vue/) or [current-refinements](https://www.algolia.com/doc/api-reference/widgets/current-refinements/vue/) widgets to allow your user to clear the initial refinements.

Another option would be to leverage [initial-ui-state](https://www.algolia.com/doc/api-reference/widgets/instantsearch/vue/#widget-param-initial-ui-state). Let me know if this helped!

**Comment by bootsmann1995** [comment]
@tkrugg  hello, I have the routing feature :) but the thing is I want to set it in my javascript initialize somehow, is that possible? I'm using nuxtRouting.

**Comment by bootsmann1995** [comment]
@tkrugg ??

**Comment by bootsmann1995** [comment]
@tkrugg  can you set filters on that?
