### ISSUE TITLE
Highlighting doesn't work for nested Objects

### ISSUE THREAD

**Issue by soolace** [algolia/vue-instantsearch#1063]
**Bug 🐞**

### What is the current behavior?
Highlighting is not working for nested objects. But the documentation of algolia says, it should be possible: 
<ais-highlight attribute="meta.name" :hit="hit" />
https://www.algolia.com/doc/api-reference/widgets/highlight/vue/

The highlightResult looks like this: (the nested object is reading as a String and replaces the " with & quot ;.

![image](https://user-images.githubusercontent.com/42381435/133998322-44b6f902-6ce5-45ee-bfae-7f010b995601.png)

Btw. Searching works fine, its just the highlighting.
It only works, when I flat the JSON.

### What is the expected behavior?
I expected, that it works like in the documentation described. 

### What is the version you are using?
"vue-instantsearch": "^4.0.0"

> Always try the latest one before opening an issue.

Probably it's not possible yet or I miss something. 
If it's necessary to see a Demo, I will create a Codepen. But the Code is similar to the Basic-Demo.
Thank you

**Comment by tkrugg** [comment]
hi @soolace that should work on nested attributes too. I just tried it here: https://codesandbox.io/s/spring-hill-rxk7h
Can you make sure you've added your nested attribute to highlighted results under Configuration > highlight > Attributes to highlight? 

This should solve your problem. 

I'll close for now. If it's not solved, please reachout at our support, so we can take a closer look at your account configuration.

**Comment by soolace** [comment]
Thank you very much @tkrugg, this should solve my Problem.
