### ISSUE TITLE
Programmatly trigger vue instant search

### ISSUE THREAD

**Issue by LobergDesign** [algolia/vue-instantsearch#1064]
**What is the current behavior?**
Custom setQuery on search, dosen´t work. 

**Make a sandbox with the current behavior**
https://codesandbox.io/s/custom-search-query-trigger-g7izx?file=/src/App.vue

**What is the expected behavior?**
I want to trigger af algolia instant search based on click or input value. 

Does this happen only in specific situations?
No

What is the proposed solution?
There should be a simple algoliaHelper, to handle things like "setQuery(str)", but it dosent really work.

What is the version you are using?
4.0.0

**Comment by sarahdayan** [comment]
Hey @LobergDesign!

You can use slots to customize `<ais-search-box>` and turn it into a button.

```vue
<ais-search-box>
  <template v-slot="{ refine }">
    <button v-on:click="refine('alexa')">Set "Alexa Voice Remote" as search query</button>
  </template>
</ais-search-box>

<ais-search-box>
  <template v-slot="{ refine }">
    <button v-on:click="refine('google')">Set "Google" as search query</button>
  </template>
</ais-search-box>

<!-- etc. -->
```

**See demo:** https://codesandbox.io/s/custom-search-query-trigger-forked-o9gz0?file=/src/App.vue:484-1109
