### ISSUE TITLE
Input tabindex

### ISSUE THREAD

**Issue by mitchiru** [algolia/vue-instantsearch#1068]
**Bug 🐞**

The input field should be usable with tabs for accessability reasons.

so pls add attrs: { tabindex:"0",

**Comment by Haroenv** [comment]
Input is accessible via tabs without explicitly adding tabIndex. We definitely can add parameters if they make sense, but I'm not sure this is needed. Do you have more info?

**Comment by mitchiru** [comment]
Yes I saw it. Sorry for the Ticket. The Auto focus just has a weird
behaviour for the tabbing.

Haroen Viaene ***@***.***> schrieb am Di., 5. Okt. 2021,
13:32:
