### ISSUE TITLE
Hierarchical Menu widget doesn't generate correct URLs when server-side rendering

### ISSUE THREAD

**Issue by ArcoMul** [algolia/vue-instantsearch#1069]
**Bug 🐞**

(Sorry for all the bug reports, it might be that those are all appearing because of all the versions mixing, it's currently the only way to get things to work for us though)

### What is the current behavior?

When using vue-instantsearch 3.3.0 (because of https://github.com/algolia/vue-instantsearch/issues/1054)
and instantsearch.js 4.29.0 (because of https://github.com/algolia/vue-instantsearch/issues/1062)
the Hierarchical Menu widget doesn't generate correct URLs when server-side rendering. The urls all have an empty state

### Make a sandbox with the current behavior

In the following sandbox I set instantsearch.js version to 4.9.0 (that's where the issue appeared for the first time). I disabled client-side rendering by not initializing the app in entry-client.js.
https://codesandbox.io/s/zealous-liskov-ee0f8?file=/package.json
When hovering the links of the HierarchicalMenu (on the Search page/view) all items link to `/search`

When decreasing the instansearch.js version to 4.8.0 and refreshing the page the HierarchicalMenu items do link to the right state, for example: `/search?instant_search%5BhierarchicalMenu%5D%5Bbrand%5D%5B0%5D=Apple`

### What is the proposed solution?

For now I can use version 4.8.0, but that seems a bit outdated so hopefully doesn't cause any other issues.

### What is the version you are using?

See comments above and the sandbox link

**Comment by Haroenv** [comment]
I can confirm this happens in your demo, and is indeed introduced in 4.9.0 (so last version without that behaviour is 4.8.7, not 4.8.0). Without SSR the issue doesn't appear, so I think possibly something about mismatched helper or mismatched state could be the cause of createURL returning undefined?

**Comment by ArcoMul** [comment]
This is (also) resolved since version 4.3.2!

**Comment by Haroenv** [comment]
Ah, I forgot to check this issue, thanks for closing @ArcoMul !
