### ISSUE TITLE
Autofocus on searchbox not working

### ISSUE THREAD

**Issue by eugenevk** [algolia/vue-instantsearch#1073]
**Bug 🐞**
When I add the autofocus attribute, it doesn't work. No autofocus happens.
In codepen I have this code (as described in the documentation):
```
<div class="searchbox">
   <ais-search-box autofocus />
</div>
```

See https://codesandbox.io/s/happy-moore-yo82c?file=/src/App.vue

**Comment by eugenevk** [comment]
Still doesn't work for me. Also not in the codesandbox you shared. Am using the Brave browser, by the way. Could that be the issue?

**Comment by eugenevk** [comment]
Tested Chrome and Edge as well. Don't work either.

**Comment by Haroenv** [comment]
It's possible that the response doesn't come in fast enough for the browser to consider it "page load". You could manually focus it on mount of the component though

**Comment by eugenevk** [comment]
Do you have a code example? I tried to use the onMounted() hook with nextTick(), but I then need a ref ID for the input and even using that doesn't work? So I tried this (but to no success):
```
<ais-search-box class="mb-3" placeholder="" autofocus>
  <template v-slot="{ currentRefinement, isSearchStalled, refine }">
    <input
      ref="searchbox"
      type="search"
      :value="currentRefinement"
      @input="refine($event.currentTarget.value)"
    >
    <span :hidden="!isSearchStalled">Loading...</span>
  </template>
</ais-search-box>
```
And this in the <script>:
```
<script>
import { algoliaSearchClient } from '@/algolia/config'
import { nextTick, onMounted, ref } from 'vue'

export default {
  name: 'Search',
  setup() {
    const searchbox = ref(null)

    onMounted(() => {
      nextTick(() => {
        searchbox.value.focus()
      })
    })

    return {
      searchbox
    }
  }
}
</script>
```

**Comment by Haroenv** [comment]
then you can use a different selector, like `.searchbox .ais-SearchBox-input` @eugenevk
