### ISSUE TITLE
Possible to contribute to the docs?

### ISSUE THREAD

**Issue by nobitagit** [algolia/vue-instantsearch#1083]
**Feature ⚡️**

### What is your use case for such a feature?
Hi team, sorry for the noise, but I really wouldn't know where to ask...
Is it possible to contribute to the documentation I see on [Algolia docs](https://www.algolia.com/doc/)?
Specifically, I would like to propose some expansion to the docs around [Routing URLs > Combining with Vue Router](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/#combining-with-vue-router) (hence asking here in this repo).

Let me know if there's a way!

**Comment by Haroenv** [comment]
Thanks for the clear explanation, this indeed should be part of the docs, and I've just made a pull request to add the listener for both vue router as nuxt. This issue will automatically close when that change has been merged.

**Comment by Haroenv** [comment]
Thanks again for your suggestion, I have merged the documentation change, don't hesitate to reach out again for any other things you think would be better!
