### ISSUE TITLE
Is there any example using Nuxt SSR and Friendly SEO routes?

### ISSUE THREAD

**Issue by helioepeca** [algolia/vue-instantsearch#1084]
I've already made the SSR version of my store, but can't figure out how to mix the SSR with friendly SEO routes as described here: https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/#seo-friendly-urls

When I try to fix the SEO routes using historyRouter the SSR doesn't works and when i use SSR i can't implement the routes.

**Comment by Haroenv** [comment]
Do you have a codesandbox of what you implemented currently @helioepeca ?

**Comment by helioepeca** [comment]
Hi @Haroenv @francoischalifour I've made this example on codesandbox:

[https://codesandbox.io/s/tender-dawn-iew54](https://codesandbox.io/s/tender-dawn-iew54)

The dataset may look weird because I'm testing, but essencialy when I select a single category on hierarchy menu the ais-hits gets updated, but when I refresh my page the route doesn't keep with the filter. Also on this example i'm not using historyRouter.

**Comment by Haroenv** [comment]
This happens because the array is written inline which gets registered as a change on every rerender, fixed version is putting those arrays in `data` @helioepeca:

https://codesandbox.io/s/brave-bartik-k3wrh?file=/pages/list/_.vue

**Comment by helioepeca** [comment]
> This happens because the array is written inline which gets registered as a change on every rerender, fixed version is putting those arrays in `data` @helioepeca:
> 
> https://codesandbox.io/s/brave-bartik-k3wrh?file=/pages/list/_.vue

Hi @Haroenv I get it and changed on my code, but is still removing the menu filter when I refresh the page, in my codesandbox example and in yours

When I refresh this url for example: https://k3wrh.sse.codesandbox.io/list/masculino
The route returns https://k3wrh.sse.codesandbox.io/list/

**Comment by Haroenv** [comment]
I couldn't figure out what's causing this @helioepeca, my guess it's related to either the stateMapping you have (you have a branch with empty ui state that's confusing) or in the create url itself

**Comment by podlebar** [comment]
@helioepeca it won't work see those issues: 

https://github.com/algolia/vue-instantsearch/issues/1062
https://github.com/algolia/vue-instantsearch/issues/1054
https://github.com/algolia/vue-instantsearch/issues/1066

**Comment by Haroenv** [comment]
For now this issue has nothing else actionable I think, as it's covered by different issues. I'll close this.
