### ISSUE TITLE
Vue 3 InstantSearch bug regarding specific imports

### ISSUE THREAD

**Issue by Miguelklappes** [algolia/vue-instantsearch#1088]
**Bug 🐞**

### What is the current behavior?
When I'm using the V4 (Vue 3) of `"vue-instantsearch"` I'm presented with a multitude of errors in the terminal. This happens when I tried to make use fo this[ guide (infinite scroll)](https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/infinite-scroll/vue/) on Vue 3, which it seems is only for Vue 2 due to the use of [mixins](https://vuejs.org/v2/guide/mixins.html).

In short, when I imported this line the Vite server dies and I have to restart the project, commenting out the specific line that caused problems:

```javascript
import { createWidgetMixin } from 'vue-instantsearch'; 
```
### Make a sandbox with the current behavior
Sandbox: https://stackblitz.com/edit/vitejs-vite-jdzfyh?file=src/App.vue

Used StackBlitz because I can't stand CodeSandbox
### What is the expected behavior?
To succesfully work as it should be, (no errors in the terminal regarding the compatibility between the Vue 2 and 3 version. And an updated version of the Vue guide about the third version.

### Does this happen only in specific situations?

I haven't tried with anything else, but for now it only happens when I import that specific line.
### What is the proposed solution?

I'm not sure of the solution. I can't comment anything on this regard.

### What is the version you are using?

```json
  "dependencies": {
    "algoliasearch": "4.11.0",
    "core-js": "3.19.1",
    "vue": "^3.2.22",
    "vue-instantsearch": "4.1.1"
  },
```
> Always try the latest one before opening an issue.

**Comment by Haroenv** [comment]
You're right that the documentation didn't yet add vue 3 imports, but they're all in the same style:

```
import { createWidgetMixin } from 'vue-instantsearch/vue3/es';
```

**Comment by Haroenv** [comment]
The documentation has been updated to explain where to import from everywhere now. Thanks for bringing this up again
