### ISSUE TITLE
Disjunction between many distincts facets

### ISSUE THREAD

**Issue by louislebrault** [algolia/vue-instantsearch#1102]
I encountered a special case that seems not possible to handle without writing a custom widget, as the documentation propose me to do im writing it as a feature request.

**Feature ⚡️**

### What is your use case for such a feature?

Refinement behaviors is that you get the results that matches all your refinement filters.

If i filter on a brand and a price, i’ll get the results that matches both the brand and the price.

I need to add some specific filters that work differently. I would like to be able to say “returns me the results that matches either refinementA, or refinementB, or refinementC.”

The reason is that those refinements are checking fields that are not present on all the products.

If i check a value for refinementA, i want to keep all the results that has no value for field corresponding to refinementA, but remove those that has a value for refinementA that does not match with the one i filtered one.

### What is your proposal

Adding a specific option ?

### What is the version you are using?

3.8.1

**Comment by Haroenv** [comment]
At the moment we don't have this behaviour yet, as based on market research, established patterns show that different filters are always applied conjunctively. In theory you probably could modify the actual search request to apply the filters disjunctively (as long as they're of the same type, you can't disjunct between different types in Algolia), but the facet count would still show what currently is expected, unless you make more drastic changes.

Could I know what the actual facets are and why you'd expect them to be joined disjunctively?

**Comment by louislebrault** [comment]
For a clothes e-commerce, there are different size categories depending on the nature of the cloth. A top will have a "topSize" field, when a hat will have no "topSize" but a  "headSize" field, for example. If a user filter on top sizes, we still consider we should show all hats, and show tops that has the size user selected.

**Comment by Haroenv** [comment]
I think what you're actually looking for is a multiple refinement lists on the same refinement, but each showing a subset of the facets. One way to do that is using transformItems, but knowing that you'll need to increase the max values per facet to have a high number of facets requested so you can filter efficiently:

https://codesandbox.io/s/dreamy-liskov-gf0z8?file=/src/App.vue

**Comment by louislebrault** [comment]
@Haroenv I cant use this solution as in the algolia database, size attributes are different depending on the nature of the item.
A hat will have his size in a "hatSize" field when a top will have his size in a "topSize" field.

I tried to use the searchFunction parameter without success.

**Comment by Haroenv** [comment]
Yes, sorry if I wasn't clear but that was suggesting a structure where there's only one size attribute that you display in different ways.

Trying to change the actual query using searchFunction won't help, as at that point you're still using `helper`, which doesn't allow disjunction between facets.

Your best bet (but facet count will be wrong) is something like this:

```js
const client = algoliasearch('', '');
const originalSearch = client.search;
client.search = function search(queries) {
  return originalSearch(
    queries.map(({ indexName, params: { facetFilters, ...params } }) => {
      const brandFilters =
        facetFilters.find((group) =>
          group.some((item) => item.startsWith('brand:'))
        ) || [];
      const categoryFilters =
        facetFilters.find((group) =>
          group.some((item) => item.startsWith('categories:'))
        ) || [];
      const otherFilters =
        facetFilters.filter((group) =>
          group.every(
            (item) =>
              !item.startsWith('brand:') && !item.startsWith('categories:')
          )
        ) || [];
      return {
        indexName,
        params: {
          ...params,
          facetFilters: [
            ...otherFilters,
            [...brandFilters, ...categoryFilters],
          ],
        },
      };
    })
  );
};
```

To have the correct facet count, you'll need to remove the facet filters from brand in the "facet count request" (has analytics set to false and hits per page 1) for categories, and the categories filter from brand request.

**Comment by louislebrault** [comment]
It is working like a charm. We're not displaying the counts anyway. Thank you for your help.

**Comment by Haroenv** [comment]
We might revisit this in the future, but for the time being, the solution mentioned earlier fits this use case well if facet count isn't displayed. Thanks for raising the feature request
