### ISSUE TITLE
 "export 'default' (imported as 'VueRouter') was not found in 'vue-router'

### ISSUE THREAD

**Issue by coderbob1024** [algolia/vue-instantsearch#1120]
**Bug 🐞**

### Make a sandbox with the current behavior

Template: https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch

### What is the expected behavior?
E:\A_data\A_Computer_books\2022.1.11\code\vue-study\myvue>npm run dev

> myvue@1.0.0 dev
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

(node:2352) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
 13% building modules 26/30 modules 4 active ...1.11\code\vue-study\myvue\src\App.vue{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
 95% emitting

 WARNING  Compiled with 45 warnings                                                                                                                                             17:15:25

 warning  in ./node_modules/_vue-router@4.0.14@vue-router/dist/vue-router.esm-bundler.js

1852:4-15 "export 'onUnmounted' was not found in 'vue'

 warning  in ./node_modules/_vue-router@4.0.14@vue-router/dist/vue-router.esm-bundler.js

1853:4-17 "export 'onDeactivated' was not found in 'vue'

 warning  in ./node_modules/_vue-router@4.0.14@vue-router/dist/vue-router.esm-bundler.js

1854:4-15 "export 'onActivated' was not found in 'vue'

 warning  in ./node_modules/_vue-router@4.0.14@vue-router/dist/vue-router.esm-bundler.js

1867:52-70 "export 'getCurrentInstance' was not found in 'vue'

 warning  in ./node_modules/_vue-router@4.0.14@vue-router/dist/vue-router.esm-bundler.js

1871:25-31 "export 'inject' was not found in 'vue'

 warning  in ./node_modules/_vue-router@4.0.14@vue-router/dist/vue-router.esm-bundler.js

1889:52-70 "export 'getCurrentInstance' was not found in 'vue'

 warning  in ./node_modules/_vue-router@4.0.14@vue-router/dist/vue-router.esm-bundler.js

1893:25-31 "export 'inject' was not found in 'vue'

 warning  in ./node_modules/_vue-router@4.0.14@vue-router/dist/vue-router.esm-bundler.js

2059:19-25 "export 'inject' was not found in 'vue'

 warning  in ./node_modules/_vue-router@4.0.14@vue-router/dist/vue-router.esm-bundler.js

2060:25-31 "export 'inject' was not found in 'vue'

 warning  in ./node_modules/_vue-router@4.0.14@vue-router/dist/vue-router.esm-bundler.js

2061:18-26 "export 'computed' was not found in 'vue'

 warning  in ./node_modules/_vue-router@4.0.14@vue-router/dist/vue-router.esm-bundler.js

2061:48-53 "export 'unref' was not found in 'vue'

 warning  in ./node_modules/_vue-router@4.0.14@vue-router/dist/vue-router.esm-bundler.js

2062:30-38 "export 'computed' was not found in 'vue'

 warning  in ./node_modules/_vue-router@4.0.14@vue-router/dist/vue-router.esm-bundler.js

2086:21-29 "export 'computed' was not found in 'vue'

 warning  in ./node_modules/_vue-router@4.0.14@vue-router/dist/vue-router.esm-bundler.js

2088:26-34 "export 'computed' was not found in 'vue'

**Comment by Haroenv** [comment]
How do you get those errors? in codesandbox it runs as expected, as well as locally for me
