### ISSUE TITLE
Trailing Slash

### ISSUE THREAD

**Issue by freeboxd** [algolia/vue-instantsearch#1124]
**Feature ⚡️**

### What is your use case for such a feature?

I am using the Pagination component (AisPagination).

### What is your proposal

I would like to add a way to add trailing slashes to hrefs such as the pagination ones

### What is the version you are using?

Ver ^4.3.3

**Comment by Haroenv** [comment]
The default history router gives complete URLs, so they have a trailing slash if that's the page you loaded, as you can see here https://codesandbox.io/s/sweet-kapitsa-9sfolu?file=/src/App.vue

Do you mind elaborating what's different in your case?

**Comment by freeboxd** [comment]
createURL option solved my problem. Thank you, I wasn't aware
