### ISSUE TITLE
Voice search language option

### ISSUE THREAD

**Issue by andyjamesn** [algolia/vue-instantsearch#1135]
**Feature ⚡️**

### What is your use case for such a feature?
To be able to set the language for voice search. There is no option on ais-voice-search to set the language as there would be when using the js voice search library.

### What is your proposal
Implement widget-param-language as an option on ais-voice-search
https://www.algolia.com/doc/api-reference/widgets/voice-search/js/?client=vue#widget-param-language

### What is the version you are using?
"vue-instantsearch": "^4.3.3",

**Comment by Haroenv** [comment]
Thanks for noticing, I've added a PR to forward those props (#1136), for the time being you can use the codesandbox preview version from that PR in your project, or patch it manually

**Comment by Haroenv** [comment]
v4.4.2 includes this option now!
