### ISSUE TITLE
Nuxt error using serverPrefetch with findResultsState

### ISSUE THREAD

**Issue by readio** [algolia/vue-instantsearch#1143]
**Bug 🐞**

### What is the current behavior?
When using serverPrefetch with findResultsState I get the following error:
`Cannot set property $nuxt of [object Object] which has only a getter` 

### Make a sandbox with the current behavior
[
Template: https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch](https://codesandbox.io/s/lingering-https-tuocvh?file=/pages/search.vue)

### What is the expected behavior?

Search page should render with Alogolia components

### What is the version you are using?
algoliasearch 4.14.2
vue-instantsearch 4.4.2

> Always try the latest one before opening an issue.

**Comment by Haroenv** [comment]
Hi, I've made a draft pull request in the past that I think should fix this, but never got a full reproduction to confirm it does. If you use the deploy preview of codesandbox of this PR: https://github.com/algolia/vue-instantsearch/pull/1117 in your project, and it solves the problem, that would be very helpful, thanks!

**Comment by readio** [comment]
Hi @Haroenv I can confirm that fix applied to `src/util/createServerRootMixin.js` fixes the error.

**Comment by Haroenv** [comment]
Perfect, I'll close this issue now then, as it will be released soon
