### ISSUE TITLE
<ais-instant-search :on-state-change: function /> is not implemented

### ISSUE THREAD

**Issue by chamby** [algolia/vue-instantsearch#1148]
**Bug 🐞**

### What is the current behavior?

`<ais-instant-search :on-state-change: function />` does not work because the `on-state-change` property is not implemented. I attempted to work around this using middleware directly `:middlewares="[() => { return {onStateChange: onStateChange}}]"` but the function signature of `onStateChange` does not include a `setUiState` argument.

### What is the expected behavior?

The parameter exists and operates as per the documentation.

[Documentation](https://www.algolia.com/doc/api-reference/widgets/instantsearch/vue/#widget-param-on-state-change) 

```
<ais-instant-search
  ...
  // Optional parameters
  :on-state-change: function
  ...
/>
```

### What is the version you are using?

v4.5.0

**Comment by Haroenv** [comment]
I've made the PR #1149 to add this, thanks for the suggestion
