### ISSUE TITLE
link in docs not working

### ISSUE THREAD

**Issue by nilsi** [algolia/vue-instantsearch#140]
It seems like the link in the docs is broken, has it moved?

https://community.algolia.com/vue-instantsearch

**Comment by rayrutjes** [comment]
Hey @nilsi ,

Thanks for jumping in.

This project is currently in Beta and we are still actively working on every aspect of it which includes documentation ;)

The page you are referring to is yet to be done and published.

For now, you can access the docs here: http://vue-instantsearch.netlify.com/

Feel free to report anything you do not understand ;)

If you are to proceed with testing this, please note that there is currently pending work to ameliorate the docs. You can access it here: https://deploy-preview-138--vue-instantsearch.netlify.com/

**Comment by nilsi** [comment]
Thank you, that looks great! Yes it would be awesome to try this out. I will be implementing Algolia very soon but Im not sure if I should go with the Javascript implementation or give this a shot. How far are you from a stable version and do you think the API will change later on? 

What I need to build is actually exactly like your example here:
https://deploy-preview-138--vue-instantsearch.netlify.com/examples/infinite-scroll.html

Looks nice but it seems like it needs some improvements with colors and materials. Is this due to bad data or something in the implementation itself?

Thanks

**Comment by rayrutjes** [comment]
This library is provides an easy way to integrate Algolia with the [Vue.js framework](https://vuejs.org/).

So if you are using Vue.js or plan to use it, then this library is definitely the good choice.

- If you are using React we also have a dedicated integration: https://community.algolia.com/react-instantsearch/
- If you are using plain JavaScript we also have an integration: https://community.algolia.com/instantsearch.js/

**Comment by vvo** [comment]
I think we can close this. @nilsi we would love to have your feedback if you try this library (you should), let us know via a new issue.

The docs are online on http://vue-instantsearch.netlify.com/ now.
