### ISSUE TITLE
Add [EDIT THIS PAGE] to docs

### ISSUE THREAD

**Issue by vvo** [algolia/vue-instantsearch#143]
Especially for new libraries, this will help a lot people to quickly edit mistakes.

**Comment by rayrutjes** [comment]
I think we should create 1 issue that is "create the build system for the docs" ;)

**Comment by vvo** [comment]
Doesn't gitbook provide this by default as an option?

**Comment by Haroenv** [comment]
https://github.com/rtCamp/gitbook-plugin-edit-link

**Comment by vvo** [comment]
and _voilà_
