### ISSUE TITLE
Edit UMD codepen to include vue with jsdelivr

### ISSUE THREAD

**Issue by vvo** [algolia/vue-instantsearch#145]
Feels weird to see on https://codepen.io/rayrutjes/pen/BRgyGV that you both use unpkg and jsDelivr.

Here's the jsDelivr url: https://cdn.jsdelivr.net/npm/vue@2.3.2/dist/vue.min.js

**Comment by rayrutjes** [comment]
unpkg is the default promoted Vue way so I thought I'd stick with that to not generate confusion.

**Comment by vvo** [comment]
Good point if people from Vue Community expect that. I did not know.
