### ISSUE TITLE
provide a way to run gitbook locally

### ISSUE THREAD

**Issue by vvo** [algolia/vue-instantsearch#153]
So that we can easily tune docs.

It also means that we would have to put gitbook as a devdep (and that would simplify the netlify build command)

**Comment by rayrutjes** [comment]
You can run gitbook locally by running:
```
gitbook install
gitbook server
```

**Comment by vvo** [comment]
will add that to the build then

**Comment by rayrutjes** [comment]
gitbook is only a temporary solution to focus on content. Don't spend too much time on it.
The idea is to leave it as decoupled as possible from the rest so that we can switch to something else in the upcoming weeks.

**Comment by vvo** [comment]
Yep, but still think it's pretty good for now!

**Comment by vvo** [comment]
done
