### ISSUE TITLE
Provide a nicer test/watch tests

### ISSUE THREAD

**Issue by vvo** [algolia/vue-instantsearch#154]
Current unit tests and tests watch env is a bit broken because:
- relies on the standalone, single-file, commonjs build, breaks code coverage
- relies on [concurrently](https://github.com/kimmobrunfeldt/concurrently) to run rollup watch and jest side by side (breaks jest interactive command line)
- fragile watch env: build may or may not be ready when tests are passing and you could be using a previous build

Ways to solve that:
- find the right approach to be able to require('component.vue') in jest tests
- wait for core Vue team to solve that

**Comment by vvo** [comment]
> find the right approach to be able to require('component.vue') in jest tests

cc @posva you have some context to this?

**Comment by vvo** [comment]
> (breaks jest interactive command line)

Just solved that, with --raw

**Comment by posva** [comment]
Hi! The truth is I still haven't used Jest with Vue but what I'm sure is that you need some kind of preprocessor. I found this one: https://github.com/vire/jest-vue-preprocessor who looks actively maintained. I looked at the code, and it looks like it's doing something similar to the rollup plugin, I also saw another core team member on the contributor list whom I know is using Jest to test Vue 🙂 
Hope it helps!

**Comment by rayrutjes** [comment]
Thanks for jumping in @posva .
We saw the preprocessor indeed, but it seems it doesn't solve the code coverage issue for now.
We might still want to give it a try to see if it improves our dev workflow.

**Comment by rayrutjes** [comment]
For the reference, is the official test tool that we could use in the future: https://github.com/vuejs/vue-test-utils
