### ISSUE TITLE
<ais-highlight> Does not support object

### ISSUE THREAD

**Issue by imsus** [algolia/vue-instantsearch#158]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
`<ais-highlight>` does not support object in `attribute-name` props.

**Bug: What is the expected behavior?**
`<ais-highlight>` should support string/array/object value.

**Bug: What browsers are impacted? Which versions?**
https://www.whatismybrowser.com/w/NYFRLGM

**Bug: What is the proposed solution?**
The problem actually on this line: https://github.com/algolia/vue-instantsearch/blob/master/src/components/Highlight.vue#L31

Proposed Solution:
Replace: `attributeValue = result._highlightResult[attributeName].value;`
To: `` attributeValue = `result._highlightResult.${attributeName}.value`; ``

**What is the version you are using? Always use the latest one before opening a bug issue.**
`"vue-instantsearch": "^0.2.1",`

**Comment by rayrutjes** [comment]
Thanks for the feedback @imsus ,

Indeed we only support a simple attribute so far.

Your solution would cover nested value access.

It would not solve the array support though. The problem with array is that you will want to be able to iterate over the values to for example join them with comas.

This definitely needs some work.

Feel free to suggest an API design.

**Comment by vvo** [comment]
One way to get object support: implement something like [lodash.get](https://lodash.com/docs/4.17.4#get) (kind of "JSON path"). This is what [we use in react-instantsearch](https://github.com/algolia/react-instantsearch/blob/133892eb9f1646db8510540511c5aa0fc662afe8/packages/react-instantsearch/src/core/highlight.js#L28).

Then for array support we could maybe have something like v-for inside the highlight or expose the method allowing to get the highlighted result from a hit (to then use it in a simple v-for method).

What do you think?

**Comment by rayrutjes** [comment]
> One way to get object support: implement something like lodash.get (kind of "JSON path"). This is what we use in react-instantsearch.

I think that is what @imsus suggests.

> Then for array support we could maybe have something like v-for inside the highlight or expose the method allowing to get the highlighted result from a hit (to then use it in a simple v-for method).

v-for could work indeed and already works. The only issues comes if you want to `join` with a coma.

**Comment by rayrutjes** [comment]
In #187 we are moving forward removing those brittle highlight & snippetting components so that you can use the values as usual.

That should solve your issue. Bear with us for the release.
