### ISSUE TITLE
Use vuejs/eslint-plugin-vue

### ISSUE THREAD

**Issue by rayrutjes** [algolia/vue-instantsearch#168]

**Comment by Haroenv** [comment]
This is in `eslint-config-algolia/vue`, right?

**Comment by rayrutjes** [comment]
No, we need to add it, but I think there were some issues with it. But now that @vvo cleaned up the repo, maybe we can try again.

**Comment by rayrutjes** [comment]
I'd like to summon @vvo on this one :p

**Comment by vvo** [comment]
Not sure it's ready yet, we need https://github.com/prettier/prettier/issues/2097 to ship more features I believe

**Comment by rayrutjes** [comment]
Ok let's wait for it then ;)
