### ISSUE TITLE
[Doc] <ais-input>

### ISSUE THREAD

**Issue by maxiloc** [algolia/vue-instantsearch#170]
Can we document \<ais-input\>

In my case I don't want to have the buttons that comes with \<ais-search-box\>

Also can we document how to bind to an existing input

**Comment by rayrutjes** [comment]
Thanks for the feedback, will do.
Opened a dedicated issue for the second part of your issue.

**Comment by rayrutjes** [comment]
I'm wondering why this was not autoclosed. @Haroenv , you are faster than the GH bot :trollface:

**Comment by Haroenv** [comment]
It wasn’t autoclosed since you wrote `fix 170` instead of `fix #170`

[source](https://github.com/blog/2398-manage-issues-and-pull-requests-with-keyword-updates)

**Comment by rayrutjes** [comment]
Oops 😫
