### ISSUE TITLE
[doc] Bind to existing input

### ISSUE THREAD

**Issue by rayrutjes** [algolia/vue-instantsearch#171]
Document how to bind query to an existing input.

**Comment by HemalR** [comment]
Plus one!

I'm trying to get an element-ui input (http://element.eleme.io/#/en-US/component/input) to be the Algolia input. 

I see the documentation regarding styling e.g. results, and that works well, but obviously, there is special binding regarding the input. I'll try to dig into the code and see if I can help out with creating documentation...

**Comment by rayrutjes** [comment]
Hey @HemalR ,

To bind to an existing input you would:
1. use `v-model` in your input to a variable named `query` for example: `<input type="text" v-model="query">`
2. bind the query to your `ais-index` like `<ais-index :query="query">`

Does that help?

**Comment by HemalR** [comment]
@rayrutjes Indeed it does! Thanks a tonne!

I spent a couple of hours (warning: noob alert) trying to create my own modified component based on the ais-input component - but for the life of me could not figure out the difference in the structure of how this repo is vs how it was showing up in my node modules! (If that makes sense...)

Also, your solution prompted me to look at the documentation of index and that has it all.

Thanks again!

**Comment by Haroenv** [comment]
This should be clear now, since it's documented in both the Vue documentation, as well as the new v2 documentation. See #416 for more info on that.
