### ISSUE TITLE
Linting issue

### ISSUE THREAD

**Issue by rayrutjes** [algolia/vue-instantsearch#192]
Currently, if there is no import statement in a <script> tag in a .vue file, linting fails :/

![image](https://user-images.githubusercontent.com/5570853/28466781-ca2ecb34-6e2d-11e7-8d1d-f9150ba74270.png)

**Comment by rayrutjes** [comment]
I think that this is related to the fact import statements are on the same line as scripts.

**Comment by timkley** [comment]
I tried reproducing the issue but didn't get any errors upon linting? Could you explain what I have to do to reproduce this?
