### ISSUE TITLE
Finalize docs migration

### ISSUE THREAD

**Issue by rayrutjes** [algolia/vue-instantsearch#202]
Things that needs to be addressed: 
- [x] Put back the examples section with the pages (see previous docs)
- [x] Update social medias metas in the header
- [x] ~See with @bobylito if we can add section names to the menu so that we can cross navigate easier~
- [x] Separate advanced concepts like SSR from the getting started (see previous docs)

cc @LukyVj let me know with which items I can help, probably better to sync on it.

**Comment by LukyVj** [comment]
Hello 
<details>world</details>

**Comment by Haroenv** [comment]
The css for highlighting for `js` and `sh` doesn't seem to be enabled, for `html` it works

**Comment by rayrutjes** [comment]
Just opened an issue for all the style issues we have #208 , feel free to add your feedback there @Haroenv if you find anything else ;)

**Comment by rayrutjes** [comment]
for js => javascript
for sh => shell

all good now
