### ISSUE TITLE
Make the getting started guide use the UMD build

### ISSUE THREAD

**Issue by rayrutjes** [algolia/vue-instantsearch#217]
Make the getting started guide use the UMD build directly from the browser.
It will shorten the guide, and make it easier to have users play with the library.

We can migrate the current getting started to another page (the next one?) as it is more close to real world projects.

cc @maxiloc

**Comment by Haroenv** [comment]
Makes sense, that's the same as the Vue tutorials

**Comment by rayrutjes** [comment]
I think I will leave the current docs as is, because:
1. we've had none asking about UMD since the launch
2. all templates installable with Vue CLI are using build steps and non UMD builds
3. the current docs is the way to go.
