### ISSUE TITLE
Pagination scroll to top

### ISSUE THREAD

**Issue by rayrutjes** [algolia/vue-instantsearch#231]
There is currently no easy way to scroll back to the top of the page when the pages changes.

We probably need to add events to the pagination component, or offer an easy to use feature to achieve this.

**Comment by Haroenv** [comment]
we have a `scrollTop` prop in React InstantSearch. We have the problem there, that _every_ refinement triggers a page change technically. We have to make sure that this edge case gets handled correctly in VIS

see https://github.com/algolia/react-instantsearch/issues/164

**Comment by rayrutjes** [comment]
Thanks for pointing that out @Haroenv .
JeffreyWay suggested this improvement and he said that just triggering an event, like "page changed" would already be good.

It's probably safer to let users deal with that event than to go to far.
