### ISSUE TITLE
Loop index: key does not work on <slot>

### ISSUE THREAD

**Issue by julienbourdeau** [algolia/vue-instantsearch#239]
I have included instantsearch this way

```js
import VueInstantSearch from './vue-instantsearch/src/instantsearch';
Vue.use(VueInstantSearch);
```

When compiling with Laravel Mix, I get the following error in `Results.vue`:

> `key` does not work on <slot> because slots are abstract outlets and can possibly expand into multiple elements. Use the key on a wrapping element instead.

I think that's why in my initial PR I named it `index`.

**Bug: What is the proposed solution?**
Rename `key` to `index`

**What is the version you are using? Always use the latest one before opening a bug issue.**
0.4.0

<img width="966" alt="1__laraconv2__node__and_price_range___vue_instantsearch" src="https://user-images.githubusercontent.com/1525636/28945005-9a85012e-7859-11e7-94c5-212a080cd5ed.png">

**Comment by rayrutjes** [comment]
Wow, seems like a bug issue.
Can I ask why you import './vue-instantsearch/src/instantsearch' instead of 'vue-instantsearch'?

I need to fix this ASAP.

**Comment by julienbourdeau** [comment]
Because I wanted to change something and test it (see #240)

If I use the package version, it works. It might be because of laravel mix config maybe 😕

**Comment by rayrutjes** [comment]
After investigation, it appears that the issue encountered is related to the fact that Vue instantSearch was downloaded locally, and transpiling was not setup properly.

That being said, this makes me realize we need to improve our contributing guide, to show an easy way to setup an environment to test changes in Vue IS directly in another project.
