### ISSUE TITLE
Refresh results in single page application

### ISSUE THREAD

**Issue by a4anes** [algolia/vue-instantsearch#241]
After adding new record, instant search <ais-results> does not update. I need a way to show new items. Is there any solution?

```vue
<ais-results>
	<template scope="{ result }">
		<li class="list-group-item">
			<a href="#"><strong><ais-highlight :result="result" attribute-name="name"/></strong></a>
		</li>
	</template>
</ais-results>
```

**Comment by Haroenv** [comment]
Just for clarity, you mean that when you add new items to the index, they don't show up immediately in the `results`?

**Comment by a4anes** [comment]
@Haroenv Yes, exactly.

**Comment by Haroenv** [comment]
It's not as simple as it seems, but it's possible. The first thing you need to do is use a custom search store, so that you can call methods on the API client. That's described [here](https://community.algolia.com/vue-instantsearch/getting-started/search-store.html#how-to-manually-create-a-search-store). Then in the place you're indexing, you'll need to [waitTask](https://www.algolia.com/doc/api-client/php/indexing/#wait-for-operations) so that you know _when_ a certain record is indexed. 

Once you have that information, you can send an event to your frontend (there are lots of ways to do that, for example with sockets) that signifies that the data needs to be updated. Once you receive that event, you can do `client.clearCache`.

Is that clear for you? Feel free to reopen if I didn't answer completely

**Comment by a4anes** [comment]
@Haroenv Is there no other way to do it? Like just reloading search component or appending results?

**Comment by Haroenv** [comment]
Not currently, but we could consider it. What kind of API would work well for that use case?

**Comment by a4anes** [comment]
Api for frontend or backend?

**Comment by a4anes** [comment]
What if i use search helper to get all results and render through vue js? Is there be any performance issue? Then i can push new item to results.

**Comment by rayrutjes** [comment]
Hey @a4anes ,
I think adding a method `refresh` to the search store makes sense.
This method would take care of clearing the underlying Algolia client's cache, and fetch the results again.

Would that work for you?

**Comment by a4anes** [comment]
@rayrutjes I'm using laravel package of algolia for backend and vue-instantsearch for frontend. I don't want to create custom search store but instead use vue-instantsearch components. Can you let me know what will work best in this case? It need to be index before refresh.

**Comment by rayrutjes** [comment]
@a4anes in your use case, I'm not sure how you could make your frontend aware that you indexed new things from the backend. I feel like this is out of the scope of this integration.

Can you tell me more about why you would need your users to have the very indexed items in your application?
One solution could be to create a `heartbeat` endpoint in your Laravel app that would check if new records have been indexed. And if so, you would trigger the refresh of the search.
This would require some custom code though both on frontend and on then backend.

I'd love to hear more about your use case.

**Comment by hellodeveloper** [comment]
@rayrutjes In our use case, users create records one by one and via bulk uploading files. We want to be able to search the very indexed records without forcing a refresh.

**Comment by rayrutjes** [comment]
Ok, I'm I correct assuming that from your single page app, users can actually trigger actions interacting with the backend that would push new records from the backend?

In that case, the best way to go about it would be to keep a reference to the search store somewhere, and hit the "upcoming" `store.refresh()` after the new items were pushed.

Like @Haroenv mentioned though, there will be a delay between the time you sent the actual indexing request and the time it's available from the search.

This is in general solved from the UX. You could create a simple button that refreshes the search.
I think we could actually create a very simple component for that.
Here is what I have in mind: 
![image](https://user-images.githubusercontent.com/5570853/28964313-8f6e5eda-790c-11e7-9c0b-78e437652052.png)

**Comment by a4anes** [comment]
@rayrutjes Yes. That is exactly what we are trying to do. So i have to create custom search store to do this? Is there any other way to do without creating custom search store because everything else is working well.

**Comment by rayrutjes** [comment]
Ok, in that case, we can easily create a component "<ais-resfresh>" that when pressed refreshes the results.

Then it would be your job though to define when to show/hide it based on other actions the user took in your application.

Does that make sense?

**Comment by rayrutjes** [comment]
@a4anes I'm currently working on this.
Could it be that what you are actually experiencing could be solved if the cache was disabled?

By default, the Algolia client caches the results. If the cache were to be disabled, it would always return the new results.

**Comment by Haroenv** [comment]
Doesn't the component still need to be made @rayrutjes

**Comment by rayrutjes** [comment]
It depends on the answer of @a4anes .
Maybe just disabling cache will be enough.

Also, I'm not a huge fan of introducing a component that is just a link with a callback.

If we could access the search store in a easier way, there would be no component needed.

```
<a @click="searchStore.refresh()">Refresh</a>
```

I think we will want to promote and enhance the docs about how to manually use the search store for advanced use cases.

**Comment by Haroenv** [comment]
Makes sense! (Should be a button though)

**Comment by a4anes** [comment]
@rayrutjes How to disable cache? I'm using a button to refresh results but still not updating.

**Comment by rayrutjes** [comment]
He @a4anes ,
The cache feature has not been released yet.

Please bear with us.

**Comment by ilearnio** [comment]
This is how I refresh results

```js
// In template
<ais-index ref="aisIndex" ...>
  ...
</ais-index>

// In "methods"
refreshResults () {
  if (this.$refs.aisIndex) {
    const searchStore = this.$refs.aisIndex._localSearchStore
    searchStore.clearCache()
    searchStore.refresh()
  }
}
```

**Comment by Haroenv** [comment]
This is also possible, thanks for sharing @ilearnio :)
