### ISSUE TITLE
[ssr] Work around the asyncData <> created hook issue

### ISSUE THREAD

**Issue by rayrutjes** [algolia/vue-instantsearch#263]
Currently some components need to change the state of the store before the first query.
The `asyncData` method pattern does not work in that case unless you manually register the facets and everything again.

We need to find a way to not have to duplicate that information. Remove the current declarative components is of course not an option.

**Comment by rayrutjes** [comment]
Unfortunately, official docs states the following:
> During SSR, we are essentially rendering a "snapshot" of our app, so if the app relies on some asynchronous data, these data need to be pre-fetched and resolved before we start the rendering process.

I'm afraid that the "rendering" process includes the creation of the components.
Currently registration of facets etc. happens on the `created` hook.

It would be nice if rendering and components instantiation were to be 2 steps so that we can actually hook between them to load async data.

Needs more digging.

**Comment by rayrutjes** [comment]
After investigating vue-router / vue.js ssr / nuxt.js it seems there is no solution.
The rendering process is de-coupled from the async data fetching which must happen before.
As a result, the only solution is to manually register facets etc.

**Comment by Haroenv** [comment]
You might be inspired by the option to hydrate we added in React InstantSearch https://community.algolia.com/react-instantsearch/guide/Server-side_rendering.html

**Comment by rayrutjes** [comment]
We currently have the same design.
The only difference beeing that the only place the store is aware of the existing components is in the actual template.

I'll put more thoughts into it but I think for now duplicating some of the initializing option makes sense.

**Comment by rayrutjes** [comment]
I tried to better explain the issue here: https://forum.vuejs.org/t/ssr-asyncdata-fetching-after-components-were-created/15382
Maybe someone with deep understanding of the core of Vue could help us.

**Comment by Haroenv** [comment]
Do you know how to deal with this @posva? Basically we would have to wait until a component is mounted before we can know what data to fetch

**Comment by rayrutjes** [comment]
This is now mainly about documenting it properly.

**Comment by posva** [comment]
Looks like Thorsten solved it 🙂

**Comment by rayrutjes** [comment]
Yes, in the end we will go for duplicating the params @posva .
Not ideal but there is no other solution.

We will also check if there are any pros of leveraging Vuex for sharing state with the front.

**Comment by rayrutjes** [comment]
Closing this, as there is not much actionable here for now.
