### ISSUE TITLE
Geo-Search

### ISSUE THREAD

**Issue by socieboy** [algolia/vue-instantsearch#299]
Can I use Geo-Search with this component for Vue?

**Comment by julienbourdeau** [comment]
Yes you can. Can you describe what you want to achieve so we can provide better help?

**Comment by socieboy** [comment]
I have all records in algolia of videos filmed on different locations i save the coordinates of the location on the _geoloc tag, but using this component for vue i want to display the map all videos. How can i do that?

**Comment by julienbourdeau** [comment]
Most of the job is not really related to Algolia, you'll have to display the map and pointers. then you can use `<ais-results>` to loop through the result. I have use this library in the past: https://github.com/xkjyeah/vue-google-maps

If you choose to go with this one, for example, the code would look like this:

```html
<gmap-map
        :center="{lat:10, lng:10}"
        :zoom="12">

    <ais-results>
        <template scope="{ result }">

            <gmap-marker :position="result._geoloc"></gmap-marker>

        </template>
    </ais-results>

</gmap-map>
```

*Note*: You need to ensure that the _geoloc values are floats, not strings.

**Comment by socieboy** [comment]
@julienbourdeau thank you for your response, i will try to use the package.

**Comment by socieboy** [comment]
@julienbourdeau  It work's perfect, i love it. thanks!
