### ISSUE TITLE
extending components

### ISSUE THREAD

**Issue by socieboy** [algolia/vue-instantsearch#301]
Extending component is not working i just exactly as the docs, and seems like the extended component it's not accessing the results

**Comment by rayrutjes** [comment]
Hey @socieboy ,

Do you mind sharing your code so that we can try it out?

**Comment by socieboy** [comment]
I have a main component
```
import { createFromAlgoliaCredentials } from 'vue-instantsearch';
import MapResults from './map-results.vue';
Vue.component('videos-index', {
    data() {
        return {
            searchStore: createFromAlgoliaCredentials('xxx', 'xxxxxxxxx'),
        };
    },
    components: [MapResults],
})
```
Then on the view
```
<videos-index>
 <ais-search-box :search-store="searchStore"></ais-search-box>
        <ais-index :search-store="searchStore" index-name="index-name">
            <map-results></map-results>
        </ais-index>
</videos-index>
```
MapResults.vue
```
<template>
    <div>
        <p v-for="result in results">
            Result 'objectID': {{ result.objectID }}
        </p>
    </div>
</template>

<script>
import { Component } from 'vue-instantsearch';
import { Results } from 'vue-instantsearch';
export default {
    extends:Results,
    mixins: [Component],
};
</script>
```
This is my code, i don't see anything on the console vue-devtools on the MapResults component.

**Comment by rayrutjes** [comment]
Can you try removing `mixins: [Component],` from your MapResults.vue component?
Given you extend the Results component, there should be no need to add the mixin again.

**Comment by rayrutjes** [comment]
Hey @socieboy I'm closing this for now.
Please let us know if it worked out for you, and feel free to re-open if the problem persists.
