### ISSUE TITLE
Query rules guide

### ISSUE THREAD

**Issue by bobylito** [algolia/vue-instantsearch#306]
Query rules is a new feature in the Algolia engine. Even though most of the impact is in the engine and most of the answer modifications should be hidden, we have identified two cases where we need to provide some help on how to integrate them:
 - when a result is promoted
 - how to access custom data from the rules engine

The idea is to make a guide for that.

This is linked to https://github.com/algolia/algoliasearch-helper-js/issues/529

**Comment by rayrutjes** [comment]
Do we have anything actionable here @bobylito ?

**Comment by Haroenv** [comment]
QR exact changes needed

- Deal with `userData`
  - Add this response parameter in the helper
  - Expose in IS allHitsTemplate
  - Expose in `<Conditional />`
- Deal with Context
  - Simply pass the parameter to `search({context: 'mobile'},{})`
- Deal with `rankingInfo` (promoted)
  - getRankingInfo: true, then _rankingInfo similar to geosearch or highlighting

Copied from meeting document today @rayrutjes

**Comment by rayrutjes** [comment]
Interesting,
Will wait and see the helper's implementation 👍
