### ISSUE TITLE
Slack-style Search+Quick Search component

### ISSUE THREAD

**Issue by tetshi** [algolia/vue-instantsearch#308]
A key-navigable tree view, similar to Slacks "Quick Jump" functionality would be nice. This would handle a simple JSON structure like:
`[
    {
        "name":"Page Title",
        "url" : "#page",
    }
]
`

This would be nice because of how Algolia handles ratings of a search, it would automatically enable the user to have a list of their most frequently visited spots in a web app. 

Proposed tag: 
<ais-navigable></ais-navigable>

**Comment by Haroenv** [comment]
To be clear, this is something you want, right? 

<img width="467" alt="screen shot 2017-09-19 at 11 00 36" src="https://user-images.githubusercontent.com/6270048/30584408-e8ce1e84-9d29-11e7-9e3b-0a3ae04ba931.png">

You should already be able to create that, by having a component that has `<ais-index>`, `<ais-search-box>` and `<ais-results>`. 

Did you try to create this interface and bump into issues? 

You can make an interface like that even faster than normal by restricting the `attributesToRetrieve` to only the relevant ones.

**Comment by rayrutjes** [comment]
Please feel free to re-open this discussion [on our forum](https://discourse.algolia.com/), super interesting topic 👍 .
