### ISSUE TITLE
Guide on replicating refinement-list

### ISSUE THREAD

**Issue by Haroenv** [algolia/vue-instantsearch#310]
See https://discourse.algolia.com/t/vue-instant-search-facet-filters/2724/5 for more information. 

This user wants to use a third-party select list [component](http://element.eleme.io/#/en-US/component/select) as a refinement-list and has trouble doing it. 

We should be able to explain this in our guide, a specific guide, or just as an answer on discourse

**Comment by rayrutjes** [comment]
The best to solve that is: 
- https://community.algolia.com/vue-instantsearch/getting-started/styling.html#overriding-templates-with
- https://community.algolia.com/vue-instantsearch/getting-started/styling.html#extending-a-component

**Comment by rayrutjes** [comment]
I've answered the thread, thanks for picking that one up @Haroenv .
I will close for now and wait for more feedback.

**Comment by mydnic** [comment]
@rayrutjes the guides are not very clear about customizing the refinement-list. What if I want to replace my facets labels with images instead of text ?

Another example: I have a model User with boolean attributes:
is_moderator : true/false
is_admin : true/false

How can I filter through these with refinement-list component?

**Comment by Haroenv** [comment]
@mydnic the process has these steps

1. make a new component
2. copy in it the contents of [RefinementList.vue](https://github.com/algolia/vue-instantsearch/blob/master/src/components/RefinementList.vue)
3. change imports:

```diff 
- import { FACET_OR, FACET_AND } from '../store';
- import algoliaComponent from '../component';
+ import { FACET_OR, FACET_AND, Component from 'vue-instantsearch';
```

4. change mixin:

```diff
-   mixins: [algoliaComponent],
+   mixins: [Component],
```

5. Change view logic to whatever you need to have correct rendering

Hope that makes sense
