### ISSUE TITLE
Tree Shaking not working / ES2015 module format?

### ISSUE THREAD

**Issue by katoba86** [algolia/vue-instantsearch#311]
I followed the guide to import the components to build the example project [https://community.algolia.com/vue-instantsearch/getting-started/using-components.html](url) 

Registering all components at once gives me  a filesize of **275kb**

`import InstantSearch from 'vue-instantsearch';
Vue.use(InstantSearch);
</script>`

. okay this is too much, because I'm , using only the "Index, SearchBox, Results", so i ONLY import the necessary components...

`import { Index, SearchBox, Results } from 'vue-instantsearch';

Vue.component('ais-index', Index);
Vue.component('ais-search-box', SearchBox);
Vue.component('ais-results', Results);
Vue.component('ais-pagination', Pagination);
`

Running the build again gives me.... the same filesize - **275kb**. 
Tree Shaking is working for all other modules... but not for vue-instantsearch. 

TestProject was installed by npm: **vue init webpack vue-instantsearch-getting-started**
Installed the library this way:  **npm install --save vue-instant-search** 
Command: **npm run build** 

Is vue-instantsearch compiled into an es2015 module format?

**Comment by Haroenv** [comment]
Vue InstantSearch is written in es2015 modules, but tree shaking is one of the lot finicky parts of technology I’ve ever worked with. Thanks for reporting though, we will investigate what the cause is, we’re sorry.

**Comment by rayrutjes** [comment]
Thanks for reporting this @katoba86 .

Just opened a PR here: #312 

Please don't expect to much in the size drop, because currently what weights a lot is the Algolia client + Algolia helper. This will get better in the future.

**Comment by katoba86** [comment]
Very nice! Thank you!

**Comment by rayrutjes** [comment]
It is now available under 1.0.1 tag @katoba86 
See: https://yarnpkg.com/en/package/vue-instantsearch
