### ISSUE TITLE
Add currently refined values component

### ISSUE THREAD

**Issue by lukepearce** [algolia/vue-instantsearch#314]
**Do you want to request a *feature* or report a *bug*?**
Feature

**Feature: What is your use case for such a feature?**
The current refined values widget would have two purposes:

- give the user a synthetic view of the current filters.
- give the user the ability to remove a filter.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
The standard instantsearch.js has a component for displaying all currently selected refinements. Can the equivalent be added as to the Vue library?

https://community.algolia.com/instantsearch.js/v2/widgets/currentRefinedValues.html

**Comment by rayrutjes** [comment]
Hey @lukepearce ,
We will be working in the near future in filling the gaps in terms of features between the different instantsearch implementations.

In the meantime, please bear with us.

Please note that we have not explicit ETA on this though.

**Comment by rayrutjes** [comment]
We are now tracking all missing components in #334 👍

**Comment by terranboy** [comment]
Hi ,when will CurrentRefinement component be released? 
Thank you

**Comment by Haroenv** [comment]
There's no current roadmap for that @terranboy
