### ISSUE TITLE
Add Props to Change Default Text

### ISSUE THREAD

**Issue by MelkerB** [algolia/vue-instantsearch#315]
For example on the Rating.vue component there should be a prop to change " & up" and "Clear" to fit different purposes as well as languages.

**Comment by rayrutjes** [comment]
Hey @MelkerB ,

We provide a slot for you to override that text.
Here is what you could do:

```js
<ais-rating>
    <template scope="{ value, min, max, count }">
        <template v-for="n in max">
            <span v-if="n <= value">&#9733;</span>
            <span v-else>&#9734;</span>
        </template>
        &nbsp;&amp; up
        <span>{{facet.count}}</span>
    </template>
</ais-rating>
```

You could also override everything by using an `inline-template`, see: https://community.algolia.com/vue-instantsearch/getting-started/styling.html#overriding-templates-with

Let me know if that helps.

**Comment by MelkerB** [comment]
Definitely, thanks.

**Comment by NicolasPK** [comment]
Hey @rayrutjes ,

I looks like there's [a slot for clear now](https://github.com/algolia/vue-instantsearch/blob/master/src/components/Rating.vue#L6), could you do the same for the `& up`?
Your solution doesn't allow me to add facet, or the `bem()` function (obviously) and all I want to do is amend this text.

Cheers
