### ISSUE TITLE
Event: "ready" or "loading"

### ISSUE THREAD

**Issue by grund3g** [algolia/vue-instantsearch#317]
Ist there any possibility to listen for an event when the search result is ready or loading?

The only event that I found ist "page-change" when using the pagination.

**Comment by Haroenv** [comment]
Hey @grund3g, what would you use this for? What would be your ideal use case?

**Comment by grund3g** [comment]
Hi,
e.g. when using masonry layouts where I have to update / recalculate the layout when the search result is ready.

**Comment by rayrutjes** [comment]
Maybe you can ask the user who has already done this here: https://discourse.algolia.com/t/algolia-instantsearch-vue-with-masonry-js/2215/2

**Comment by grund3g** [comment]
Thanks for the link! I ended up doing the following:

```
 <ais-index :app-id="xxx" :api-key="xxx" index-name="xxx">
    <ais-event-wrapper>
        // Other Components
    </ais-event-wrapper>
</ais-index>
```

// AisEventWrapper.vue
```
<template>
    <div>
        <slot>
        </slot>
    </div>
</template>

<script>
import { Component } from 'vue-instantsearch';
export default {
    mixins: [Component],
    watch: {
        'searchStore._results'(val) {
            // Emit event
        }
    }
}
</scritpt>
```

**Comment by Haroenv** [comment]
That seems like a good solution! I'll close this, but feel free to reopen or open another issue for other things 😄

**Comment by Haroenv** [comment]
@intrepidws, could you open a new issue, is this also for masonry?
