### ISSUE TITLE
[ais-search-box] Unable to change the class names of the Clear button

### ISSUE THREAD

**Issue by pixelastic** [algolia/vue-instantsearch#318]
**Do you want to request a *feature* or report a *bug*?**
feature

**Bug: What is the current behavior?**
When passing `class-names` to `ais-search-box`, I cannot override the class added to the clear button.

On this codepen I can correctly add a specific class to the submit element, but not to the clear one: https://codepen.io/anon/pen/wryRMb

**Feature: What is your use case for such a feature?**
I'm using a CSS framework (tachyons.css) that expect me to add CSS classes to the elements I want to style (similar to atomic css). I don't want to add new CSS selectors to target the clear element that would duplicate styling I have for something else.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
Just like I can override the class added to `ais-search-box__submit`, I would expect to be able to override the class passed to `ais-clear`.

I would first suggest to rename the CSS class used on the clear button to more specifically mark that it is used in the context of the search box, and using `ais-search-box__clear` instead of `ais-clear` as the default class added.

As a second step, I would allow the passing of `class-names.ais-search-box__clear` to override this CSS class setting directly from the props.

**Comment by pixelastic** [comment]
After digging a bit more in the code and the examples, I found that could achieve my goal simply by using `ais-input` instead of `ais-search-box` (I actually wanted to remove the submit and clear buttons).

This is a much easier solution in my case, but the above issue still stands.

**Comment by Haroenv** [comment]
I would’ve suggested the ais-input, but seems like that class isn’t implemented correctly indeed

**Comment by rayrutjes** [comment]
Hi @pixelastic ,
Here is an example to achieve what you want: https://github.com/algolia/vue-instantsearch-examples/blob/master/examples/e-commerce/src/App.vue#L11

I think that solves the issue.

Let me know if it doesn't.
