### ISSUE TITLE
Refinement List - option to have all values at all time.

### ISSUE THREAD

**Issue by OneX** [algolia/vue-instantsearch#324]
Is there a way to set all facet filters that are possible, and not to remove them if we use another facet filter.

Seems much more User-Friendly when creating UI.

**Comment by OneX** [comment]
Example: https://community.algolia.com/vue-instantsearch/examples/bootstrap.html

Set Color to White and Dark Gray, then select Material to Glass.

Now Dark Gray option has a count of 0, and if I click on it, it disappears.
 
And now I need to toggle Material Option to get value back, so it seems little confusing.

**Comment by Haroenv** [comment]
Hey @OneX, this is a complicated issue to solve, in a lot of cases there just are too many options to show, and it would cause the search to be really slow if we want to show those options too. 

A way around this is to add search for facet values, as described in #224, but this hasn't been implemented in this library yet.

**Comment by mydnic** [comment]
Hello @Haroenv 
One year later, what's the solution for this ?

I have 4 refinement list that each have 2 values (true and false). If I use the search input and type some random stuff, the refinement lists disappear. But they are part of my UI so I prefer to have them display at all time even if clicking on the facet won't bring any new result.
Furthermore it's sometimes buggy, they don't reappear when cleaning the search input

Thanks in advance!

**Comment by OneX** [comment]
@mydnic you can build custom plugin using code from refinement list, you provide your own list of options you have for each list, then you create a method that compares you list with refinement list coming from Algolia. This is the only solution I could come up, that would not take too much time to do.

**Comment by Haroenv** [comment]
Note that in the next version of Vue InstantSearch; we _will_ have searchable on the refinement list
