### ISSUE TITLE
Suggestion, how to store filter params?

### ISSUE THREAD

**Issue by OneX** [algolia/vue-instantsearch#329]
For example, imagine we add some text to search, then we click on couple facet refinements, then we open detail of some entry from return index, and we need to return back (so we have to go back in a browser history). Is there a way to easy return parameters of the last search?

**Comment by Haroenv** [comment]
You can store it in the URL, as described in the [vue-router](https://community.algolia.com/vue-instantsearch/advanced/vue-router-url-sync.html) guide

**Comment by OneX** [comment]
That is one option, but what is an option if we don't use vue-router? I guess one option is to save parameters to localStorage?

**Comment by Haroenv** [comment]
Yep, that's the other option, or you can handle it yourself with `history.pushState`, rather than an invisible option with localStorage
