### ISSUE TITLE
Stats component is not always display

### ISSUE THREAD

**Issue by samouss** [algolia/vue-instantsearch#330]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**

The `Stats` component is not always visible even if the `totalResults` is greater than `0`.

- on initial load the `Stats` component is not visible (`'10,000' > 0` => `false`)
- search for `He`
- it will be now visible (`'444' > 0` => `true`)

https://codepen.io/anon/pen/BwGGwE?editors=1010#0

**Bug: What is the expected behavior?**

The `Stats` component should always be visible when `totalResults` is greater than `0`.

**Bug: What browsers are impacted? Which versions?**

All.

**Bug: What is the proposed solution?**

The `totalResults` computed property pass to the view is converted to a string with `toLocaleString()`. So the condition for display the content is not always predictable. 

We should pass two variables to the view, one for the display the count and the other for the condition.

**What is the version you are using? Always use the latest one before opening a bug issue.**

`1.2.0`

**Comment by rayrutjes** [comment]
Thanks for reporting this @samouss will fix it in the hour.

**Comment by rayrutjes** [comment]
Looks like we went a little bit to fast @ehayman 😂

**Comment by rayrutjes** [comment]
This is now fixed in 1.21.0 🎉 
Thanks again @samouss
