### ISSUE TITLE
Umbrella IS missing components

### ISSUE THREAD

**Issue by rayrutjes** [algolia/vue-instantsearch#334]
This issue lists all the components available in other IS implementations that will need to be implemented.

#### Components:
- [ ] Analytics
- [ ] Breadcrumb
- [ ] CurrentRefinedValues
- [ ] NumericRefinementList
- [ ] NumericSelector
- [ ] MenuSelect

**Comment by Haroenv** [comment]
Also needs SFFV in RefinementList, see #224

**Comment by samouss** [comment]
Also needs `MenuSelect` widget.

> https://community.algolia.com/react-instantsearch/widgets/MenuSelect.html
> https://community.algolia.com/instantsearch.js/v2/widgets/menuSelect.html

**Comment by rayrutjes** [comment]
Added @samouss

**Comment by Haroenv** [comment]
addressed in #416
