### ISSUE TITLE
Displaying some sort of placeholder instead of hiding component when there are no facets

### ISSUE THREAD

**Issue by Rias500** [algolia/vue-instantsearch#347]
**Do you want to request a *feature* or report a *bug*?**

Feature

**Feature: What is your use case for such a feature?**

When a component has no facets or results then they get hidden, but in my current implementation this makes it look like the interface broke, see screenshots for an example:

*With results (ok)*
![image](https://user-images.githubusercontent.com/3626559/31890093-4e1b3874-b802-11e7-85b6-081e6e627889.png)

*Without results (looks broken)*
![image](https://user-images.githubusercontent.com/3626559/31890121-5e71463c-b802-11e7-8e46-189bad9d9516.png)

I can't see any way to still display something when there are no results.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

Add a `placeholder` slot or something comparable to still show some sort of message or button when the component would be hidden.

**What is the version you are using? Always use the latest one before opening a bug issue.**

Latest

**Comment by rayrutjes** [comment]
Interesting feedback @Rias500 , WDYT  @ronanlevesque ?

**Comment by michaelpumo** [comment]
Just chiming in, but I think this term is known as “ghosts”. Essentially showing facet links that would result in zero results. 

I think it’d be nice to have this, especially from a UX perspective as it can help the user have a better understanding with what’s going on. 

There is a plugin for WordPress that produces Facet searching and it had this option. See example doc here:
https://facetwp.com/documentation/checkboxes/

**Comment by batFormat** [comment]
@Haroenv Can you please tell me if such a function is planned in `v2?

**Comment by Haroenv** [comment]
In v2 you can do this, but only when you are making fully custom components (using createWidgetMixin). This is probably something we should make achievable using the panel.
