### ISSUE TITLE
Multi Index with Nuxt?

### ISSUE THREAD

**Issue by abattenburg** [algolia/vue-instantsearch#348]
Is it possible to use multiple indexes with Nuxt? I'm attempting to search inside a sub component with a different index, but unfortunately Nuxt provides the `asyncData` hook only on `pages` and not standard components. 

To get around this I'm hoping to pass a second index as a prop, but whenever I try to return two separate search stores in the asyncData method, I seem to overwrite the first store when trying to instantiating the second. 

The other tactic i've tried is calling an async method on the `mounted() `hook per the Nuxt [documentation,](https://nuxtjs.org/faq/async-data-components/) but that always returns an error that there is no data. I'm attempting something like this.

```vue
<script>
import {
  createFromAlgoliaCredentials,
  createFromSerialized
} from 'vue-instantsearch'
const searchStore = createFromAlgoliaCredentials(
  '',
  ''
)
searchStore.indexName = 'Products'

export default {
  data() {
    return {
      searchStore: null
    }
  },
  mounted() {
    this.startAlgolia()
  },
  created() {
    this.searchStore = createFromSerialized(this.serializedSearchStore)
  },
  methods: {
    async startAlgolia() {
      searchStore.start()
      await searchStore.waitUntilInSync()

      return { serializedSearchStore: searchStore.serialize() }
    }
  }
}
</script>
```

Is there any example out there of implementing something like this? Thanks!

**Comment by rayrutjes** [comment]
Hey @abattenburg, thanks for pinging us.

Can you confirm you are trying to have this all working with Server Side rendering?
In that case, the best example we have so far is: https://github.com/algolia/vue-instantsearch-examples/blob/master/examples/nuxt/pages/search.vue

However, SSR is definitely tricky. For now, I would recommend you always load the state from pages, because like you said, it's the only place where it works by default.

I'd gladly see the full repo if accessible.

**Comment by abattenburg** [comment]
Hi @rayrutjes, thanks for looking at this. Currently my setup is exactly like the link you put as an example. But instead of using just one index (`searchStore.indexName = 'bestbuy'` in this case), I would like to add a second index to be used on the same page. Maybe `searchStore.indexName = 'bestbuy'` and `searchStore2.indexName = 'reviews'` or something like that for example. 

You have a good example here: https://github.com/algolia/vue-instantsearch-examples/blob/master/examples/multi-index/src/App.vue showing two indexes, but I'm having trouble using the same concept with SSR. 

I can put together a repo if you would like, but my structure is pretty much exactly the same as the example you posted. Everything I had posted before, was just attempted work arounds to put two index's on one page. Sorry for the lack of context, and let me know if a repo would still be helpful. Thanks again for looking at this!

**Comment by abattenburg** [comment]
Great thank you so much! That's exactly what I was hoping for.
