### ISSUE TITLE
Question : How to search by _geoloc and date (in unix)

### ISSUE THREAD

**Issue by foufrix** [algolia/vue-instantsearch#352]
Hello again,

I have to search data using date and _geoloc (algolia data are ready with date in timestamp and _geoloc to search by geoloc) but how do i search that with vue-instantsearch ? 

I think that i have to use SearchStore, am i right ? if it's possible an example would be nice :)

Thanks in advance !

**Comment by rayrutjes** [comment]
Hey @foufrix, you might find this inspiring: https://discourse.algolia.com/t/vue-instantsearch-distance-filter/3309/7

Let me know if that helps or if you'd like more precise help,

**Comment by foufrix** [comment]
As always, quick response by the team thanks ! 
For those who find this post here is the code that solved my problem 
`this.searchStore.queryParameters = { aroundLatLng: '' + this.searchLat + ', ' + this.searchLng + '', aroundRadius: 20000, numericFilters: '[\"start_time_unix >1509584830\"]' }`

with searchLat latitude, searchLng longitude and start_time_unix the unix time i want to filter

**Comment by Haroenv** [comment]
perfect @foufrix, have a great day!
