### ISSUE TITLE
compose a link to filter a result and switching between two indices

### ISSUE THREAD

**Issue by iamraphson** [algolia/vue-instantsearch#360]
Hello,
Currently facing 2 issues at the moment. I have to 2 indices(groups and students). Groups Indice contains group details and list of students under it. 

first, I want to compose a URL/route in such a way when I click on a group, it will take students index page which will be filtered by group. 

secondly, I defined a facet `age` on my student index. switching between the 2 indices page(groups and students) using, i got an error ` Error in render: "Error: age is not present in facets or disjunctiveFacets"`. I don't know what went wrong but when I do a hard refresh, the age filter will display. Note: I'm using `ais-range-input` component for the age facet.  

### After Hard refresh. 
![image](https://user-images.githubusercontent.com/3502724/32748706-59067322-c8bd-11e7-92fb-b12de4d9b8a8.png)

#### After switching between group page and student page
![image](https://user-images.githubusercontent.com/3502724/32748655-36679e72-c8bd-11e7-924b-a085bf1ecba4.png)

**Comment by rayrutjes** [comment]
Is there any chance you could share a isolated example to re-produce this?

It think this is related to the way we remove facets when components get destroyed.

**Comment by iamraphson** [comment]
@rayrutjes  sure
```
 <ais-range-input attribute-name="age" :class-names="{
                                            'ais-range-input__input': 'form-control',
                                            'ais-range-input__submit': 'btn btn-success range_submit'
                                            }"></ais-range-input>
```
```
 <router-link to="/group" class="btn btn-lg btn-info"><i
                                            class="fa fa-fw fa-group"></i>
                                        <span class="text">Groups</span></router-link>
                                    <router-link to="/" class="btn btn-lg btn-info active"><i
                                            class="fa fa-fw fa-user"></i>
                                        <span class="text">Student</span></router-link>
```
```
<script>
	require('spark-bootstrap')
	import {createFromAlgoliaCredentials} from 'vue-instantsearch'

	const searchStore = createFromAlgoliaCredentials('xxxx', 'xxxxx')
	searchStore.indexName = 'profiles'
	export default {
		components: {
		},

		props: {
			queryParameters: {
				type: Object,
				default: {},
			},
		},
		data() {
			return {
				searchStore,
				indexSelected: 'people',
				action: 'email',
                col: 'list',
				page: 1,
				
                },
              
			};
		},
		watch: {
			'searchStore.queryParameters'(parameters) {
				const query = parameters;
				delete query.index;
				this.$router.push({
					name: 'searchPeople',
					query,
				});
			},
		},
	};
</script>
```

**Comment by iamraphson** [comment]
@rayrutjes how will I component the URL please in such a way that it will go to the other index, filtered.

**Comment by rayrutjes** [comment]
@iamraphson could you create a small repo with the code so that we can run it?
I don't see any obvious things that could be problematic in the above code so we would have to run it.

Maybe @samouss can help on this one.

**Comment by iamraphson** [comment]
@rayrutjes thanks 

Hi @samouss ..can i invite to a private repo?

**Comment by iamraphson** [comment]
@rayrutjes I think something is wrong with `ais-range-input` component. I tried it with `ais-price-range` component and I switch between pages and it worked fine with no error.

**Comment by iamraphson** [comment]
@rayrutjes @samouss send a mail to support@algolia.com. please kindly help. This's urgent

**Comment by Haroenv** [comment]
This issue seems to have been resolved after messaging support
