### ISSUE TITLE
How to put the result in string in Laravel blade?

### ISSUE THREAD

**Issue by majidsajadi** [algolia/vue-instantsearch#364]
I`m using vue instantsearch in my web application and it works great but how can i put id of my records in href attribute of <a> ?
my blade template : 
`<div id="app">

		<ais-index app-id="{{ config('scout.algolia.id') }}"
		api-key="{{ config('scout.algolia.secret') }}"
		index-name="doctors">

		<ais-input placeholder="Search doctors..."></ais-input>

		<ais-results>
			<template scope="{ result }">

				<div class="card widget">				
					<div class="avatar">
						<img src="/img/avatar.png">
					</div>
					<div class="name">
						<h3>doctor @{{ result.firstname }} @{{ result.lastname }}</h3>
						<p>@{{ result.general }}</p>
						<a href="doctors/@{{ result.id }}">
							<button class="button button-outline button-small">more</button>
						</a>
					</div>
				</div>

			</template>
		</ais-results>

	</ais-index>

</div>`
i could not find anything in the documentation.

**Comment by vvo** [comment]
Hi @majidsajadi if you find how to solve this, can you add a comment on how you solved it? This will help future GitHub searches.
