### ISSUE TITLE
Powered-by component is not SSR compatible

### ISSUE THREAD

**Issue by Jexordexan** [algolia/vue-instantsearch#367]
**Do you want to request a *feature* or report a *bug*?**

bug

Steps:

- Create an empty `nuxt` starter project and install `vue-instantsearch`

- add an `<ais-powered-by>` component into one of the templates

- run `npm run dev`

- visit the page with the component and notice the error screen saying `location is undefined`

**Bug: What is the current behavior?**

`<ais-powered-by>` is not SSR compatible, 

**Bug: What is the expected behavior?**

The component should be compatible with ssr

**Bug: What browsers are impacted? Which versions?**

This is an SSR issue, so node.js?

**Bug: What is the proposed solution?**

Add a null check for the `location` object

**What is the version you are using? Always use the latest one before opening a bug issue.**

1.3.2

**Comment by Haroenv** [comment]
Oh thanks for noticing that. Feel free to add a or if you want

**Comment by Jexordexan** [comment]
I'll try to leave a PR tonight! for now I've wrapped it in a nuxt `no-ssr` component

**Comment by rayrutjes** [comment]
Hey @Jexordexan , this is now release in v1.3.3

Let me know if it works out properly now.

Thanks for your work!

**Comment by Haroenv** [comment]
Hmm @ishitatsuyuki, are you using the latest version? The PR has been merged to fix this almost a year ago. Can you give a GitHub project where you receive this error?
