### ISSUE TITLE
Initial facet filtering for "deep links"

### ISSUE THREAD

**Issue by kfirba** [algolia/vue-instantsearch#372]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**Bug: What is the current behavior?**
When we try to access a "deep link" page, for example, `example.com/search?q=term`, we can use the `query` parameter on the `<ais-index>` component to set a "default" value for the search.

When we try to do the same with facets by accessing a custom "deep link" such as `example.com/search?facet=tags&value=PHP`, one may think that we apply the initial filtering using the `:query-parameters` parameter on the `<ais-index>` component:

```
<ais-index
    app-id="..."
    api-key="..."
    index-name="..."
    :query-parameters="{
        facetFilters: ['tags:PHP']
    }"
>
</ais-index>
```

While it's true that the returned results will be filtered down to the PHP tag (where "tag" is a facet), other components such as the `<ais-refinement-list>` won't pick on that and will not "check" the facet option:

![image](https://user-images.githubusercontent.com/8510486/34080039-dc13b1a6-e340-11e7-9244-ce8dfa2a38d6.png)

Note that the refinement list on the right side didn't pick on the fact that we filter on the "Laravel" tag facet.

The **huge** issue I see with that is that the user does not get a feedback as to what he is currently viewing and if he now tries to type something into the search box, Algolia will scope what he typed to the current facet that is being drill-downed to. Just imagine how confused the user is at this point:

1. The user can't see any visual indication for a facet filtering.
2. Since there is no indication, the user thinks that he's viewing every record and starts typing in the search box.
3. Algolia scopes the query the user types to the facet that was initially selected.
4. The user does not get expected results as the result he's looking for may be under a different tag facet (SSL, for example).

The current "solution" to that behavior is:

1. The user has to remember which facet he attempted to filter.
2. Double-click that facet in the refinement list TWICE - 1 time to check it as marked (the results do not change, wasting a query here) and another time to uncheck it which "resets" the filters.

**Bug: What is the expected behavior?**
When there is an initial facet filtering, we need to let the `<ais-refinement-list>` component know about it and make it "check" the correct item in the list. By doing so, the next click on that "checked" item will uncheck it and "reset" the filters.

**Bug: What browsers are impacted? Which versions?**
Every browser. A logical bug.

**Bug: What is the proposed solution?**
I'm not well-versed with how the components "talk" to each other, I assume there is a general store object which they all share:

We a set a flag if the user uses the `facetFilters` option which the `<ais-refinement-list>`component can check for its existence. If it exists, the refinement list will look for that filter in its data and manually mark it (**without initiating a request to Algolia** as the data was pre-fetched by the main component).

**Comment by kfirba** [comment]
Is there anything new with this issue?

**Comment by Haroenv** [comment]
Nothing new yet, we haven’t decided how to solve this

**Comment by Haroenv** [comment]
This is now solved with routing in v2: https://v2--vue-instantsearch.netlify.com/advanced/vue-router-url-sync.html
