### ISSUE TITLE
Search Store Facet Refinement - "OR"

### ISSUE THREAD

**Issue by shaunnez** [algolia/vue-instantsearch#374]
First things - great library. 

What I would like to know is how to use "add facet refinement" to do an "OR" query instead of an "AND" query.

i.e. store.addFacetRefinement("skills", "dev"); store.addFacetRefinement("skills", "designer")

The above causes it to be an "and" query (where each person must be a dev AND a designer).

According to the algolia documentation, we need to parse in an "array".

I.e. the above in the actual ajax request sends: facetFilters:["skills:dev","skills:designer", "someotherthing:true"]

The documentation has an example like this (book OR ebook AND author JK Rowling)
facetFilters: [["category:Book", "category:Ebook"], "author:JK Rowling"]

https://www.algolia.com/doc/guides/searching/filtering/?language=javascript#facet-filters

Thanks

**Comment by Haroenv** [comment]
```js
import { FACET_OR } from "vue-instantsearch";

//... create store

store.addFacet("the-attribute", FACET_OR);
store.addFacetRefinement("the-attribute", "the-value");
```

That way that facet is set up for faceting with “or”, rather than the default of “and”

**Comment by Haroenv** [comment]
Thanks for using Vue InstantSearch and don’t hesitate to reach out for any other questions

**Comment by rayrutjes** [comment]
Definitely something we need to add to our docs.
This has become a frequent question.

Moreover, a lot of users are trying to leverage the `queryParameters` for this and it doesn't work.
Maybe we should see what's happening there and make it work if it makes sense, or raise an error for users to act accordingly.
