### ISSUE TITLE
Index component with auto search disabled and empty query

### ISSUE THREAD

**Issue by 3alampro** [algolia/vue-instantsearch#375]
Hello,

I'm using vue-instantsearch in my Laravel App Project and love how easy and super fast to implement the search functionality on my project specially with multiple Indexes

the only issue I'm facing right now is disabling auto search when the page load for the first time I achieve that by configuring the auto-search props to false on the index component and it's work fine but how can I disable searching when the search input is empty I can hide the result components but I want better solution and not to trigger the search request at all if the input is empty 

Proposed Solution 
make index component check if query is empty or auto search is disabled do not fire search request 
or
make it easy to toggle it like auto-search

Because now what is the point if I disabled auto search but if user start typing and deleted the text in the input field all result will be shown again

**Comment by Haroenv** [comment]
Sorry for having missed this issue somehow apparently, this pattern is now documented at https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-requests/vue/
