### ISSUE TITLE
Get first few search results

### ISSUE THREAD

**Issue by mtilokani** [algolia/vue-instantsearch#379]
How to get first few search results?

Example: Is there facility to show say first 10 result items and then link as "Show all" ?

**Comment by Haroenv** [comment]
```vue
<ais-results inline-template>
  <table>
    <tbody>
      <tr v-for="result in results" :key="result.objectID">
        <td>{{ result.name }}</td>
        <td>{{ result.description }}</td>
      </tr>
    </tbody>
  </table>
</ais-results>
```

In there you can limit it and add a button to toggle between full view and just a few, does that help you?

**Comment by mtilokani** [comment]
@Haroenv , yes I had seen this inline template example previously, but thought might be there will be some facility from plugin/package end to do this like say 

`<ais-results :limit="10">
...
 </ais-results>`

**Comment by Haroenv** [comment]
not natively @mtilokani, but we'll keep this suggestion in mind  if more people ask for it. 

I'll close this issue for now, since there's a workaround, thanks for your issue!

**Comment by mtilokani** [comment]
@Haroenv , Ok, thanks for your time.

**Comment by Haroenv** [comment]
Have a great day @mtilokani 👍
