### ISSUE TITLE
Null attributes causes the highlight component to throw errors

### ISSUE THREAD

**Issue by aarondfrancis** [algolia/vue-instantsearch#385]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**Bug: What is the current behavior?**
I have homeowner records in Algolia, and sometimes the `owner_name` can be `NULL`, when that's the case, the `ais-highlight` will throw this error over and over:

`Error in render: "Error: The "owner_name" attribute is currently not configured to be highlighted in Algolia. See https://www.algolia.com/doc/api-reference/api-parameters/attributesToHighlight/."`

**Bug: What is the expected behavior?**
No text is displayed for that attribute, no error is thrown. The attribute *is* set up for searching, one or two records just have null values!

**Bug: What browsers are impacted? Which versions?**
All

**Bug: What is the proposed solution?**
Not sure... Change this check to something more strict though: https://github.com/algolia/vue-instantsearch/blob/master/src/components/Highlight.js#L22

**Comment by aarondfrancis** [comment]
I think at a very minimum, the error message should be clarified, because it sent me down the wrong path for an hour or two trying to figure out why it wasn't "configured for highlighting".

**Comment by Haroenv** [comment]
Seems like in your case, just changing that error to “might” and into a warning should be enough I think

**Comment by Haroenv** [comment]
Feel free to make a PR to any text you’d prefer!

**Comment by aarondfrancis** [comment]
I think that better solution is for the `ais-highlight` component to happily display `null` values.

**Comment by ligne13** [comment]
Hi,
I have this error in my console :
> vue-instantsearch.esm.js:857 The "tags" attribute might currently not be configured to be highlighted in Algolia. See https://www.algolia.com/doc/api-reference/api-parameters/attributesToHighlight/.

Though I've added the tags attribute in my index config :
```
<ais-index
                        :app-id="algoliaAppId"
                        :api-key="algoliaAppSecret"
                        index-name="posts_index"
                        :query-parameters="{
                        query: query,
                        attributesToHighlight: ['title', 'content', 'tags'],
                        attributesToRetrieve: ['title', 'content', 'slug', 'tags'],
                        restrictSearchableAttributes: ['title', 'content', 'tags'],
                        attributesToSnippet: ['content:30'],
                    }"
                        :auto-search="false">
```
My tags attribute is an array of strings, for example :
```
["tag1", "tag2"]
```
It works fine from the Algolia Dashboard with this custom query param `{ "attributesToHighlight": ["title", "content", "tags"] }` but not from my VueInstantSearch implementation.

Any idea why ?

**Comment by ligne13** [comment]
I also have the same issue for null attributes to be highlighted.
