### ISSUE TITLE
How to use paginationLimitedTo ?

### ISSUE THREAD

**Issue by Evild67** [algolia/vue-instantsearch#387]
I want to display more than 1000 results. I used infinit scroll with :stack option but when i trying to get more than 1000 results stacked, i get an error 

> you can only fetch the 1000 hits for this query. You can extend the number of hits returned via the paginationLimitedTo index parameter or use the browse method. You can read our FAQ for more details about browsing: https://www.algolia.com/doc/faq/index-configuration/how-can-i-retrieve-all-the-records-in-my-index

I did not find how to use paginationLimitedTo :/

**Comment by Haroenv** [comment]
You can put it in the `:query-parameters` of the InstantSearch component: https://community.algolia.com/vue-instantsearch/components/index.html#usage

**Comment by Evild67** [comment]
paginationLimitedTo can't be added to :query-parameters
https://www.algolia.com/doc/api-reference/api-parameters/paginationLimitedTo/?language=javascript.

![image](https://user-images.githubusercontent.com/2675980/35731676-e48026e4-0816-11e8-89dc-52ca8d5f7ce2.png)

**Comment by Evild67** [comment]
I tried this, but not working :/ I didn't find vue-instantsearch docs how to set this. I got an error, `setSettings is not a function`. But this is normal here, i can't find setSettings in this file https://github.com/algolia/vue-instantsearch/blob/master/src/store.js. Is this option elsewhere implemented ? 
```javascript
import {
  createFromAlgoliaCredentials,
  createFromSerialized,
} from "vue-instantsearch";
const searchStore = createFromAlgoliaCredentials(
  "----",
  "----"
);

export default {
  async asyncData({ context, route }) {
    searchStore.indexName = "emoji";
    searchStore.query = route.params.query ? route.params.query : "";
    searchStore.setSettings({
      paginationLimitedTo: 2000
    });
    searchStore.start();

    await searchStore.waitUntilInSync();

    return { serializedSearchStore: searchStore.serialize() };
  }
[...]
}

```

**Comment by Evild67** [comment]
Thanks ! I just created a quick script to update my settings because i did not find where to update this on the dashboard. Is it available ?

**Comment by Haroenv** [comment]
perfect!

**Comment by Haroenv** [comment]
That looks like an oversight in the typescript definitions instead. Could you send an email to support@algolia.com with exact replicatable code please so we can find what is going on in your case ?

**Comment by suryavanshi08** [comment]
> index.setSettings is supposed to be done backend or on the dashboard, not in your frontend application; sorry for not being clear on that.

Hi, @Haroenv I am facing the same issue as if I try to use index.setSettings function it showing me its not error as index.setSetting is not a function can you please me how I can use this function.

**Comment by Haroenv** [comment]
You need to use the function in a node script, or you can set the setting with the dashboard @suryavanshi08

**Comment by suryavanshi08** [comment]
Thank you @Haroenv  now it's working fine, I appreciate your reply. Thanks!
