### ISSUE TITLE
Combine multiple Tree menus on the same page

### ISSUE THREAD

**Issue by rikiless** [algolia/vue-instantsearch#389]
Is it possible to use two Tree menus on the same page? For examples tree menu filtering for Categories and Regions?

If I use component `<ais-tree-menu>` twice in my PHP template the attributes from the first one overrides the second one. The result is I will get two components with Categories options only.

```html
<div class="card mb-4">
    <div class="card-header">
        Categories
    </div>
    <div class="card-body">
        <ais-tree-menu :attributes="['categories.levels.lvl0', 'categories.levels.lvl1', 'categories.levels.lvl2', 'categories.levels.lvl3', 'categories.levels.lvl4']"></ais-tree-menu>
    </div>
</div>

<div class="card mb-4">
    <div class="card-header">
        Regions
    </div>
    <div class="card-body">
        <ais-tree-menu :attributes="['regions.levels.lvl0', 'regions.levels.lvl1', 'regions.levels.lvl2', 'regions.levels.lvl3', 'regions.levels.lvl4']"></ais-tree-menu>
    </div>
</div>
```

**Comment by Haroenv** [comment]
Can you make this into a sandbox like [this](https://codesandbox.io/s/github/algolia/vue-instantsearch-examples/tree/master/examples/e-commerce)? I wonder where this issue is exactly occurring from

**Comment by rikiless** [comment]
Sorry for spamming. I did not read the [docs](https://community.algolia.com/vue-instantsearch/components/tree-menu.html#props)...

**The props attribute needs to be added.**

> The attribute name to refine on. This only needs to be changed if multiple tree-menu components are bound to the same search store...

**Comment by Haroenv** [comment]
Perfect!
