### ISSUE TITLE
[Question] Rangking & Faceting with SearchStore

### ISSUE THREAD

**Issue by muhibbudins** [algolia/vue-instantsearch#392]
Hi there,

Thank you very much for awesome work. I have many question when using vue instantsearch (especially on nuxtjs). In this case i can't use "search input" (see image below) so i create SearchStore for manual search.

<img width="390" alt="screen shot 2018-02-13 at 17 13 06" src="https://user-images.githubusercontent.com/17744043/36144657-4e7ae3f4-10e1-11e8-97c0-dcc1292040f9.png">

---

And then i try to use below code to search, but the results of search is not correctly (still show wrong ranking / facets).

```js
    searchStore.page = 2
    searchStore.ranking = ['desc(view_counte)']
    searchStore.facets = ['category:custom_ring']
    searchStore.resultsPerPage = 5
    searchStore.queryParameters = {
      distinct: true
    }
    searchStore.start()
    searchStore.refresh()
    await searchStore.waitUntilInSync()

    const stores = createFromSerialized(searchStore.serialize())
```

*I already add category to faceting on Algolia dashboard

Thank you

**Comment by Haroenv** [comment]
Hey @muhibbudins, can you give the other parts you tried as well, so I can try something out which I can run and debug? Especially would like to see what the exact parameters that are sent are, but I'll need to have a complete experience for that. You should be able to use [glitch](https://glitch.com) or just a GitHub repository for the server normally.

**Comment by muhibbudins** [comment]
Hi @Haroenv ,

Thank you very much for answer my question, for problem multiple faceting. I already found the answer like this.

```js
import {
  createFromAlgoliaCredentials,
  createFromSerialized,
  FACET_OR
} from 'vue-instantsearch'

const searchStore = createFromAlgoliaCredentials('xxx', 'xxx')
searchStore.indexName = 'xxx'

...
    searchStore.page = 2
    searchStore.addFacet('category')
    searchStore.addFacet('sub_category', FACET_OR)
    searchStore.addFacetRefinement('category', 'diamond_pendant')
    searchStore.addFacetRefinement('sub_category', 'threestone')
    searchStore.addFacetRefinement('sub_category', 'two_tone')

    searchStore.resultsPerPage = 30
    searchStore.start()
    searchStore.refresh()
    await searchStore.waitUntilInSync()

    const stores = createFromSerialized(searchStore.serialize())
```

But for sort ranking like sort by price or view count, i can't solve now. Maybe i'll find a solution at the source code or discourse.

---

Thank you
