### ISSUE TITLE
Feature: pass in the page when emitting the page change event

### ISSUE THREAD

**Issue by VinceG** [algolia/vue-instantsearch#393]
**Feature: What is your use case for such a feature?**

Right now when the page change event is emitted it's empty. it'll be nice to get the page it was changed to passed in.

This might not be an actual feature or a bug but rather a minor change. I can submit a PR if needed. ~~I was also wondering if there is a way to access the current page in any other way?~~

Edit: I guess the page can be accessed with the following code:

`this.$refs.search._localSearchStore.page`

However the page being passed as part of the event is helpful.

Thank You.

**Comment by Haroenv** [comment]
That makes sense. Do you want to make a PR for this? Relevant code can be added here:

https://github.com/algolia/vue-instantsearch/blob/40c9406c5f0d477324a2e9061c75241f6debad6e/src/components/Pagination.vue#L100

**Comment by VinceG** [comment]
@Haroenv thanks, will do.
