### ISSUE TITLE
Running Uglify causes errors on page and the components fail to load 

### ISSUE THREAD

**Issue by VinceG** [algolia/vue-instantsearch#395]
I have this issue when trying to use the instant search, it seems that if we try to build our app for production (tree shaking, uglify, etc..) the app breaks due to vue instant search. If i remove the vue instant search import everything works fine.

I am not sure if it's due to the fact vue instant search is already compiled and we try to uglify it again? I wanted to see if you guys had any issues similar to this one before.

I know this is Vue instant search code because when i search for those colors it comes back to node_modules/vue-instantsearch/dist/vue-instantsearch.js

**Bug: What is the current behavior?**

![screen shot 2018-02-16 at 9 58 05 am](https://user-images.githubusercontent.com/195199/36321941-6e6a0386-1300-11e8-867c-def1dc0f5728.png)

![screen shot 2018-02-16 at 9 58 23 am](https://user-images.githubusercontent.com/195199/36321810-fb3dd518-12ff-11e8-9d4b-1928783cb999.png)

**Bug: What is the expected behavior?**

No errors.

**Bug: What browsers are impacted? Which versions?**

Chrome 64.0.3282.167

**Bug: What is the proposed solution?**

No idea.

**Comment by Haroenv** [comment]
Can you leave your setup here? Usually you wouldn’t process dependencies like that, but I’m not sure what can be going wrong. A repository we can try out would be ideal

**Comment by VinceG** [comment]
@Haroenv I am going to create a simple repository to reproduce the issue.

**Comment by VinceG** [comment]
Closing since when using a separate repository with fresh install this does not happen. I am sure this is due to our app being so large and having so many dependencies that something is causing that error.

**Comment by VinceG** [comment]
@Haroenv How would i go in troubleshooting this? it seems it's something to do with our build process but this is the only thing that has an issue.

```
vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1 Uncaught TypeError: t.i is not a function
    at o (vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
    at Object.<anonymous> (vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
    at Object.Fy0/ (vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
    at n (manifest.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
    at Object.<anonymous> (vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
    at Object.mZWS (vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
    at n (manifest.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
    at Object.c1n5 (vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
    at n (manifest.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
    at Object.l3sP (vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
o @ vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
(anonymous) @ vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
Fy0/ @ vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
n @ manifest.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
(anonymous) @ vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
mZWS @ vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
n @ manifest.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
c1n5 @ vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
n @ manifest.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
l3sP @ vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
n @ manifest.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
MdZJ @ vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
n @ manifest.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
1 @ vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
n @ manifest.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
window.webpackJsonp @ manifest.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
(anonymous) @ vendor.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
app.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1 Uncaught TypeError: Object(...) is not a function
    at Object.hnH7 (app.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
    at n (manifest.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
    at Object.<anonymous> (app.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
    at Object.Swm5 (app.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
    at n (manifest.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
    at Object.0 (app.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
    at n (manifest.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
    at window.webpackJsonp (manifest.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1)
    at app.bbeda5ba8c29876758702d0c98b1215b486e4cd2.js?_1519849194:1
```

![screen shot 2018-02-28 at 12 21 47 pm](https://user-images.githubusercontent.com/195199/36811254-fccc7e8a-1c81-11e8-9b50-66d142c66232.png)
![screen shot 2018-02-28 at 12 21 35 pm](https://user-images.githubusercontent.com/195199/36811255-fce4e83a-1c81-11e8-870f-b0dfbac29dea.png)



[Archive.zip](https://github.com/algolia/vue-instantsearch/files/1768715/Archive.zip)

**Comment by jaredloman** [comment]
@VinceG what version Laravel Mix are you running? I was able to resolve this by upgrading Mix to the latest version. 

What I did to troubleshoot this was start a basic Vue project based upon the docs here and then just replicated the build environment of the app that was having trouble. Using Mix 0.8.9 broke this component but upon upgrade it fixed the issue.

**Comment by Haroenv** [comment]
Interesting, i thought this was fixed. Can someone make a repo which recreates this issue minimally?

**Comment by jaredloman** [comment]
@Haroenv , I believe this should do it.. https://github.com/jaredloman/instantsearch

npm run dev and everything is fine...npm run production and it breaks

**Comment by Haroenv** [comment]
Thanks, that will help!

**Comment by Haroenv** [comment]
I can replicate the error, and can trace it down to the `debug` package, but I'm not sure how not to throw an error after uglifying it 😞

**Comment by Haroenv** [comment]
This is no longer relevant with the latest versions of the library, since debug is no longer used 🙌
