### ISSUE TITLE
Feature: add debounce as optional parameter for the query watch

### ISSUE THREAD

**Issue by VinceG** [algolia/vue-instantsearch#396]
**Feature: What is your use case for such a feature?**

Right now the instant search does what it suppose to do and that's search on every key stroke. However in some cases it'll be helpful to add a timeout for the search. right now if i type a name while i type it goes to the server to return the results, this is by design but it'll be helpful if we can specify a timeout in ms as in a lot of cases people type fast and all those queries and data shifting just ruins the search experience.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

On this line
https://github.com/algolia/vue-instantsearch/blob/master/src/components/Index.vue#L119

add a timeout, default will be 0 so it'll work the exact same way and we can optionally specify the timeout if needed.

If this is something you guys will be open to i can submit a PR.

Thank You.

**Comment by Haroenv** [comment]
As discussed in person, debouncing is something that can be done by copying the bits of ais-searchbox and ais-input and debouncing in the event manually and debouncing before changing the `searchStore.query`. For that reason there's no urgent need for a native debounce method in Vue InstantSearhc for now.

**Comment by Draer** [comment]
Worst answer ever :P
