### ISSUE TITLE
Bug: empty search input performs search

### ISSUE THREAD

**Issue by VinceG** [algolia/vue-instantsearch#397]
**Bug: What is the current behavior?**

empty search string performs a search operation.

**Bug: What is the expected behavior?**

if the search term is empty do not perform a search string

**Bug: What browsers are impacted? Which versions?**

All browsers.

**Bug: What is the proposed solution?**

if the string is empty do not run a search

We have thousands of searches for an empty string.

**Comment by Haroenv** [comment]
This is in fact on purpose to warm up the connection to have a faster second request. You also don’t get charged for search operations, so this shouldn’t really be an issue for you in that regard. 

Is this a blocking issue for you?

**Comment by Haroenv** [comment]
By the way, I’m in LA for the weekend, if you want to talk about it or give your experiences otherwise :)

**Comment by VinceG** [comment]
@Haroenv it's not blocking, i was just curious as to why it'll run an empty search. I don't mind as long as we don't get charged for it.

![screen shot 2018-02-23 at 3 40 10 pm](https://user-images.githubusercontent.com/195199/36622042-036356ea-18b0-11e8-8d6d-c602d57a75bf.png)

You should've came to our office, i'd love to give you a tour and show how we use algolia and the what the road map is.

**Comment by Haroenv** [comment]
Send me an email, I’m still here until Wednesday, haroen@algolia.com

**Comment by VinceG** [comment]
@Haroenv sent.

**Comment by Haroenv** [comment]
now with v2, the solution is described here: https://v2--vue-instantsearch.netlify.com/advanced/conditional-requests.html
