### ISSUE TITLE
Add CurrentRefinedValues component in Vue-instantsearch

### ISSUE THREAD

**Issue by Panart** [algolia/vue-instantsearch#404]
It would be great to have the CurrentRefinedValues component from React InstantSearch in Vuejs InstantSearch!

**Comment by Haroenv** [comment]
Will be added in v2, see https://github.com/algolia/vue-instantsearch/milestone/1

**Comment by Haroenv** [comment]
Right now a workaround you can use is:

1. make a custom widget
2. use `computed: { currentRefinedValues(): { returnthis.searchStore._helper.lastResult.getRefinements(); }}`
3. make some html you want

**Comment by Haroenv** [comment]
more info [here](https://community.algolia.com/algoliasearch-helper-js/reference.html#searchresults) and [here](https://community.algolia.com/vue-instantsearch/getting-started/custom-components.html)

**Comment by Panart** [comment]
Thank you @Haroenv , it is working. I was wondering if there is any way, for now, to implement a click on the selected tag? Is there another method to change selected refinements array?

**Comment by Haroenv** [comment]
Yes, you'll need to use `this.searchStore._helper.removeFacetRefinement` in the click handler. See also [the docs](https://community.algolia.com/algoliasearch-helper-js/reference.html#AlgoliaSearchHelper#removeFacetRefinement)

**Comment by Haroenv** [comment]
https://v2--vue-instantsearch.netlify.com/components/currentrefinements
