### ISSUE TITLE
Populating header slot in Range Input component causes inputs to disappear

### ISSUE THREAD

**Issue by Josh865** [algolia/vue-instantsearch#405]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**Bug: What is the current behavior?**
When populating the `header` slot in the `range input` component, the inputs, separator, and button do not appear.

**Bug: What is the expected behavior?**
The range inputs, separator, and button should appear.

**Bug: What browsers are impacted? Which versions?**
Latest versions of Chrome, Firefox, and Edge.

**What is the version you are using? Always use the latest one before opening a bug issue.**
1.5.1

See code beginning at line 53 in App.vue in this sandbox:
[![Edit example-e-commerce](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/54z38ykoxx)

**Comment by Haroenv** [comment]
Thanks for the sandbox! Great issue report. I’ve seen similar issues which were solved by having explicit naming, but will check out where the problem lies ASAP

**Comment by Haroenv** [comment]
I just released 1.5.2 which fixed this!

**Comment by Josh865** [comment]
Works perfectly! Thanks for the quick fix and the great package.

**Comment by Haroenv** [comment]
With pleasure, don't hesitate to reach out with any other issues you have!
