### ISSUE TITLE
Sync Refinement List with Vue Router

### ISSUE THREAD

**Issue by Alig96** [algolia/vue-instantsearch#411]
I got the search query & page to match with Nuxt using the tutorial, but now I would also like to sync the user's refinements to the URL. What would be the most efficient way to do this? What data from the searchStore should I append to the URL and re-apply?

Thanks for the awesome project!

**Comment by Haroenv** [comment]
For a refinementList, you should sync [`store._helper. getFacetValues `](https://community.algolia.com/algoliasearch-helper-js/reference.html#SearchResults#getFacetValues) add `store.addFacet` when setting the value. Feel free to make this into a repository we can play around with and find the correct way to do it. 

By the way, v2 will have a brand new way of doing url synchronisation which will be a lot simpler, looking forward to it!
