### ISSUE TITLE
Add range slider as a facet component

### ISSUE THREAD

**Issue by jryd** [algolia/vue-instantsearch#412]
**Do you want to request a *feature* or report a *bug*?**

Feature

**Feature: What is your use case for such a feature?**
This is a feature supported in the vanilla InstantSearch library; https://community.algolia.com/instantsearch.js/v2/widgets/rangeSlider.html. I'm in the process of converting this all to be based of vue-instantsearch given my app uses Vue on the frontend.
This is a nice feature that is missing in the current library and would either suit a standalone component or as an extension of the Range Input component.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
I see two options:

1. Add this as it's own component and call it like:

```
<ais-range-slider-input :min="" :max="" attribute-name="" ...></ais-range-slider-input>
```

2. Add it as an extension of the current `ais-range-input` component, something like

```
<ais-range-input attribute-name="" :slider="true"></ais-range-input>
```

**What is the version you are using? Always use the latest one before opening a bug issue.**
vue-instantsearch@1.5.2

**Comment by Haroenv** [comment]
As you noted, a  range component is quite hard to build yourself is not that easy. For that reason we also plan to port this component from InstantSearch.js in the coming release. thanks for your patience!

**Comment by SebSzcze** [comment]
Any update on this?

**Comment by Haroenv** [comment]
The next version will be ready for a beta in a few weeks

**Comment by Haroenv** [comment]
Code how to use this in v2 (alpha):

https://github.com/algolia/vue-instantsearch/blob/95a5cdba17b05d77206d66ca0f420dd6e97395c8/stories/RangeInput.stories.js#L74-L132


[demo](https://deploy-preview-416--vue-instantsearch.netlify.com/stories/?selectedKind=ais-range-input&selectedStory=with%20vuetify%20slider&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs) and [other demo](https://deploy-preview-416--vue-instantsearch.netlify.com/stories/?selectedKind=ais-range-input&selectedStory=with%20vue-slider-component&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs)
