### ISSUE TITLE
Add collapsible option to facet components

### ISSUE THREAD

**Issue by jryd** [algolia/vue-instantsearch#413]
**Do you want to request a *feature* or report a *bug*?**

Feature

**Feature: What is your use case for such a feature?**

This would help bring parity to the options we have available in the vanilla JS version of InstantSearch.js.
The use case of this is to have primary filters expanded for prominence, but secondary filters minimized that can later be expanded.
It can also help when you have a number of filters on the page, to avoid the page requiring scrolling by default.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

I would see this being a prop that we pass to the component `:collapsible="true"` and then perhaps a default state `:collapsed="false"`.

**What is the version you are using? Always use the latest one before opening a bug issue.**

The latest, vue-instantsearch@1.5.2.

**Comment by Haroenv** [comment]
Thanks for raising this issue, as with other feature parity issues, this is also planned in v2

**Comment by jryd** [comment]
Thanks for your response on this and the other issues I raised @Haroenv. I see the V2 milestone has a due date of 5 April 2018. Is this still looking to be the case, can we expect a release roughly around then? I ask in the interest of not wasting my own time - if a release can be expected shortly then I won't bother on working on a workaround, but if this is looking further away than anticipated then I will need to look at doing something for now.

**Comment by Haroenv** [comment]
The release will likely be delayed a bit because there were some unforeseen complications on the implementation side. 

For collapsible specifically, you should be able to copy the component, add a v-if where you prefer it and use that instead of our component, if that makes sense :)

**Comment by jryd** [comment]
@Haroenv I was thinking of something very similar.

**Comment by Haroenv** [comment]
Feel free to leave your workaround here, or how far you got if you're stuck in a codesandbox (template [here](https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/Vue%20InstantSearch))

**Comment by Haroenv** [comment]
Here's an example implementation of `ais-panel` enhanced with toggling abilities: https://codesandbox.io/s/8xl54vl5r2

**Comment by louislebrault** [comment]
If you hide a refinement-list that way (with a v-if), it will be removed from instant search state, which is not the same behavior as using the collapsed props from the original panel widget.

**Comment by Haroenv** [comment]
you can use v-hide @louislebrault
