### ISSUE TITLE
numericRefinementList for filtering on date and time for event records

### ISSUE THREAD

**Issue by mycaule** [algolia/vue-instantsearch#414]
Please implement `numericRefinementList` in the vue version of the library.

The goal would be to make a date filter as mentioned in https://discourse.algolia.com/t/filter-by-date-instantsearch/2858

**Comment by Haroenv** [comment]
Thanks for bringing this to our attention. We will actually rework the way numeric ranges etc. are working specifically for dates all around InstantSearch in the coming time. Could you for that reason explain which behaviour you exactly want to achieve? i.e. what kind of data you have, how you want to refine etc.

Thanks!

**Comment by mycaule** [comment]
I have a list of events which I would like to filter be date preferably using a calendar UI component.
I stored the date in the index using a numeric timestamp (UNIX time in seconds), and would like to use it as a facet.

It looks like usecase has been studied already using the regular vanilla InstantSearch.js library.

The demo is available on https://mycaule.github.io/tango-search/.

**Comment by Haroenv** [comment]
So to be clear, every record in your index has a single timestamp, and you want to have a refinement like this?

```
             from             to         
             [                ]          
  x     x    o  o o      o  o   x x x   x
    x     x   o     o o       o x   x  x 
```

with `x` being record not matched, and `o` being record matches?

**Comment by mycaule** [comment]
Yes indeed

Something like https://github.com/airbnb/react-dates would be awesome as mentioned by algolia team members here https://github.com/algolia/instantsearch.js/issues/1077

**Comment by Haroenv** [comment]
🤔 Would it also make sense to have both of those things in two timestamps instead: 

```json5
{
  "date": {
    "from": 1522281600, // 15h, 29/3
    "to": 1522281600 // 20h, 29/3
  }
}
```

For your use case, if you use the date/time picker, the events need to be completely within the range you give right? You wouldn't want to match things which partially overlap with the range?

**Comment by mycaule** [comment]
If I want to get every events happening on tuesday at 6pm, this would require more calculation.

That's why I just store the hours, not the full date + hours unix format. But I agree that it's easier to store the hours as numeric values instead of strings.

I still need a date and time picker which is still not provided by `vue-instantsearch`

**Comment by Haroenv** [comment]
I’m aware that Vue InstantSearch doesn’t have this feature yet, I’m just thinking what you exactly need

**Comment by mycaule** [comment]
Closing this thank you very much.

**Comment by Haroenv** [comment]
We will keep this issue in mind, when we make this a built-in future in the future. Thanks!
