### ISSUE TITLE
Unexpected token :

### ISSUE THREAD

**Issue by AndreyBashuk** [algolia/vue-instantsearch#428]
**Bug: What is the current behavior?**
I try to use vueinstantsearch with my project, but i see the next error in my console:
https://monosnap.com/file/JJCsOWpHmnD8Fo6faqXTiVA0Oz0Qn6
Before i play with vueinstantsearch in testing project, and everything works great. I try to use SearchStore:
https://monosnap.com/file/1fFakzCtDJ3yEc05HPWdpvRRMgguCa
Error comes as soon as i make
import InstantSearch from 'vue-instantsearch';
 any vue-instantseach plugin that i import leads to#  UNECPECTED TOKEN : error.
Help pls)

**Comment by Haroenv** [comment]
Seems pretty odd, can you make this into a standalone repository I can try things out in, I haven't seen this error before, but just seeing the error message in a screenshot won't be enough to debug this. 

Thanks for providing with more info!
