### ISSUE TITLE
Can't removeFacet from searchStore.

### ISSUE THREAD

**Issue by AndreyBashuk** [algolia/vue-instantsearch#440]
**Bug: What is the current behavior?**
I create new searchStore instance using faceFilters. But i need to change facet when my route parameters changed. And i can't change facets manually. I try many methods, but i still can't do this.
![image](https://user-images.githubusercontent.com/35767496/39397030-565dfb42-4b01-11e8-904f-dfd4dbb81456.png)
![image](https://user-images.githubusercontent.com/35767496/39397061-c31db2f4-4b01-11e8-8138-fb4633628657.png)
 
Method addFacet works. But removeFacet is not working.

**Bug: What is the expected behavior?**

**Comment by Haroenv** [comment]
RemoveFacet is supposed to be called with a single argument, the name of the facet. I’m currently not close to a computer to try it out, but can you try changing that?
