### ISSUE TITLE
vue-instantsearch not compatible with vue-cli 3? Could not find a declaration file for module 'vue-instantsearch'.

### ISSUE THREAD

**Issue by bwentzloff** [algolia/vue-instantsearch#442]
I was able to run `npm install --save vue-instantsearch` successfully, but when starting the server, I get the following error:
`ERROR in /data/src/main.ts
Could not find a declaration file for module 'vue-instantsearch'. '/data/node_modules/vue-instantsearch/dist/vue-instantsearch.common.js' implicitly has an 'any' type.
Try 'npm install @types/vue-instantsearch' if it exists or add a new declaration (.d.ts) file containing 'declare module 'vue-instantsearch';'`

As suggested, when I try `npm install @types/vue-instantsearch`, I get:
`npm install @types/vue-instantsearch
npm ERR! code E404
npm ERR! 404 Not Found: @types/vue-instantsearch@latest`

I am using the new vue-cli 3, could this be a compatibility issue with this component?

**Comment by Haroenv** [comment]
Hey! Seems like you’re adding typescript too. Can you make a repository which throws these errors?

**Comment by Haroenv** [comment]
There's no typescript definition of Vue InstantSearch, you'll have to write your own (possible to write a simple stub which simply declares the module). 

I'll gladly take a look on how to do it if I have a complete git repo to clone and try things around. 

Thanks!

**Comment by nolawill** [comment]
I threw up a quick repo with our exact vue app setup and the sample best buy code from your vue docs. (keep in mind that we are using [vue-cli-3](https://github.com/vuejs/vue-cli) when we set this up, just in case that has any impact)

[https://github.com/nolawill/vue-ais-typescript](https://github.com/nolawill/vue-ais-typescript)

Run the `npm install` and `npm run serve` and you should see the same declaration error. Thanks for taking a look for us!

**Comment by Haroenv** [comment]
Made it work, feel free to get back if that didn't do it https://github.com/nolawill/vue-ais-typescript/pull/1

**Comment by Haroenv** [comment]
<img width="1440" alt="screen shot 2018-05-03 at 17 42 08" src="https://user-images.githubusercontent.com/6270048/39587264-5cffb9da-4ef9-11e8-8680-e395542e874e.png">

🙌

**Comment by nolawill** [comment]
Confirmed. 👏🏼👏🏼👏🏼 No more declaration error. Thanks for the fix!

**Comment by sbrunswig** [comment]
is there a fix for this for those of use not using typescript? I am using vanilla js and vue-instantsearch does not work with vue-cli 3;

**Comment by Haroenv** [comment]
All examples use Vue CLI 3. Can you please post a failing reproducible example @sbrunswig?

**Comment by sbrunswig** [comment]
would you happen to have a link to an example of a vue cli 3.  The one on algolia's website is still using 2.0:
https://community.algolia.com/vue-instantsearch/getting-started/getting-started.html. I am trying vue create, where as this example is using vue init.  In the meantime I will put some code up, thanks for the quick reply.

**Comment by Haroenv** [comment]
https://www.algolia.com/doc/guides/building-search-ui/getting-started/vue/

**Comment by sbrunswig** [comment]
Here is the code: https://github.com/sbrunswig/vue-instantsearch,
Pretty simple to reproduce: 
1. vue create instant-search
2. npm i --save vue-instantsearch
3. replace main.js and app.vue with code in this example https://community.algolia.com/vue-instantsearch/getting-started/getting-started.html
4. npm run serve
5. open localhost:8080 and get console error `unknown custom element <ais-index>`

ive tried importing directly into app.vue also but still can find the modules

**Comment by sbrunswig** [comment]
thanks, will give that link a shot

**Comment by Haroenv** [comment]
As said earlier, you are looking at the docs for v1, not the docs for v2 of Vue InstantSearch, the link I gave is the correct of the one you're using

**Comment by sbrunswig** [comment]
yep had streams crossed thanks

**Comment by michaelpumo** [comment]
I created an `algolia.d.ts` file and put this inside:

```
declare module 'vue-instantsearch' {
  import * as InstantSearch from 'vue-instantsearch'
}
```

Worked for me, so hopefully it helps someone out.
