### ISSUE TITLE
show all refined parentlevel data for custom tree view

### ISSUE THREAD

**Issue by jaystacey** [algolia/vue-instantsearch#445]
**Do you want to request a *feature* or report a *bug*?**

Bug / feature

**Bug: What is the current behavior?**

Tree Menu component when filtering more than 2 levels deletes the previous levels data, except root levels data.

**Bug: What is the expected behavior?**

keeps the facets data when refined on sub levels

**Bug: What browsers are impacted? Which versions?**

all

**Bug: What is the proposed solution?**

instantsearch.js seems to provide desired result when 'showParentLevel = true', vue-instantsearch.js seems to only maintain root and current level data.

**Feature: What is your use case for such a feature?**

desired solution is select boxes plural (3+) where a user can re-refine earlier hierarchical levels, as opposed to re-refining from root.

could even be desired for tree view components.

**Comment by jaystacey** [comment]
Duplicate, my bad

**Comment by Haroenv** [comment]
Note that I have a “quite hacky/workaroundy” solution for that component within v1, send me a mail at Haroen@algolia.com if you want it :)
