### ISSUE TITLE
Make it possible for the sortBySelector to render something other than <select>

### ISSUE THREAD

**Issue by stephan-v** [algolia/vue-instantsearch#446]
**Do you want to request a *feature* or report a *bug*?**

Feature

**Feature: What is your use case for such a feature?**

Make it possible for the `sortBySelector` component to render something other than a select element.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

Possibly add a prop to change the parent elements type an example of this can be found here:

https://stackoverflow.com/questions/42228636/change-html-element-type-of-component

Using the native select option for a sort selection is something that is hardly being done anymore. Most of the time people use custom dropdown menu's and do not want to resort to a `<select`> tag.

The styling of the element needs to be overridden, the native usability for iOS and Android takes up half of your screen and most designs do not take into account the downsides and using a native button.

I would be very nice to have the ability to select what the wrapping parent uses as an element while not being  too much trouble to implement.

**Comment by Haroenv** [comment]
In v2 this would become almost trivial to provide your own rendering for a certain component. 

For now I suggest you take a look at the component here, copy it and change the html to suit you. 

Does that work?

**Comment by stephan-v** [comment]
I did not know about a 2.0 release. I can certainly create my own component here and use the injected store that you provide.

The reason I made the suggestion is because I hardly know anyone who still uses a select element for a sort option. Therefore I would not make sense to have this as a default. 

From a semantic point of view, I understand there is reason to keep it like it is. From a design and implementation point of view, I would change the default to be something other than a select element.

Thanks for your reply.

**Comment by Haroenv** [comment]
Sure, I understand your point of view for sure. For that reason our default implementation will always be semantic elements, which can be styled, but not completely. 

Let me know how it goes to edit the component to your needs, and feel free to reopen when you need more info
