### ISSUE TITLE
I am looking at building a custom component to improve the tree menu

### ISSUE THREAD

**Issue by benjam-es** [algolia/vue-instantsearch#447]
Currently, I have products within multiple categories. This seems to be preventing the tree menu from working.

**Comment by Haroenv** [comment]
Hey @benjam-es, could you send what exactly the problem is and the code you're using (preferably in a sandbox)? Thanks!

**Comment by benjam-es** [comment]
Hi,

I have managed to get the tree menu to show by adding attributed for faceting within the algolia dashboard. (using a modified version of the ecommerce example)

However my tree menu is showing a list of subcategories, and not top level categories.

I am unsure how I could demonstrate this with the live data, and how/where I do this in a sandbox.

I could look to add the code to an accessible test site/page for review?

**Comment by samouss** [comment]
We have template that are ready to use, you can find it [here](https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/Vue%20InstantSearch).

**Comment by benjam-es** [comment]
Here is a sandbox using the sample data.

[https://codesandbox.io/s/o7nnwpxz35](https://codesandbox.io/s/o7nnwpxz35)

Those categories are the subcategories. It doesnt first show the top level to select

i.e. VISUAL INSPECTION EQUIPMENT > ATEX Camera

**Comment by benjam-es** [comment]
Is it something I'm doing wrong?

**Comment by Haroenv** [comment]
I’m on mobile now, but I can’t see anything obviously wrong. Could you send an email to support@algolia.com when you give access to the index so we can inspect it?

**Comment by benjam-es** [comment]
In my example - the problem was:

I had 'categories' with the final category in, and 'sub categories' with a 'top level > final level' structure. To work, it needed 'categories' to list the top level category, rather than the sub category.

**Comment by benjam-es** [comment]
There is still a problem with the sandbox code above. The categories have been corrected as per the  help from the support email.

However:

Clicking the second category in the menu expands, but clicking the first does not.

**Comment by benjam-es** [comment]
One category had a trailing space (server side issue), so algolia was seeing was looking for 'space > space' and finding 'space space > space' which was breaking things

**Comment by Haroenv** [comment]
all right, so it was what I expected after all. I haven't seen this kind of issue before, but I wonder if maybe we could do something with calling `.trim` on the strings, @bobylito ?
