### ISSUE TITLE
How to use setSettings with searchStore?

### ISSUE THREAD

**Issue by OneX** [algolia/vue-instantsearch#453]
I want to change some settings on the index, mainly '[paginationLimitedto](https://www.algolia.com/doc/api-reference/api-parameters/paginationLimitedTo/)'.

How to set this?

```
import { createFromAlgoliaCredentials } from 'vue-instantsearch';
import config from '../../config';

const searchStore = createFromAlgoliaCredentials(
  config.algolia.appId,
  config.algolia.apiKey,
);
searchStore.setSettings({
  paginationLimitedTo: 2000
});
searchStore.indexName = 'stories';
```

This did not work for me.

**Comment by Haroenv** [comment]
Hey @OneX, settings should only be set with a node (or other backend) client, since it needs credentials that would allow users to set any other setting they want, and read your whole search as well. 

For that reason it's not supported with the search store. 

Feel free to follow up!

**Comment by OneX** [comment]
@Haroenv - but is there an option than to increase pagination limit via vue-instantsearch or i am stuck with 1000 per page.

**Comment by Haroenv** [comment]
You can set it either via the dashboard or via a node script, you only need to set that setting once per index (unless you change it) @OneX

**Comment by OneX** [comment]
@Haroenv - I can't find that option 'paginationLimitedTo' on Algolia Dashboard.

**Comment by Haroenv** [comment]
Ah you're right, I was wrong, you can't set it via the dashboard, since it's a setting we discourage from setting unless in very specific use cases. In node you can do it like this: 

```js
// index.js
const algoliasearch = require('algoliasearch');
const client = algoliasearch('app', 'api key');
const index = client.initIndex('the index');
index.setSettings({
  paginationLimitedTo: 1000
});
```

```sh
npm install algoliasearch
node index.js
```
