### ISSUE TITLE
Custom highlight prefix tag using ais-highlight directive

### ISSUE THREAD

**Issue by Arvind6353** [algolia/vue-instantsearch#458]
Hi ,

How to provide custom highlight prefix tag using ais-highlight directive?

Thanks,
Arvind

**Comment by Haroenv** [comment]
With ais-highlight you're able to use the highlight prefix and postfix tags set in the dashboard. Does that behave as you expected?

**Comment by Haroenv** [comment]
*does that __not__ behave as you expected?

Could you make a fiddle please showing what you have and what you want?

**Comment by Arvind6353** [comment]
@Haroenv : In the dashboard I changed the values to "<highlightsearch> and </highlightsearch>". But in the UI am getting only <em>

**Comment by Haroenv** [comment]
Can you try to show this in this fiddle, Vue InstantSearch seems to follow my settings here: 

https://codesandbox.io/s/jpxwx04749

(note that you can set `highlightPreTag` both in the dashboard and in search parameters)

**Comment by Arvind6353** [comment]
@Haroenv  Thanks. Its working . I made a mistake in the config.

**Comment by Arvind6353** [comment]
@Haroenv : I used the demo app from algolia . it had some nice styling . 
Do we have a styling that is similar to the demo application with vue-instant-search components ?
