### ISSUE TITLE
Search bar for refinement list when the count is more 

### ISSUE THREAD

**Issue by Arvind6353** [algolia/vue-instantsearch#460]
Hi ,

Is there a feature for adding search inside the refinement list in case the count of the list is more .

I find this feature in the browse section of the indices in the Algolia site

![image](https://user-images.githubusercontent.com/23059431/40887040-e60f8268-675f-11e8-8d2f-77aeca2af088.png)

**Comment by Haroenv** [comment]
Hey! This will be present in the next version and is tracked in https://github.com/algolia/vue-instantsearch/issues/224
