### ISSUE TITLE
Is aroundLatLngViaIP supported?

### ISSUE THREAD

**Issue by truthuntold** [algolia/vue-instantsearch#462]
I have attempted to put `aroundLatLngViaIP="true"` on my `ais-index`, and `ais-input` but the results are the with or without it. It could very well be attempting to search with my IP however I'm not sure how to tell if it is using my local IP.

I'm using Laravel 5.5 as a backend if anyone thinks that could be problem.

**Comment by Haroenv** [comment]
Hey @truthuntold, `aroundLatLngViaIP` is a search parameter which isn't explicitly added to `ais-index`, but rather the `query-parameters` prop of it:

```vue
<ais-index
  ...(other things)
  :query-parameters="{
    aroundLatLngViaIP: true,
  }"
/>
```

see: https://community.algolia.com/vue-instantsearch/components/index.html#usage
