### ISSUE TITLE
Pagination component false name for current page

### ISSUE THREAD

**Issue by gruenekampfente** [algolia/vue-instantsearch#464]
I've just figured out that there is a false value for the pagination default slot in the official documentation. The name of the current page for the scoped-slot is not "item" but "value".

Link: <https://community.algolia.com/vue-instantsearch/components/pagination.html>

**Comment by Haroenv** [comment]
ah that's right, sorry for the confusion. It really should have been `item` all along. I fixed the documentation in https://github.com/algolia/vue-instantsearch/pull/465
