### ISSUE TITLE
[Question] Mock instant search request in jest test

### ISSUE THREAD

**Issue by renanbronchart** [algolia/vue-instantsearch#466]
I have an error in jest test because I test with key app that don't exist.
I want to stop the request algolia. Is that possible ?

Thanks a lot.

**Comment by renanbronchart** [comment]
![capture d ecran 2018-06-20 a 15 27 49](https://user-images.githubusercontent.com/16922579/41661279-9a9836ee-749e-11e8-8b4c-dd639e1edb8d.png)

**Comment by Haroenv** [comment]
You should be able to mock the `algoliasearch().search()` function to what you expect. We don't have an existing mock, but there's one used in an OSS project here: https://github.com/CocoaPods/indexer.cocoapods.org/blob/master/__mocks__/algoliasearch.js

**Comment by Haroenv** [comment]
Please reopen if this is something which wasn't clear yet.
