### ISSUE TITLE
[Docs] Note for User to Try "0.0.0.0" if "localhost" does not render

### ISSUE THREAD

**Issue by agdavid** [algolia/vue-instantsearch#469]
Hi! I used the easy-to-follow [Getting Started](https://community.algolia.com/vue-instantsearch/getting-started/getting-started.html) guide.  

When I ran `npm run dev`,  the browser did not properly render the sample app on `localhost:8080`. However, a change to `0.0.0.0:8080` successfully rendered the app.

Consider adding a note to the Getting Started guide for the user to try `http://0.0.0.0:8080` if localhost results in an issue?

**Comment by Haroenv** [comment]
Maybe we can just put that or 127.0.0.1 in the guide. I’ve fallen for it too, still not sure what the cause is

**Comment by Haroenv** [comment]
In V2, we use a different version of Vue CLI which doesn't have this issue
