### ISSUE TITLE
Best way to modify Menu component?

### ISSUE THREAD

**Issue by cloudbluedigital** [algolia/vue-instantsearch#472]
Hi Guys,

I am trying to use algolia with Menu component to create a navigation. The problem I am having is that it renders as

```
<div class="ais-menu"> 
  <div class="nav-item">
     <a href="#" class="nav-link"> portfolio 
     <span class="ais-menu__count">27</span>
     </a>
   </div>
</div>
```

I don't need the div with class `ais-menu` and also the div with class `nav-item` I want it to be as `<li>` instead. What is the best approach for that? I tried using slots but I couldn't get it work

here is my current code
```
              <ais-menu :attribute="category" :class-names="{ 'ais-menu__item': 'nav-item', 'ais-menu__link': 'nav-link'}">
              </ais-menu>
```

Thanks for help

**Comment by Haroenv** [comment]
Hey @cloudbluedigital, for now the best option you have is the following: 

1. copy our real `Menu.vue` file from [here](https://github.com/algolia/vue-instantsearch/blob/master/src/components/Menu.vue)
2. change relative imports to directly from `vue-instantsearch`
3. make your edits to the DOM you need

The next version of Vue InstantSearch will have a more straightforward way of changing the DOM, as well as the default being better for accessibility already. 

I'll close this issue now, but feel free to open a new one or comment here if you need more guidance
