### ISSUE TITLE
Custom menu component what to use for imports

### ISSUE THREAD

**Issue by cloudbluedigital** [algolia/vue-instantsearch#474]
As suggested in #472 

I am trying to create my custom Menu component however what do I need to use for the imports? I tried to use vue-instasearch module but that didn't work.

```
  import algoliaComponent from 'vue-instantsearch';
  import { FACET_TREE } from 'vue-instantsearch';
```

**Comment by Haroenv** [comment]
Algoliacompnent is `{ Component }`, facet_tree is correct.

**Comment by cloudbluedigital** [comment]
I have tried changing it to `{ Component }` and that didn't work @Haroenv

**Comment by Haroenv** [comment]
```vue
<template>
</template>
<script>
import {Component, FACET_TREE} from 'vue-instantsearch';

export default {
  mixins: [Component],
  // the rest can be the same
}
</script>
```

Here is a version I edited like you requested in the previous issue: https://codesandbox.io/s/j288q11k7w
