### ISSUE TITLE
Bug: no search results on IE11

### ISSUE THREAD

**Issue by jvignolles** [algolia/vue-instantsearch#476]
**Bug: What is the current behavior?**

Search results are not displayed on IE11.

**Bug: What is the expected behavior?**

To see search results on IE11 (Internet Explorer 11).

**Bug: What browsers are impacted? Which versions?**

IE11.

**Bug: What is the proposed solution?**

No solution.

Here, one of the samples to reproduce the issue: https://s3-eu-west-1.amazonaws.com/vignolles/files/test_algolia/index.html

The console show a javascript error `Object doesn't support property or method 'assign'`.

**What is the version you are using? Always use the latest one before opening a bug issue.**

1.7.0

**Comment by Haroenv** [comment]
That’s right, I thought we mentioned it in the docs but apparently not; please use [polyfill.io](https://polyfill.io/v2/docs/) or other polyfills for ie11 compatibility.

**Comment by jvignolles** [comment]
Thank you! Polyfill.io fix my issue.

**Comment by Neophen** [comment]
What polyfills? where is that in documentation?

**Comment by Haroenv** [comment]
Good catch, seems like this is not showing on the Vue documentation, but it is on InstantSearch.js, https://www.algolia.com/doc/guides/building-search-ui/installation/js/?language=vue#browser-support

I'll reopen to remember to add this to the documentation in detail
