### ISSUE TITLE
attribute for distinct is unknown

### ISSUE THREAD

**Issue by zangab** [algolia/vue-instantsearch#477]
**Do you want to request a *feature* or report a *bug*?**
Bug, reproduction in sandbox: https://codesandbox.io/s/vmqnomr3l3
According to the documentation, it should work: https://community.algolia.com/vue-instantsearch/components/index.html

**Bug: What is the current behavior?**
Query-Parameter "attributeForDistinct" is unknown -> browser crash/freeze!

**Bug: What is the expected behavior?**
No duplicated results defined by attribute as in attributeForDistinct.

**Bug: What browsers are impacted? Which versions?**
Encountered in Chrome v67.0.3396.99 - others not tested.

**Feature: What is your use case for such a feature?**
I have multiple events in my database. Some of them take place more than once, e.g. twice a week within a given period of time. All events are indexed - so there are also duplicates. I created an autocompletion component so the user can search for events by a keyword. However, users also see the duplicated events (so the names are listed more than once) -> BAD.

**What is the version you are using? Always use the latest one before opening a bug issue.**
version 1.7

**Comment by samouss** [comment]
You cannot provide [`attributeForDistinct`](https://www.algolia.com/doc/api-reference/api-parameters/attributeForDistinct) at query time. This parameter is only available at indexing time. You can either configure it in your [Algolia Dashboard](https://www.algolia.com/dashboard) inside the "Display" section. Or you can use one of our client to manually to configure it programmatically using [`setSettings`](https://www.algolia.com/doc/api-reference/api-methods/set-settings/).

**Comment by zangab** [comment]
thx for your answer @samouss .
could u please update the docs? quite confusing this way.

Can I even set this setting somehow via vue-instantsearch?

**Comment by zangab** [comment]
and as I've seen here: https://www.algolia.com/doc/api-reference/api-parameters/distinct/#examples
Could I activate the `distinct` at query time and set the attribute at the algolia dashboard?

**Comment by Haroenv** [comment]
indeed, at query time you can toggle the display of distinct, or the number of items for distinct; but at settings time (e.g. via dashboard) you need to set which attribute is used for the distinct @zangab

**Comment by zangab** [comment]
nice. working like a charm. 😸 👌
