### ISSUE TITLE
Bug: watcher for query-parameters not checking nested changes

### ISSUE THREAD

**Issue by zangab** [algolia/vue-instantsearch#480]
**Do you want to request a *feature* or report a *bug*?**
BUG.

**Bug: What is the current behavior?**
When changing the query-parameters (at ais-index), algolia does not trigger a query / request. Therefore the result is not updated.
Reproduction: https://codesandbox.io/s/vmqjnzq7l5

**Bug: What is the expected behavior?**
A request is sent after changing the query-parameters.

**Bug: What is the proposed solution?**
`queryParameters() {
      this._localSearchStore.queryParameters = this.queryParameters;
    },`
Changing this line of code in the `components/Index.vue` (watcher) to watch nested changes alias `deep: true`.

**Feature: What is your use case for such a feature?**
Toggle tags.

**What is the version you are using? Always use the latest one before opening a bug issue.**
v1.7.0

My current quickfix:
`this.$set(this.$refs.algoliaIndex._localSearchStore, 'queryParameters', this.queryParameters);` but this sucks.

**Comment by Haroenv** [comment]
This is a bug in v1, but not major. Because of that we will not release a new version with this changed; unless a pull request is made. in V2 you can use configure for this: https://www.algolia.com/doc/api-reference/widgets/configure/vue/
