### ISSUE TITLE
Access query inside  <ais-results>

### ISSUE THREAD

**Issue by fusionsquare** [algolia/vue-instantsearch#501]
How can i access the query within the  <ais-results> Element? I'll want add a "show results" link within the suggest.

**Comment by Haroenv** [comment]
Hey @fusionsquare, you can do that by wrapping the results widget in another widget, which would have access to the search query:

```vue
<template>
  <div>
    <p>this is the query: "{{searchStore.query}}".</p>
    <p>you can use it for everything</p>
    <ais-results class="ais-Hits-list">
      <template slot-scope="{ result }">
        <div class="ais-Hits-item">
          <ais-highlight :result="result" attribute-name="name"></ais-highlight>
        </div>
      </template>
    </ais-results>
  </div>
</template>

<script>
import {Component} from 'vue-instantsearch'
export default {
  mixins: [Component]
}
</script>
```

https://codesandbox.io/s/jz0kvx76ky?module=%2Fsrc%2FMyResults.vue

Don't hesitate to get back if there's any more questions!

**Comment by fusionsquare** [comment]
It works, thanks!

**Comment by Haroenv** [comment]
perfect!
