### ISSUE TITLE
ais-range-input not working \ Error: price is not present in `facets` or `disjunctiveFacets`

### ISSUE THREAD

**Issue by besnikh** [algolia/vue-instantsearch#503]
Bug: ais-range-input

Behavior: 
Component `ais-range-input` is not working at all from my localhost. 

All other components are working fine but not range input

To test it i used price-range with this code: 
```
<ais-price-range
  attribute-name="price"
  from-placeholder="from"
  to-placeholder="to"
  currency="$"
  :class-names="{
    'ais-price-range': 'v-input mt-0 v-text-field v-input--hide-details theme--light',
    'ais-price-range__input': 'v-input__control',
    'ais-price-range__input--from': 'v-input__slot und mr-2',
    'ais-price-range__input--to': 'v-input__slot und',
    }">
    <template slot="default">
       <span></span>
    </template>
</ais-price-range>
```

Now this component above is working fine and if I use the the range component with attribute price it's not working 

```
<ais-range-input
  attribute-name="price"
/>
```
The main reason I want to use range component is year but since that was not working I tried with price and that is not working as well.. 

As per if i added price and year as facets: 
![fireshot capture 192 - algolia i dashboard_ - https___www algolia com_apps_yblqt](https://user-images.githubusercontent.com/25027019/45006340-b4827980-aff8-11e8-958a-f54a84a3c69e.png)

Error in console: 
```
Error: year is not present in `facets` or `disjunctiveFacets`
    at SearchResults.webpackJsonp../node_modules/algoliasearch-helper/src/SearchResults/index.js.SearchResults.getFacetStats (index.js:683)
    at Store.getFacetStats (vue-instantsearch.esm.js:486)
    at VueComponent.range (vue-instantsearch.esm.js:1830)
    at Watcher.get (vue.runtime.esm.js:3138)
    at Watcher.evaluate (vue.runtime.esm.js:3245)
    at Proxy.computedGetter (vue.runtime.esm.js:3503)
    at Proxy.render (vue-instantsearch.esm.js:1709)
    at VueComponent.Vue._render (vue.runtime.esm.js:4540)
    at VueComponent.updateComponent (vue.runtime.esm.js:2784)
    at Watcher.get (vue.runtime.esm.js:3138)
```

I believe this is bug or I am missing something ? 

Cheers

**Comment by Haroenv** [comment]
I've just tried it to be sure, and it works on my end: https://codesandbox.io/s/6yx1zrpm8w

Do you have your `price` attribute always as number, or is it maybe a string sometimes?

**Comment by besnikh** [comment]
@Haroenv always as a number.

I am testing with 3 documents only so I double checked that. 
As I noted above when I use the price range for attribute price, everything is working fine, but when using the price attribute with range its not working.

I have to not that I am using latest version of nuxt, it will bve ssr but at this time I am using <no-ssr> before ais tag. 

Also please note because I forgot to mention that I am using inline template, since I wanted to make a custom template to fit my needs but inline-template is above the line of filtering and searching so I don't think that' is releveant. 

my ais-index tag looks like this

`<ais-index :search-store="searchStore" :query="query" :auto-search='true'>`

```
<script>
import { createFromAlgoliaCredentials, createFromSerialized } from 'vue-instantsearch'
const searchStore = createFromAlgoliaCredentials('API', 'API')
searchStore.indexName = 'INDEX_NAME'

export default {
 async asyncData () {
    searchStore.start()
    searchStore.refresh()
    await searchStore.waitUntilInSync()
    return { serializedSearchStore: searchStore.serialize() }
  },
data () {
  return {
    searchStore: null,
    query: '', 
   }
  },
 created () {
    this.searchStore = createFromSerialized(this.serializedSearchStore)
  }
}
</script>

What should I do ... this completely stopped our dev for last 2-3 days :(

**Comment by Haroenv** [comment]
for range input to work you need to make it into this:

```vue
<script>
import { createFromAlgoliaCredentials, createFromSerialized, FACET_OR } from 'vue-instantsearch'
const searchStore = createFromAlgoliaCredentials('API', 'API')
searchStore.indexName = 'INDEX_NAME'
store.addFacet('price', FACET_OR)

export default {
 async asyncData () {
    searchStore.start()
    searchStore.refresh()
    await searchStore.waitUntilInSync()
    return { serializedSearchStore: searchStore.serialize() }
  },
data () {
  return {
    searchStore: null,
    query: '', 
   }
  },
 created () {
    this.searchStore = createFromSerialized(this.serializedSearchStore)
  }
}
</script>
```

**Comment by Haroenv** [comment]
please reopen if there's more issues :)
