### ISSUE TITLE
Translation within ais-results

### ISSUE THREAD

**Issue by fusionsquare** [algolia/vue-instantsearch#540]
Hi there,

we need to put some text inside the <ais-results> component. But i can't push a property inside, because the property is empty inside the <ais-results> tag. 

How can i put some text inside the component?

Thanks

**Comment by Haroenv** [comment]
Sorry, could you explain what you have / want with a codesandbox? I don't really understand what you mean :)

**Comment by Haroenv** [comment]
The reason you can't do this, is because `inline-template` overrides your template, the solution is to use a wrapper component.

(in v2 you can use the `default`, but in the current version you don't get access to all the results)

**Comment by Haroenv** [comment]
see https://codesandbox.io/s/8l98q8rml8 on how to use a custom component.

and https://vuejs.org/v2/guide/components-edge-cases.html#Inline-Templates on why inline template behaves like this.
