### ISSUE TITLE
v2 - advanced routing & vue router

### ISSUE THREAD

**Issue by Haroenv** [algolia/vue-instantsearch#544]
**Feedback on the v2 alpha version 🆕**

### Describe the bug / features

Currently there's three existing ways how to use the InstantSearch routing. 

The first option is putting `:routing="true"`. This will use the default serialising that doesn't lose any information, but might be a bit verbose

The second option is to put an object of config. This object can take `stateMapping`, with the functions `stateToRoute` and `routeToState` to serialise differently, but still use the default routing. This allows to rename things to make them easier to read, without touching how the serialising itself happens.

Finally, you can also change the URL to use full URLs, rather than just the query string. You need to change the `router` key inside the `routing` object. You can import the default (history) router from `import {history} from 'instantsearch.js/es/lib/routers'`, and modify, like in InstantSearch JS.

[![Edit vue-instantsearch-app](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q8pmz6n7lj?module=%2Fsrc%2FApp.vue)

All docs for InstantSearch routing configuration are [here](https://community.algolia.com/instantsearch.js/v2/guides/routing.html).

Finally an option is to use Vue Router. All previous examples will _work_ using Vue Router, as long as they don't conflict, as long as you don't try to do specific Vue Router things which are controlled by InstantSearch, since that might cause infinite loops, and InstantSearch provided query strings won't be available to Vue Router, as soon as the routing changes from its initial deserialisation.

#### How to make the InstantSearch router use Vue Router? 

This is possible by passing a custom router to to InstantSearch. The router prop accepts an object looking like this: 

```js
const instantSearchRouting = {
  router: {
    read() {
      return router.currentRoute.query;
    },
    write(routeState) {
      router.push({
        query: routeState,
      });
    },
    createURL(routeState) {
      return router.resolve({
        query: routeState
      }).href;
    },
    onUpdate() {}, 
    dispose() {},
  },
}
```

The problem is that this doesn't work with Objects (https://github.com/vuejs/vue-router/issues/1268). The solution can be in two ways. 

1. use `stateMapping` to make the `routeState` fully flat, or only using arrays. These arrays can be nested two times, but not more
2. modify Vue Router to work with objects (https://github.com/vuejs/vue-router/issues/1259#issuecomment-306000548)

```js
import qs from 'qs';

const router = new Router({
    routes: [
        // ...
    ],
    // set custom query resolver
    parseQuery(query) {
        return qs.parse(query);
    },
    stringifyQuery(query) {
        var result = qs.stringify(query);

        return result ? ('?' + result) : '';
    }
});
```

That way it works with nested objects without problem, but has the downside it needs configuration and is actually slightly less nice-looking than the default routing. 

The proper solution would be creating a stateMapping by default, or building that mapping from objects to nested arrays in a "router" to plug into the library directly. If there's enough people who see the advantage of using these arrays in Vue InstantSearch with Vue Router directly, we can do that, and people who see this issue can experiment with it now. 

### What is the version you are using?

> Always try the latest one before opening an issue.

v2.0.0-alpha.3

**Comment by Haroenv** [comment]
For reference, here's a routing config that makes the objects flat. I only made it work for hierarchicalMenu,  refinementList, sortBy, page, hitsPerPage, searchBox. It won't work for numericRefinementList, numericSelector, priceRanges, range, starRating & toggle since those use a different form of the uiState object. 

https://github.com/algolia/vue-instantsearch/blob/53efcc546cce4c6a8fd6320c92b597942749d4a9/examples/vue-router/src/Search.vue#L151-L175


If you use any of the methods to make the object flat when you **do** know the attributes of your UI in advance, you can create the URLs of the form described in the InstantSearch guide. Those will work without any of the customisation in the code sample above

**Comment by Haroenv** [comment]
there's a guide on Vue Router & Vue InstantSearch now: https://v2--vue-instantsearch.netlify.com/advanced/vue-router-url-sync.html

**Comment by alishanster** [comment]
Hello,
For some reason when I use ```:routing="true"```, I get an error in console:
```vue.js?ver=2.6.10:634 [Vue warn]: Invalid prop: custom validator check failed for prop "routing".```, which freezes the page.

**Comment by Haroenv** [comment]
True is not an allowed prop for Vue InstantSearch routing, instead you need to explicitly pass the state mapping & history, as seen here https://www.algolia.com/doc/api-reference/widgets/instantsearch/vue/#widget-param-routing

by the way, in the future it's more likely to be seen by us if you open a fresh issue with context, linking older issues you saw than commenting on them.
