### ISSUE TITLE
V2 - multiple anormal search just while scrolling on the page.

### ISSUE THREAD

**Issue by tfossoul** [algolia/vue-instantsearch#546]
**Feedback on the v2 alpha version 🆕**

Hi, 

I'm trying to migrate my website to the v2Alpha.
I detect something really strange: when I start scrolling on my webpage the system start to make a bunch of search request to my backend.
Any idea ?
![image](https://user-images.githubusercontent.com/7678234/46484481-29182600-c7fa-11e8-9186-5aac555403d3.png)

**Comment by Haroenv** [comment]
Scrolling shouldn't send any new requests, but it could be possible that you have an infinite loop because of inline objects and arrays in the template. 

Without a sandbox I won't be able to debug this though :)

**Comment by tfossoul** [comment]
Mmm everythings is working fine when I'm not trying to use our own backend and do direct request.

When are you plan to work on this ?

**Comment by Haroenv** [comment]
I can work on this when I get a reproducible example.

**Comment by tfossoul** [comment]
@Haroenv Sorry. I was talking about the "use your own backend" functionnality :).

I add the following code `searchForFacetValues() { return /* a promise */ }` as you propose me on the #545.
I don't have anymore multiple request when I'm scrolling. But.

Now the scrolling is now really slow. it appear the system is doing some stuff maybe related to the widgets.
It appear the system remove then add widget. I constat when I'm scrolling the search result on the refinement list is reseted.

You can see on theses pictures on the right the addWidget and removeWidget are called (and they are called several times when I scroll the window).

To test that you need to realise the test with a backend and I don't know how to give you a sandbox available online...

![image](https://user-images.githubusercontent.com/7678234/46523102-00893e00-c885-11e8-867d-a4da2342ffbd.png)
![image](https://user-images.githubusercontent.com/7678234/46523109-04b55b80-c885-11e8-8cf7-36351dedae8f.png)

**Comment by samouss** [comment]
Hi @tfossoul, thanks for screenshots! Like @Haroenv said without a reproducible example it will be hard to understand where the issue come from. Could you create a small CodeSandbox ([you can fork this one](https://codesandbox.io/s/vqw30v6r40)) with your Vue InstantSearch code even without the custom back-end. It will help us to spot potential issue. Thanks!

**Comment by Haroenv** [comment]
Hey @tfossoul; I'd like to get to the bottom of this, but I haven't seen this happen on my end. Is it possible that you could try distilling this to an example on codesandbox or else giving me access to your full code so I can debug that way?

**Comment by tfossoul** [comment]
@Haroenv  I think we could took back the discussion after you start and finish to work on the "use your own backend" functionnality :) Because this issue appear on my system only when i'm trying to pass by my backend. So we are both loosing our time actually trying to figure out that issue that could simply be solved later... But thanks anyway :)

**Comment by Haroenv** [comment]
Looking at what you said, it doesn't seem related to backend queries. I made a sandbox here which also does basically the same as backend querying, but I don't have any reason why anything should be happening on scroll. https://codesandbox.io/s/zx4y4l9orl

You can likely leave the actual parts of your app which call the backend, but importantly leave all bits which listen to scroll; e.g. for displaying a menu on the side or something? I think you're unmounting things when they're not supposed to be mounted&unmounted (on scroll)

**Comment by Haroenv** [comment]
Please leave a reproducible example of multiple requests being done with the same search parameters. 

It's also best practice to cache search requests using a custom backend to avoid these kind of situations in the first place.

I'll reopen if this is something that's still reproducible 🙂
