### ISSUE TITLE
v2 - use cases for emitting events when refining

### ISSUE THREAD

**Issue by Haroenv** [algolia/vue-instantsearch#552]
**Feedback on the v2 alpha version 🆕**

### Describe the bug / features

There might be some use cases where people want to listen to things happening inside widgets and do side effects. One major use case used to be routing, bu that can be solved in different ways now. 

### Reproduction

Please for every use case you have, make a sandbox link with https://codesandbox.io/s/zx4y4l9orl with the code you'd like to see working and give some explanation on what you expect to be emitted at which point

### What is the version you are using?

> Always try the latest one before opening an issue.

v2.0.0-alpha.3

**Comment by drpeck** [comment]
I've had to write a custom component, just to be able to output the number of page results in a location outside of the <ais-instant-search />

**Comment by Haroenv** [comment]
Thanks for that use case @drpeck. Which API would be ideal for you if it would exist?

**Comment by drpeck** [comment]
I guess just a change event on the main AIS component, for any changes to the state data changes. The full new state data provided as an argument, and potentially the old state data too if that wasn't too hard.
________________________________

**Comment by haoyun** [comment]
This was an old issue but i would also be happy to see if the ais-instantsearch compoent can emit the state changes.

**Comment by Haroenv** [comment]
I'd say the low number of replies here indicates we don't need events
