### ISSUE TITLE
Bug: numeric filter invalid syntax

### ISSUE THREAD

**Issue by zangab** [algolia/vue-instantsearch#559]
**Bug 🐞**

## What is the current behavior?
I encounter 2 problems at the moment when dealing with multiple numeric filters in the `queryParameters`.

### If I add multiple numeric filters, error is thrown.
The code looks like this:

`[
  [
    'start.timestamp>=1000',
    'end.timestamp>=1500'
  ],
  [
    'start.timestamp<=2000',
    'end.timestamp<=2500'
  ]
]`

Error: **"Invalid syntax for numeric condition:[object Object]"**
> Interestingly, if I only have 1 of the array, it does work fine. However, that's not what I need.

### If I add a numeric range filter, error is thrown.
The code looks like this:

`[
  'start.timestamp:1000 TO 2000',
  'end.timestamp:1500 TO 2500'
]`

Error: **"Invalid syntax for numeric condition:[object Object]"**

## Make a sandbox with the current behavior

Template: https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch
As no one responds to my [other bug ticket,](https://github.com/algolia/vue-instantsearch/issues/480) I wont waste my time to reproduce any other stuff.

## What is the expected behavior?

Getting the results according to the numeric filter.

## Does this happen only in specific situations?

Occurs always.

## What is the version you are using?

1.7

> Always try the latest one before opening an issue.
Can't use v2.0.0, as I would need to rewrite a bunch of code.

**Comment by Haroenv** [comment]
I'm seeing this work as expected, no error. I used the same condition as your example, but changed the attributes to ones that exist in the demo index. https://codesandbox.io/s/4rk1l50n4w?module=%2Fsrc%2FApp.vue

Is what I did also what you did?

**Comment by zangab** [comment]
🙈🙈🙈

Yeah, it's actually the same as you did.
Initially I was using multiple separate algolia-stores and refactored it to using just one. There was still an old function left, which also set the `numericFilters` property on a specific event. In there an object was set to the property & causing the error.

UPDATE:
Both versions work. The one with multiple arrays (`[ [], [] ]`) and the one with the numeric range (`attribute:<value> TO <value>`)

**Comment by Haroenv** [comment]
Glad it's working 👍
