### ISSUE TITLE
Is it possible to use vue-instantsearch with Algolia places?

### ISSUE THREAD

**Issue by emdahlstrom** [algolia/vue-instantsearch#563]
Hi! Thank's for a great project! I'm just wondering if it is possible to use vue-instantsearch with Algolia places. I see there is a mention of instantsearch.js on the Algolia Places page. I can't seem to figure out how to use places if it is possible.

**Comment by Haroenv** [comment]
There’s no built-in component right now, but it’s possible to write your own Vue wrapper for the library, and the. Use that to set Center and radius search Parameters. 

Unfortunately I don’t have an example for that right now, but feel free to start it and I’ll try to help you out where you’re stuck

**Comment by emdahlstrom** [comment]
Many thanks! I got places running in Vue, though not in Nuxt. I'll hack away a bit and get back to you.

**Comment by Haroenv** [comment]
Yes, places will need to be wrapped in a no-ssr component, since it uses `window` and `document` in the code without fallback for node

**Comment by Haroenv** [comment]
Also, it would be nice if you gave a quick demo on how you made this work (we have a [template](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch)) for other people with the same questions

**Comment by emdahlstrom** [comment]
I looked at the template but it seemed oriented around instant search and I haven't tried integrating them yet, but I can certainly share how I made places work in vue. I'll just clean up the code a bit and share a sandbox.

I've seen that there are a couple of places integrations but they seem outdated(? or I just cant make them work) or in once case depends on other Vuetify components.

**Comment by ajw4sk** [comment]
Ever make any progress on that?

**Comment by Haroenv** [comment]
Here's a integration with places in Vue:

[![Edit test-project](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6wz966kz23?module=%2Fsrc%2Fcomponents%2FPlaces.vue)

see https://github.com/algolia/places/issues/662 too.

A more advanced component could make use of `connectGeoSearch` here

**Comment by Haroenv** [comment]
Places is no longer exists, so this issue can't be solved anymore.
