### ISSUE TITLE
V2 doesn't seem to work in IE11 - at all.

### ISSUE THREAD

**Issue by JustinSainton** [algolia/vue-instantsearch#564]
**Feedback on the v2 alpha version 🆕**

### Describe the bug / features

Doesn't appear to work at all in IE11.

### Reproduction

https://codesandbox.io/s/l4wxnxy2jz <-- I found this simple Sandbox on the repository. I attempted to open in a session at crossbrowsertesting.com in IE11. It doesn't load at all. The app failing to load (with no JS errors at all) is also what we're experiencing on our production site.

### How to resolve or implement the fix?

Not sure what the necessary fix is yet.

### What is the version you are using?
alpha v3.

**Comment by Haroenv** [comment]
You need to add polyfills, see: https://v2--vue-instantsearch.netlify.com/getting-started/older-browsers.html

**Comment by Haroenv** [comment]
@JustinSainton, note that CodeSandbox itself doesn't work on IE11, meaning that you won't be able to try it there, you will need to make a local version. Did you make it work since, or do you have more questions?

**Comment by JustinSainton** [comment]
Thanks @Haroenv! For sure, I noticed Codebox seems to always fail in IE11. Still seeing lots of breakage in IE11, but adding the polyfills helped quite a bit! Will close for now and debug further internally.

**Comment by Haroenv** [comment]
Let me know if you have a specific problem where something is not clear how to polyfill.

**Comment by JustinSainton** [comment]
Definitely! My assumptions are that the polyfill is pretty much just plug and play. It's not quite there yet, but it's getting better! My hunch at this point is just that modern browsers are hiding my own broken code better than IE11 does :P

**Comment by Haroenv** [comment]
Let me know if you have pinpointed anything I missed in the documentation, IIRC Object.assign is missing in ie11
