### ISSUE TITLE
v2: Unable to change index when the historyRouter is being used

### ISSUE THREAD

**Issue by chamby** [algolia/vue-instantsearch#567]
**Feedback on the v2 prerelease version 🆕**

### Describe the bug / features

I want to dynamically switch indexes but also make use of the historyRouter. I can get both of these pieces of functionality to work on their own, but together they cause an error in Vue when trying to reinitialize the routes.

```vue
  <ais-instant-search
    :search-client="searchClient"
    :index-name="indexName"
    :routing="{
      router: historyRouter(),
      stateMapping: simpleMapping(),
    }"
  >
```

### Reproduction

https://codesandbox.io/s/m4lz8q393x

Click the button that says "Click me to change the index". There will be an error about the index not existing, ignore that. You can plug in a working index if you like.

The real error is in the console.

`[Vue warn]: Error in callback for watcher "routing": "Error: routing configuration can not be changed dynamically at this point.`

### How to resolve or implement the fix?

Not sure. I am guessing that the routing needs to be re-initialized more gracefully.

### What is the version you are using?

v2.0.0-beta.1

**Comment by Haroenv** [comment]
Ah, it seems to be happening because you write the object inline, meaning that Vue will tell us that it changed, while it didn't actually change. 

https://codesandbox.io/s/yw88pjzjzj

fixes it. 

Here's an alternative way of writing the code that changes the index:

```vue
<ais-sort-by :items="[{ value: 'instant_search' }]">
  <template slot-scope="{ refine }">
    <button type="button" @click="refine('instant_search_price_asc');">
      Click me to change the index
    </button>
  </template>
</ais-sort-by>
```

https://codesandbox.io/s/8k61l289nj

Both ways are functionally equivalent though.

**Comment by chamby** [comment]
Thanks. This indeed fixes the issue.
