### ISSUE TITLE
V2 Docs search not working 

### ISSUE THREAD

**Issue by ul8** [algolia/vue-instantsearch#569]
**Feedback on the v2 prerelease version 🆕**

### Describe the bug / features

When I search on https://v2--vue-instantsearch.netlify.com/ the search results link to V1 of the docs which really is a big pain when trying to migrate.

By the way I was specifically looking for <ais-index  :auto-search="false">  and was searching for "auto-search" - seems like it is completely gone in V2?

**Comment by Haroenv** [comment]
auto-search is completely gone, and replaced by: https://v2--vue-instantsearch.netlify.com/advanced/conditional-requests.html

**Comment by Haroenv** [comment]
DocSearch on the new website isn't working because python apparently doesn't think `--` is allowed in urls :(

**Comment by Haroenv** [comment]
The documentation is now available at https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/vue/ (and has search again)
