### ISSUE TITLE
v2 - <ais-input> component removed?

### ISSUE THREAD

**Issue by ul8** [algolia/vue-instantsearch#570]
**Feedback on the v2 prerelease version 🆕**

### Describe the bug / features

The <ais-input> component seems to be removed, but this is not mentioned in the migration docs. 

What is the recommend alternative?

**Comment by Haroenv** [comment]
Ah you’re right, I should have mentioned that in the docs. The recommended way is:

1. Use ais-search-box
2. Use the default template in it (see stories on how to do that) if you need complete custom rendering without our wrapper

**Comment by ul8** [comment]
@Haroenv Thanks I expected you'd say that just making sure :) Just trying to help improving the docs.

**Comment by Haroenv** [comment]
documented in https://github.com/algolia/vue-instantsearch/pull/554/commits/5e6d26729aeee85b443309309df53fbddc45f949
