### ISSUE TITLE
v2 - RefinementList - Add slot for searchable

### ISSUE THREAD

**Issue by michelemarrionline** [algolia/vue-instantsearch#572]
**Feedback on the v2 prerelease version 🆕**

### Describe the bug / features

Please add the ability to change the placeholder text

### What is the version you are using?

v2

**Comment by Haroenv** [comment]
Placeholder text should indeed be changeable, I thought I added that :)

**Comment by michelemarrionline** [comment]
> Placeholder text should indeed be changeable, I thought I added that :)

Sure? In the refinement List with the option searchable="true"?

Can't find in the docs :)

Can u help me?
<3

**Comment by Haroenv** [comment]
I think, but will have to check next week since I’m not by a computer now, that it doesn’t have the option; I’ll get back to you!

**Comment by Haroenv** [comment]
Looks like I forgot to close this, `searchable-placeholder` is an option on `ais-refinement-list` since the last beta
