### ISSUE TITLE
v2 - Timing issue / race condition / circular dependency resulting from trying to conditionally show a facet component

### ISSUE THREAD

**Issue by chamby** [algolia/vue-instantsearch#573]
**Feedback on the v2 prerelease version 🆕**

### Describe the bug / features

Timing issue / race condition / circular dependency resulting from trying to conditionally show a facet component.

### Reproduction

https://codesandbox.io/s/0m7vw69o0w

Type "show" into the search box.

#### Expected behavior

The `<ais-refinement-list v-show="showFacet" attribute="material_readable" />` facet is rendered.

#### Actual behavior

The helper state is corrupted / reset.

### How to resolve or implement the fix?

I know that using a watcher on the helper state is probably not advisable. Is there another way to conditionally show a facet component?

This particular issue is reproducible when using routing as well as using a `ais-hierarchical-menu` component. Without these requirements this issue does not occur. 

### What is the version you are using?

v2.0.0-beta.1

**Comment by chamby** [comment]
I believe this may also have been caused by inline props (#575). I will follow-up with more information.

**Comment by Haroenv** [comment]
Thanks! An infinite loop because of changing props likely is one of the main causes

**Comment by chamby** [comment]
Yes, that was the issue. An additional issue was related to my code causing another infinite loop using a watcher on the helper state and changing data with every call.
