### ISSUE TITLE
v2 - Vue Warning: Duplicate keys detected when using CurrentRefinements component

### ISSUE THREAD

**Issue by chamby** [algolia/vue-instantsearch#574]
**Feedback on the v2 prerelease version 🆕**

### Describe the bug / features

Vue Warning: Duplicate keys detected

### Reproduction

Use the CurrentRefinements component with a disjunctive facet. Select multiple entries for the disjunctive facet.

### How to resolve or implement the fix?

Choose a unique key here https://github.com/algolia/vue-instantsearch/blob/2a67eeff89fd6ce3b0628f24244b13133bd114c0/src/components/CurrentRefinements.vue#L14 . Perhaps a combination of the attribute and label values appended together.

### What is the version you are using?

v2.0.0-beta.1

**Comment by Haroenv** [comment]
Good call, I forgot that they weren't merged in this version 👍
