### ISSUE TITLE
v2 - refine method not found

### ISSUE THREAD

**Issue by leonardovilarinho** [algolia/vue-instantsearch#585]
**Feedback on the v2 prerelease version 🆕**

### Describe the bug / features

I'm trying to customize the interface of the components, in the documentation it shows the `refine` command to refine the menu with the data selected from the menu:

```
<ais-menu attribute="brands">
  <template slot-scope="{ items }">
    <ul>
      <li v-for="item in items" :key="item.value">
        <button @click="refine(item.value)">
          {{ item.label }}
        </button>
      </li>
    </ul>
  </template>
</ais-menu>
```

(https://v2--vue-instantsearch.netlify.com/advanced/custom-components.html)

But when I access the page and click on a menu it returns the error that the method does not exist:
> Uncaught TypeError: Cannot read property 'refine' of undefined

### Reproduction
Create a new project in the App.vue place the following code:

```
<template>
  <ais-instant-search
    :search-client="searchClient"
    index-name="XXX"
  >
    <ais-search-box/>
    <ais-menu attribute="categories.level0">
      <template slot-scope="{ items }">
        <ul>
          <li v-for="item in items" :key="item.value">
            <button @click="refine(item.value)">
              {{ item.label }}
            </button>
          </li>
        </ul>
      </template>
    </ais-menu>

    <ais-hits>
      <template slot="item" slot-scope="{ item }">
        <h2>
          <ais-highlight :hit="item" attribute="name" />
        </h2>
      </template>
    </ais-hits>
  </ais-instant-search>
</template>

<script>
import algoliasearch from 'algoliasearch/lite'

export default {
  name: 'app',
  data() {
    return {
      searchClient: algoliasearch(
        'XXX',
        'XXX'
      ),
    }
  }
}
</script>
```

PS: replace the `XXX`

### What is the version you are using?

2.0.0-beta.1

**Comment by samouss** [comment]
Yes indeed there is an issue inside the documentation. The `refine` function comes from the slot scope. You have to define the value inside the object like this:

```vue
<ais-menu attribute="categories.level0">
  <template slot-scope="{ items, refine }">
    <ul>
      <li v-for="item in items" :key="item.value">
        <button @click="refine(item.value)">
          {{ item.label }}
        </button>
      </li>
    </ul>
  </template>
</ais-menu>
```

Here is [a live example](https://codesandbox.io/s/q8n9zj57nj) with the code above. 

-----

I've create a [PR](https://github.com/algolia/vue-instantsearch/pull/586) to fix the documentation.

**Comment by leonardovilarinho** [comment]
@samouss Thanks for the information.
