### ISSUE TITLE
Add replica index to settings parameters

### ISSUE THREAD

**Issue by renanbronchart** [algolia/vue-instantsearch#590]
**Feature ⚡️**

### What is your use case for such a feature?

Actually, I want to add replica index to settings parameters, like here :
https://www.algolia.com/doc/api-reference/api-parameters/replicas/

I feel is not possible actually ?

Thanks for reply

### What is the version you are using?

I use Version 1.6.0 of vue-instantsearch

**Comment by Haroenv** [comment]
For that you would use [`ais-sort-by-selector`](https://community.algolia.com/vue-instantsearch/components/sort-by-selector.html) (in v2: [ais-sort-by`](https://v2--vue-instantsearch.netlify.com/components/sortby))

Is that what you expected?

**Comment by Haroenv** [comment]
I'm not exactly sure what you meant with this issue (apart from `sort-by`), so I will close it, but if you or anyone else has more information, please open a new issue which clarifies which feature could be added.
