### ISSUE TITLE
Couldn't find/use CurrentRefinements component.

### ISSUE THREAD

**Issue by jimba-lc** [algolia/vue-instantsearch#591]

**Comment by Haroenv** [comment]
Hi, could you explain a bit more what your issue is? Version 1 of Vue InstantSearch does not have anything to show the current refinements, but v2 (currently in beta) has it: https://v2--vue-instantsearch.netlify.com/components/currentrefinements

**Comment by jimba-lc** [comment]
@Haroenv yeah I realize that I wasn't using beta. Thanks.
