### ISSUE TITLE
v2 How to do InstantSearch with a filter?

### ISSUE THREAD

**Issue by leonardovilarinho** [algolia/vue-instantsearch#594]
Hello,

I would like to know if there is any way to edit the search made by the `ais-instant-search` component. By default it brings up the complete index, how can I apply a number filter for it, for example: `in_stock = 1`, thus loading only the products in stock, without having to use` ais-numeric-menu` for this ?

**Comment by Haroenv** [comment]
You can use the filters prop on ais-configure for that :)

**Comment by leonardovilarinho** [comment]
@Haroenv thanks!! 👍
