### ISSUE TITLE
Search results don't accept query if no search box added

### ISSUE THREAD

**Issue by drpeck** [algolia/vue-instantsearch#608]
Due to the design, my search box is outside of my Instant Search app.

I'm using routing, to pass in a query, and this value appears to be set accordingly to documentation. If I have a dummy AIS Search Box, hidden with `style="display:"none"`, within my AIS app then this works fine. I can set the query from my external textbox, or by manually modifying the url. No issues. As soon as I delete the hidden dummy search box the query is no longer passed on. It appears that the search box is required for a search by query.

**Comment by StevenOtto** [comment]
Hey drpeck, I also have a searchbox outside my Instant Search app. How did you configure your routing to pass in a query from your search box? I use a v-model in Vue to story the query. 

`routing: {
                router: historyRouter(),
                stateMapping: {
                    stateToRoute() {
                      return {
                        query: this.query
                      };
                    },
                    routeToState() {
                      return {
                        query: this.query
                      };
                    }
                }
            }`

**Comment by Haroenv** [comment]
Hi @drpeck, this is completely expected. InstantSearch is made with concept: search parameters are mapped to elements which are on screen. A search box `[hidden]` is a possible solution. If you'd prefer a solution where there's no unnecessary / hidden rendering, you can make a custom component: VirtualSearchBox, which would act like a search box for the context of the search. You can make it like this:

```js
import { createWidgetMixin } from 'vue-instantsearch';
import { connectSearchBox } from 'instantsearch.js/es/connectors';

export default {
  mixins: [createWidgetMixin({ connector: connectSearchBox })],
  render() {
    return null;
  },
};
```

Then you can use `<virtual-search-box />` instead of `<ais-search-box :hidden />`

**Comment by Haroenv** [comment]
Also quite weird that I see this issue now, but that it's supposedly made in January 🤔

**Comment by drpeck** [comment]
I did not explain this well!

So I can set the query from an external textbox, pass it in (I forget if this was through the router or a prop), and set the query using `<ais-configure />`. It doesn't work, until I add a hidden search box. So it appears that the search box does more than allow you to input a query.

**Comment by Haroenv** [comment]
Yes, a search parameter set by a Configure won’t be synchronised with the URL, other widgets do synchronise. This makes me think we should maybe change that default, and by default do give Configure to the url; but filter it out. Then you can choose to synchronise it if you want

**Comment by Haroenv** [comment]
So for now the workaround is still as described if you want something to show in the url

**Comment by Haroenv** [comment]
The state here is still correct, and we don't plan to change it. This behaviour can be achieved in two ways:

- hidden / non-rendering search box
- ads-configure with a custom stateMapping to make the query show up in the URL
