### ISSUE TITLE
v2 - How to retrieve instantSearchInstance from a component?

### ISSUE THREAD

**Issue by billmn** [algolia/vue-instantsearch#613]
Hi guys,
is it possibile to retrieve the <code>instantSearchInstance</code> object from my code (e.g. from **mounted**) ?

```vue
<template>
    <ais-instant-search :search-client="searchClient" :index-name="indexName">
        <ais-autocomplete>
            <div slot-scope="{ currentRefinement, indices, refine }">

            </div>
        </ais-autocomplete>
    </ais-instant-search>
</template>

<script>
    import algoliasearch from 'algoliasearch/lite';

    export default {
        data() {
            return {
                searchClient: algoliasearch('###', '###'),
            }
        },
        mounted() {
            // Like: this.instantSearchInstance
        },
    }
</script>
```

**Comment by samouss** [comment]
Yes it's possible with the `createWidgetMixin` that we exposes. You can find an example inside [the documentation](https://www.algolia.com/doc/guides/building-search-ui/going-further/improve-performance/vue/?language=vue#caching). The purpose of the guide is to refresh the cache but you can grasp the concept around the mixin. You can provide the value `true` to connector to create a component that only access the instance.

```js
export default {
  mixins: [createWidgetMixin({ connector: true })],
  mounted() {
   // You have access to the instance
    this.instantSearchInstance
  }
};
```

**Comment by billmn** [comment]
Thanks @samouss 

I've tried your suggestion but I get a console error: (**search-hero** is the name of my component)
```
Uncaught TypeError: It looks like you forgot to wrap your Algolia search component "<search-hero>" inside of an "<ais-instant-search>" component.
```

You can find an example here: https://codesandbox.io/s/zx1rxyv1qx

If you remove <code>createWidgetMixin({ connector: true })</code> works fine.

**Comment by samouss** [comment]
You got this error because the component that uses the widget mixin **must be scoped under** the `ais-instant-search` component. This is the only requirement to create / use Vue InstantSearch widgets. In your example you cannot use the mixin within the `SearchHero` component because it's the one that creates the instance. You have to create another component scoped under the `ais-instant-search`.

**Comment by billmn** [comment]
Great, thank you for your explanation!
