### ISSUE TITLE
Programmatically set the pagination page

### ISSUE THREAD

**Issue by simonerlandsen** [algolia/vue-instantsearch#614]
**Feature ⚡️**

### What is your use case for such a feature?

Letting the user use the browser back button for navigating to the previous pagination page. By letting me disable the default pagination click event and setting the page to be navigated to programmatically on the ais-pagination component I could handle the pagination page change with vue-router (by passing the page-change event payload to vue-router).

### What is your proposal

Adding one prop on the ais-pagination component for passing in which page to change to. The component would have to disable the normal page change triggering click event when this prop is used.

or

Adding two props on the ais-pagination component. One for disabling the click event to change the pagination page, and one for triggering a page change manually.

If there is better ways of doing this, I would off course be happy to to comply.

### What is the version you are using?

vue-instantsearch 1.7.0

**Comment by samouss** [comment]
You can follow [the guide on URLSync](https://community.algolia.com/vue-instantsearch/advanced/vue-router-url-sync.html#initialize-instantsearch-with-route-parameters) for the V1 of Vue InstantSearch. You can override the page value with `searchStore.page = XX`.

We released a new version of Vue InstantSearch that comes [with URLSync](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/) out of the box. You can find [the migration guide](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/vue/?language=vue#upgrade-from-v1-to-v2) on the documentation website. You can install it with:

```sh
npm install vue-instantsearch@beta
```

Don't hesitate to give us feedback on this version!

**Comment by simonerlandsen** [comment]
@samouss thank you!  `searchStore.page = XX` works like a charm!
