### ISSUE TITLE
[ais-configure] The widget does not work with HTML template

### ISSUE THREAD

**Issue by samouss** [algolia/vue-instantsearch#617]
One requirement of the `ais-configure` widget is that the prop must be camel-case. But it doesn't work with an HTML template since HTML is case-insensitive. The attributes are always lowercase. It does throw an error on the API side (see [example](https://codesandbox.io/s/jpo5xj5ql9)).

> https://discourse.algolia.com/t/camelcase-attributes-in-ais-configure/7080/3

**Comment by Haroenv** [comment]
Damn, I fear this won't be solvable without shipping a kebab-to-camelcase in the library 😢

**Comment by jryd** [comment]
Just ran into this issue today.

Is there a workaround to use in the meantime?

In mine and @samouss case we are just wanting to specify the hits per page. All my ais components are written in my HTML and moving away from this approach is far from practical.

**Comment by Haroenv** [comment]
Without shipping runtime Vue, one way to go is the following one-on-one mapping (which we can't do in the library itself because it would blow up the size of the widget).

```js
import { connectConfigure } from 'instantsearch.js/es/connectors';
import { createWidgetMixin } from 'vue-instantsearch';

export default {
  props: {
    // add your relevant props
    hitsPerPage: {
      type: Number,
      required: false,
    },
  },
  mixins: [createWidgetMixin({ connector: connectConfigure })],
  computed: {
    widgetParams() {
      return {
        searchParameters: {
          // do a manual mapping here
          hitsPerPage: this.hitsPerPage,
        },
      };
    },
  },
  render() {
    // no template or rendering at all
    return null;
  },
};
```

[![Edit default-theme](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q7xjp199jw?module=%2Fsrc%2FMyConfigure.js)

**Comment by Haroenv** [comment]
I just found something that might solve the issue: giving `:hits-per-page.camel="4"` as a prop.

see: https://vuejs.org/v2/api/#v-bind

**Comment by samouss** [comment]
> I just found something that might solve the issue: giving `:hits-per-page.camel="4"` as a prop.

@Haroenv does it work within HTML template? If yes we have to investigate how to integrate this without breaking the current API.

**Comment by Haroenv** [comment]
This is something that's specifically made for html templates if I understand it correctly. Using it is something done by the user, not by us, so this isn't a breaking change.

**Comment by Haroenv** [comment]
I've tried this out in html templates and string templates, and `.camel` is the way to go. I made a PR to the docs to mention this solution specifically (will be deployed in 3 weeks, because docs are currently in code freeze).

```html
<ais-configure
  v-bind:hits-per-page.camel="4"
  v-bind:distinct="true"
></ais-configure>
```

**Comment by donPuerto** [comment]
@Haroenv can you provide an example on how to override layout using Vuetify.
```html
<ais-instant-search-ssr>
      <ais-search-box/>
      <ais-configure query="atem" :hits-per-page.camel="2"/>
      <ais-stats/>
      <!-- <ais-refinement-list attribute="brand"/> -->

      <ais-hits>
        <template slot="item" slot-scope="{ item }">
          <div>
            <ais-highlight attribute="firstName" :hit="item"/>
            <ais-highlight attribute="lastName" :hit="item"/>
          </div>

          <div>
            <ais-highlight attribute="email" :hit="item"/>
          </div>
          <div>
            <ais-highlight attribute="role" :hit="item"/>
          </div>
          <div>
            <ais-highlight attribute="phone1" :hit="item"/>
          </div>
          <div>
            <ais-highlight attribute="phone2" :hit="item"/>
          </div>
        </template>
      </ais-hits>
      <ais-pagination/>
    </ais-instant-search-ssr>
```

**Comment by Haroenv** [comment]
I don't understand your question @donPuerto, the code you wrote seems valid to me. Can you open a new issue with full reproduction and a clear description of the problem?
