### ISSUE TITLE
Dynamic added widgets to an already started instantsearch can render to early

### ISSUE THREAD

**Issue by maxiloc** [algolia/vue-instantsearch#620]
![image](https://user-images.githubusercontent.com/1689007/52725623-dde4ff80-2fb1-11e9-8fd1-294f6a5059e6.png)

**Comment by samouss** [comment]
Could you provide us a working example of your issue? It will help a lot to better understand the problem. We provide template in order to avoid you the boilerplate part. You can find it on [CodeSandbox](https://codesandbox.io/s/yv3rpojwp1).

**Comment by Haroenv** [comment]
We have fixed this issue in IFW-874 & https://github.com/algolia/algoliasearch-helper-js/pull/738 for the next major version of InstantSearch.js
