### ISSUE TITLE
Nuxt: ais-instant-search-ssr + ais-hierarchical-menu

### ISSUE THREAD

**Issue by LuXDAmore** [algolia/vue-instantsearch#626]
**Feedback on the v2 version 🆕**

### Describe the bug / features

After updating `vue-instantsearch` to ^2, I'm unable to get in sync with the component `ais-hierarchical-menu`.
For upgrading, I've followed the guide that you've provided.

### Reproduction

[CodeSandBox](https://codesandbox.io/s/13nmp7k5j4?autoresize=1&eslint=1&hidenavigation=1&moduleview=1)

### How to resolve or implement the fix?

I think that the problem could be in the `instantsearch.hydrate`, because I can see the `hierarchical-menu` without passing by the function during `beforeMount`.
Obviously, _the client-side rendered virtual DOM tree is not matching server-rendered content_.

### What is the version you are using?

"algoliasearch": "^3.32.0",
"nuxt": "^2.4.3",
"vue-instantsearch": "^2.0.0"

**Comment by Haroenv** [comment]
State to pass to findResultsState for a hierarchical menu looks like this:

```
hierarchicalFacets: [
        {
          name: 'hierarchicalCategories.lvl0',
          attributes: [
            'hierarchicalCategories.lvl0',
            'hierarchicalCategories.lvl1',
            'hierarchicalCategories.lvl2',
            'hierarchicalCategories.lvl3',
          ],
          separator: ' > ',
          rootPath: null,
          showParentLevel: true,
        },
      ],
```

This can be found in the devtools when you have a regular app mounted with this. 

Here's a forked, working version: https://codesandbox.io/s/r7n924xyoo

**Comment by LuXDAmore** [comment]
Thank You very much! 😄

I've tried with `hierarchicalFacets`, but with an array of Strings.
First (version 1), i used the `ais-tree-menu`, without having to specify this parameters and it worked, so, i've  thought the problem could be the `hydrate` method. 😅 

✌️
