### ISSUE TITLE
Nuxt with router urls - not work?

### ISSUE THREAD

**Issue by batFormat** [algolia/vue-instantsearch#628]
**Feedback on the v2 version 🆕**

### Describe the bug / features

Nuxt not support route urls?

### Reproduction

I'm trying to connect like in the documentation but it doesn't work.
https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/

### How to resolve or implement the fix?

How to solve this problem is not clear, because there are no errors in the console and terminal.

### What is the version you are using?

> Always try the latest one before opening an issue.

v2.0.0

**Comment by Haroenv** [comment]
The process should be the same as https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/?language=js#combining-with-vue-router 

What's the reason you want to combine the routers? In my testing it worked together without any issues if the Nuxt router isn't used. 

a sandbox of the precise problem you're trying to solve with synchronising with the router would also be ideal. There's a sample sandbox here:

https://codesandbox.io/s/github/algolia/vue-instantsearch/tree/v2/examples/nuxt

**Comment by batFormat** [comment]
Sorry my mistake!
I did not disconnect the `nuxt` router
