### ISSUE TITLE
custom search client with <ais-instant-search-ssr>

### ISSUE THREAD

**Issue by calvinmuller** [algolia/vue-instantsearch#630]
**Feature ⚡️**

### What is your use case for such a feature?
To be able to provide a custom search client with the SSR verision of instantsearch within nuxt.

### What is your proposal
Allow <ais-instant-search-ssr> to be able to take the search client and :routing option as in the non-ssr version.

### What is the version you are using?
^2.0.0

**Comment by Haroenv** [comment]
These options are passed to `createInstantSearch`, however, routing will not (yet) be taken in account on the server (this is to prevent calls to window etc., but when we will find a robust isomorphic solution  this will be solved).

A custom search client can be passed there, just like a regular one

**Comment by batFormat** [comment]
> These options are passed to `createInstantSearch`, however, routing will not (yet) be taken in account on the server (this is to prevent calls to window etc., but when we will find a robust isomorphic solution this will be solved).
> 
> A custom search client can be passed there, just like a regular one


It turns out I cannot transfer parameter `routing` according to the documentation?
https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/#basic-urls

**Comment by Haroenv** [comment]
https://codesandbox.io/s/13o2pyj4w3 here's a demo (download it however, CodeSandbox doesn't detect this as a SSR template)

**Comment by batFormat** [comment]
@Haroenv And for nuxt.js, the way is about the same as in this example that you sent?

**Comment by Haroenv** [comment]
Yes, that's practically the same, except according to  #628 you need to "disconnect" Nuxt's router to avoid conflict (or write your own router that synchronises with Nuxt's router

**Comment by Haroenv** [comment]
I'll close this issue, since I see nothing anymore that needs to be solved
