### ISSUE TITLE
missing 'createFromAlgoliaCredentials' and 'createFromSerialized'

### ISSUE THREAD

**Issue by nelsonlarocca** [algolia/vue-instantsearch#631]
**Feedback on the v2.0.0 version 🆕**
<a name="2.0.0"></a>
# [2.0.0](https://github.com/algolia/vue-instantsearch/compare/v2.0.0-beta.3...v2.0.0) (2019-02-18)

after npm i vue-instantsearch --save

and after compiling I got:

"export 'createFromAlgoliaCredentials' was not found in 'vue-instantsearch'
and
"export 'createFromSerialized' was not found in 'vue-instantsearch'

I couldn't find anything related to that functions at vue-instantsearch
any clue ?

**Comment by Haroenv** [comment]
These functions don't exist anymore, and are replace by:

## from
```js
import {createFromAlgoliaCredentials, createFromSerialized } from 'vue-instantsearch';
createFromAlgoliaCredentials(/* your credentials */);
```
## to
```js
import algoliasearch from 'algoliasearch/lite';
import { createInstantSearch } from 'vue-instant-search';

const searchClient = algoliasearch(/* your credentials */);

// credentials becomes search client
<ais-instant-search :search-client="searchClient" />

// createFromSerialized becomes -ssr & hydrate
const {instantSearch, rootMixin } = createInstantSearch({ searchClient, indexName });
<ais-instant-search-ssr />
beforeMount: instantSearch.hydrate()
```

A full guide on SSR is available here: https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/vue/
