### ISSUE TITLE
v-model + scoped slots

### ISSUE THREAD

**Issue by jsinhSolanki** [algolia/vue-instantsearch#641]
Hi, I am trying out vue instant search. It's awesome. I customized my search hits but I can not customize my filters.
e.g.
The framework is have slider component which accepts array value of range using v-model. And I want to use `ais-range-slider`. In [Customize UI](https://www.algolia.com/doc/api-reference/widgets/range-slider/vue/?language=vue#customize-the-ui) example array is passed to `value` prop like below:
```
<template>
  <!-- ... -->
  <ais-range-input attribute="price">
    <div slot-scope="{ currentRefinement, range, refine }">
      <vue-slider
        :min="range.min"
        :max="range.max"
        :value="toValue(currentRefinement, range)"
        @input="refine({ min: $event[0], max: $event[1] })"
      />
    </div>
  </ais-range-input>
  <!-- ... -->
</template>
```

But slider component of my framework uses v-model for array value
e.g. 
```
<template>
  <vs-slider color="warning" v-model="value1"/>
</template>

<script>
export default {
  data(){
    return {
      value1:[60,90],
    }
  }
}
</script>
```

So, how can I use my component in this case. Can I access `currentRefinement` in my `data` or something else.

I have this problem in my all components. They all uses `v-model`.
e.g. `ais-numeric-menu` not uses my radio component. I tricked html so it looks like my component.

Sorry if it's silly question.

Also where can I find full guide/implementation or video of how can I create my custom widgets using my components. I can not understand this [guide](https://www.algolia.com/doc/guides/building-search-ui/widgets/create-your-own-widgets/vue/)

Regards

**Comment by Haroenv** [comment]
Hey, that's no problem, 

Any time a solution documents `v-model`, that's a shorthand for `@input` and `value`, you can see examples that fit this here: 

https://github.com/algolia/vue-instantsearch/blob/79d0573dc0b8b9685beecc114656288b7d03d6c9/stories/RangeInput.stories.js#L74-L125

**Comment by jsinhSolanki** [comment]
Thank you @Haroenv for your response. It worked with slider component.
However this doesn't work with radio component.
Here's my code:
```
<vs-radio :value="item.isRefined" :vs-value="item.value" @input="refine(item.value)">{{ item.label }}</vs-radio>
```

And i am not using vuetify i am using [vuesax](https://lusaxweb.github.io/vuesax/components/radio.html#default)

One last thing in my rating filter as shown here [guide](https://www.algolia.com/doc/api-reference/widgets/rating-menu/vue/?language=vue#customize-the-ui). I only get 4 start for filtering. What if I want to filter with 5 star??

Thank You again.

**Comment by Haroenv** [comment]
Can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch). Thanks!

I'm not sure I completely understand what you had as behaviour mismatch

**Comment by jsinhSolanki** [comment]
I created sandbox. Like is [here](https://codesandbox.io/s/5yx1kz5r9p?fontsize=14). My framework supports vue 2.5.19.

As you can see filter is working somehow but my radio doesn't look like working.
