### ISSUE TITLE
Can't apply a class name to ais-SearchBox-input within ais-refinement-list

### ISSUE THREAD

**Issue by AngyNoT** [algolia/vue-instantsearch#644]
**Bug 🐞**

### What is the current behavior?

It is impossible to apply a class-name to `ais-SearchBox-input` within `ais-refinement-list`

### Make a sandbox with the current behavior

https://4j2k883yp4.codesandbox.io/
If you inspect the ais-RefinementList-count, a "foo" class is applied. However, if do the same thing on ais-SearchBox-input, the "bar" class is not applied. 

### What is the expected behavior?

We should be able to apply a style to the `ais-SearchBox-input` class by using the following code : 

```
<ais-refinement-list
attribute="label"
searchable
:class-names="{
	'ais-SearchBox-input': 'test',
}" />
```

### Does this happen only in specific situations?

It happens all the time.

### What is the version you are using?

2.0.0

**Comment by samouss** [comment]
It's not currently possible to add a class on the `input` directly. You can add a class on the wrapper of the `SearchBox` though. Inside the example you've passed the class `bar` for `ais-RefinementList-searchBox`. You can see that the class is correctly set on the wrapper.

<img width="421" alt="Screen Shot 2019-03-13 at 20 54 11" src="https://user-images.githubusercontent.com/6513513/54310424-a24e4d00-45d2-11e9-80fe-bd3fcb256b42.png">
