### ISSUE TITLE
Multilingual facets

### ISSUE THREAD

**Issue by ayalon** [algolia/vue-instantsearch#645]
Hi

We try to index multilingual facets. 

Example in the database:

facet_id | "Name DE" | "Name EN"
--------|-------------|--------------
1            | "Label DE"   | "Label EN"

In the search vue app we need mixed languages in the results. This means, for DE results we index "Label DE" and for EN results we index "Label EN".

The main issue is, that the same facet will appear as "Label DE" and "Label EN". But in fact, this is only one facet with the facet_id.

How can we aggregate multilingual facets and reducing them to an ID?

It feels, like Algolia has a very limited multilingual support.

**Comment by francoischalifour** [comment]
I transferred the issue from [InstantSearch.js](https://github.com/algolia/instantsearch.js) @Haroenv. Feel free to tag/close it.

**Comment by samouss** [comment]
It's definitely not a limitation of Vue InstantSearch but more a limitation on the engine side. It's not the first time we have those use cases. You can find some alternative solution inside [this Discourse thread](https://discourse.algolia.com/t/facets-with-slug-alias/6870). The product team that works on the engine is already aware of this limitation.
