### ISSUE TITLE
The docs v1 is out

### ISSUE THREAD

**Issue by hernanimattos** [algolia/vue-instantsearch#646]
Docs v1 out..

In docs have redirect to docs/v1 and give 404
https://community.algolia.com/vue-instantsearch/getting-started/

**Comment by Haroenv** [comment]
Where did you find the link you posted? I don't think that ever worked. The correct link is: https://community.algolia.com/vue-instantsearch/getting-started/getting-started.html

I'll close this, but reopen if there's a link to update somewhere, thanks!

**Comment by maaxxicarvalho** [comment]
Hi @Haroenv 

The link can be found on the Vue Algolia documentation main page [https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/vue/](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/vue/)

Just scroll down a bit and you can see:

> You are reading the documentation for Vue InstantSearch v2. Read our migration guide to learn how to upgrade from v1 to v2. You can still find the v1 documentation **here**.

The link under the word **here** points to [https://community.algolia.com/vue-instantsearch/getting-started/](https://community.algolia.com/vue-instantsearch/getting-started/) which gives a 404

**Comment by Haroenv** [comment]
Good call, updating that one
