### ISSUE TITLE
ais-range-slider does not work out of the box

### ISSUE THREAD

**Issue by robmellett** [algolia/vue-instantsearch#647]
**Bug 🐞**

### What is the current behavior?
When using the range slider, the examples in the documentation do not work.
https://www.algolia.com/doc/api-reference/widgets/range-slider/vue/

The slider does not filter the results.   

Are we meant to pass a `v-model` value to the range slider?

### Make a sandbox with the current behavior
https://codesandbox.io/s/98k5vqx5lr

### What is the expected behavior?
When using the slider in the docs, it should filter the results.

### What is the version you are using?
    "algoliasearch": "3.30.0",
    "instantsearch.css": "7.1.1",
    "vue": "2.5.17",
    "vue-instantsearch": "2.0.0",
    "vue-slider-component": "^3.0.15"

> Always try the latest one before opening an issue.

Thanks in advance

**Comment by Haroenv** [comment]
Vue Slider Component v3 has changed its API and now uses `@change`, and no longer `@input`. I'll update the example https://codesandbox.io/s/qk2noolol9

**Comment by robmellett** [comment]
Thanks mate! I'll test it tomorrow.  Thank you for your help :)
