### ISSUE TITLE
Algolia + VueInstantSearch + Customize UI - Refinements gets cleared if I navigate to another page

### ISSUE THREAD

**Issue by jsinhSolanki** [algolia/vue-instantsearch#658]
**Bug 🐞**

### What is the current behavior?
I have algolia eCommerce Demo. When I select refinements everything works fine. But if I navigate to another url in my app algolia's Refinements gets cleared.
To test this I used..
```
<ais-current-refinements />
```

When I am in that page and apply filters it's shows like below:
![before](https://user-images.githubusercontent.com/31243533/55701849-4b317180-59f2-11e9-8412-0ac613468452.PNG)

But I navigate to another page and come back all Refinements(filters) gets cleared(reset).

### Make a sandbox with the current behavior
Sandbox: https://codesandbox.io/s/64zppzjrl3

Template: https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch

### What is the expected behavior?
Algolia's filters should remain applied even after route changes

### Does this happen only in specific situations?
I don't think so

### What is the proposed solution?
??

### What is the version you are using?
"algoliasearch": "^3.32.0",
"vue-instantsearch": "^2.0.0",
> Always try the latest one before opening an issue.

Related Issue:
My main issue is..
I have sidebar which contains all the filters and in tablets and mobile devices it gets hidden. So the problem is, this filters works fine in larger devices. But If I have tablet and I click on toggler button to open sidebar and then I apply filters. Now I click on close sidebar button and all filters get reset.
You can also check my sidebar(demo) here:
https://lusaxweb.github.io/vuesax/components/sideBar.html#default

**Comment by Haroenv** [comment]
The main issue that you're seeing here is the fact that the sidebar unmounts when it becomes invisible; but InstantSearch is built with the principle that the search state is driven by which widgets are currently on the page. 

A solution for that can be something like https://github.com/LinusBorg/portal-vue, or using the `hidden` (v-show vs v-if) attribute instead of fully unmounting

**Comment by jsinhSolanki** [comment]
Thanks @Haroenv for quick reply.
I seen the source code of sidebar component they used `v-show` to display sidebar. They don't use `v-if`.

My project is currently in production. So, a quick demo of solution of this issue will be very helpful(I don't have enough experience using portal-vue).
So, Is there in case in which I can solve this issue without using `portal-vue`.

Thanks

**Comment by Haroenv** [comment]
In your sandbox you are talking about different pages with the router, but in the text about the sidebar, which is confusing. Can you make an exact reproduction for the problem your facing?

**Comment by jsinhSolanki** [comment]
hello @Haroenv Thanks for response. I have created similar [sandbox](https://codesandbox.io/s/64zppzjrl3) as in my project.

Steps to reproduce:
1. Sidebar should be open when you visit sandbox
2. Click on any filter e.g. **<= $10**.  items will be filtered.
3. Now reduce the width of output window. So it triggers **handleWindowResize** method. it will close sidebar
4. Now if you look at results. Applied filter **<= $10** is cleared.
5. To verify filter increase the width again and you will see filter is clear in sidebar.

Here's GIF:
![ezgif com-optimize](https://user-images.githubusercontent.com/31243533/56187422-2b2c2e80-6040-11e9-89e4-02833ff30f26.gif)



Another Issue I was talking about is filter also gets cleared if I change the route and visit back. But this is optional.
Here's GIF:
![router change algolia](https://user-images.githubusercontent.com/31243533/56187246-a214f780-603f-11e9-9ae1-61d1898b3d59.gif)


Routing issue is optional. But issue with sidebar is critical. Can you please provide solution because I haven't use vue-portal.

~ Thanks

**Comment by Haroenv** [comment]
This happens because you gave a non-primitive value (array) as an inline prop. Vue can not tell the difference between those, and chooses to rerender the input, which loses its value. 

I fixed it by moving that to data: https://codesandbox.io/s/kw7nopwpjv

**Comment by jsinhSolanki** [comment]
Thank you so much @Haroenv Awesome :100:
