### ISSUE TITLE
ais-toggle-refinement label prop does not work

### ISSUE THREAD

**Issue by sandramedina** [algolia/vue-instantsearch#667]
**Bug 🐞**

### What is the current behavior?
When using the <ais-toggle-refinement /> component, passing a value to the "label" prop does not change the label of the filter.

### Make a sandbox with the current behavior

This issue is visible on the live demo linked to in the docs: https://v2--vue-instantsearch.netlify.com/stories/?selectedKind=ais-toggle-refinement&selectedStory=default&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs
<img width="248" alt="Screen Shot 2019-04-27 at 3 01 15 PM" src="https://user-images.githubusercontent.com/14882667/56855525-54c93d80-68fd-11e9-8b81-101ba967f279.png">

### What is the expected behavior?
Adding a value to the "label" prop should populate ais-ToggleRefinement-labelText with the correct label.

### Does this happen only in specific situations?
No

### What is the proposed solution?
Check for the regression that caused this bug and revert

### What is the version you are using?
"vue-instantsearch": "^2.0.1"

> Always try the latest one before opening an issue.

**Comment by francoischalifour** [comment]
This issue was fixed in #649 but we haven't released a new version since. We'll let know you when we do.
