### ISSUE TITLE
Multiple selected facets activated and updating results on button click

### ISSUE THREAD

**Issue by Artpan-fe** [algolia/vue-instantsearch#671]
Is there any way to use a built-in method of selecting multiple facets from one refinement list and activate update of results on click of button, like in Zalando site (https://www.zalando.de/damenschuhe/).

**Comment by Haroenv** [comment]
There's no built-in way of doing that, but you can create it by making a custom refinement list where you wrap everything in a form, and only call `refine` on the form's submit

**Comment by Artpan-fe** [comment]
@Haroenv is there any documentation of how to use that refine() method, where it is bound to? to store? to helper? and if the page is reloaded after form is sent and products are updated? Is there a chance to include this behavior as a feature in further vue instantsearch release? Cos there are lots of sites where filters are applied only on some event, and not on selecting each value

**Comment by Haroenv** [comment]
here's an example how to achieve this effect with refinement list https://codesandbox.io/s/7woyz8nlq1

**Comment by Artpan-fe** [comment]
@Haroenv Is there a way to do it in the scope of Vue InstantSearch v1?

**Comment by Haroenv** [comment]
Yes, but instead of reading from `state.items`, you should look at how the real RefinementList was made in v1 and import the data that way.

Hope that helped!
