### ISSUE TITLE
Passing custom template to loadMore slot

### ISSUE THREAD

**Issue by Sti3bas** [algolia/vue-instantsearch#675]
**Bug 🐞**

### What is the current behavior?

It's not possible to customise `Show more` button when passing custom template to `default` slot, because `loadMore` slot is nested inside it.

`loadPrevious` slot is fine.

https://github.com/algolia/vue-instantsearch/blob/dca88f90f82a5e9e620ae2cd12e5a3efc8475910/src/components/InfiniteHits.vue#L45

### Make a sandbox with the current behavior

https://codesandbox.io/s/vueinstantsearchapp-wypg0

### What is the expected behavior?

To work the same as "Show previous".

### Does this happen only in specific situations?

No.

### What is the proposed solution?

Move `loadMore` slot outside of `default` slot, the same way as `loadPrevious`.

### What is the version you are using?

2.2.1

**Comment by Haroenv** [comment]
This makes sense, but changing this is be a breaking change now 🤔 

Luckily there's an easy workaround, by defining the button within the `items` slot.

**Comment by alexcroox** [comment]
I just ran into this and was a major headache as loadPrevious slot was behaving as expected but loadMore was not when following the docs.

There is a workaround to use the old Vue `slot` syntax inside a default slot:

```
<AisInfiniteHits show-previous>
    <template #loadPrevious="{ isFirstPage, refinePrevious }">
        // Custom load previous button
    </template>

    <template #default="{ items, isLastPage, refineNext }">
        <ul>...results</ul>
 
        <!-- Have to use the old slot syntax because you can't nest #slotname. This is a workaround for vue-instant search layout of slots -->
        <div slot="loadMore">
            // Custom load more button
        </div>
    </template>
</AisInfiniteHits>
```

**Comment by Haroenv** [comment]
Sorry that this isn't fixed yet, but we can't change this without a major version @alexcroox

**Comment by alexcroox** [comment]
No worries, just posting a code example for anyone else that stumbles on the issue to save them time :)

**Comment by ArcoMul** [comment]
This would be good to note in the documentation

**Comment by Haroenv** [comment]
Where in the documentation would you have expected a note, and what would it say @ArcoMul ?

**Comment by ArcoMul** [comment]
I imagine here: https://www.algolia.com/doc/api-reference/widgets/infinite-hits/vue/#widget-param-loadmore

Something like:

>Note that when overriding the default slot, the loadMore slot also get overriden, in that case include the template code of the loadMore slot in the default slot and don't define a loadMore slot.

**Comment by Haroenv** [comment]
I've made an update to the documentation that adds a similar note to every default slot. This issue will automatically close once that is merged. Thanks for the suggestion @ArcoMul !
