### ISSUE TITLE
Nuxt demo crashes browser

### ISSUE THREAD

**Issue by fernando-mc** [algolia/vue-instantsearch#676]
**Bug 🐞**

### What is the current behavior?
I attempted to create the starter app described here:
https://community.algolia.com/vue-instantsearch/advanced/integrate-with-nuxt.html

When I tried this is crashed on me consistently when loading the search page.

### Make a sandbox with the current behavior

Visit /about in the browser of my page: https://codesandbox.io/s/codesandboxnuxt-zretx

### What is the expected behavior?
The page loads the demo mentioned in the community guide.

### Does this happen only in specific situations?
So far any time I load it it crashes and I can't debug. Locally or in code sandbox.

### What is the proposed solution?
Update docs to reflect how to create nuxt/vue-instantsearch app?

### What is the version you are using?
Latest version 2.2.1

**Comment by Haroenv** [comment]
An updated guide is available here, how did you find that docs? I thought we made them unaccessible via google. https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/vue/#with-nuxt

Let's say the old docs need a bigger banner

**Comment by fernando-mc** [comment]
@Haroenv Victory! Just got my app to start working finally.
