### ISSUE TITLE
How to retrieve a single `hit` by unique param (like objectID)

### ISSUE THREAD

**Issue by regenrek** [algolia/vue-instantsearch#682]
**Feature ⚡️**

Hey Everyone I'm just wondering if there is an easy approach to get a **single hit from an index by a unique param** (like objectID)?

This question was already [asked](https://github.com/algolia/react-instantsearch/issues/16#issuecomment-324565662) but maybe the answers are outdated and not specific for vue-instantsearch. So I give it a try here. 

### What is your proposal

* products.vue (parent)
https://localhost:3000/products/

```html
<template>
  <div>
    <ais-instant-search
      :search-client="searchClient"
      :index-name="algoliaIndex"
    >
        <div class="searchbox">
            <ais-search-box v-model="query" />
            <ais-configure
              :hitsPerPage="25"
              :restrictSearchableAttributes="['title']"
            />
          </div>
        </div>

        <div class="search-panel">
            <nuxt-child :key="$route.params.id" :item="item" />
        </div>
      </div>
    </ais-instant-search>
  </div>
</template>

<script>
import algoliasearch from "algoliasearch/lite";

const ALGOLIA_APP_ID = "<add>";
const ALGOLIA_SEARCH_ONLY_API_KEY = "<add>";
const ALGOLIA_INDEX_NAME = "<index>";

const searchClient = algoliasearch(
  ALGOLIA_APP_ID,
  ALGOLIA_SEARCH_ONLY_API_KEY
);

export default {
  data() {
    return {
      searchClient,
      algoliaIndex: ALGOLIA_INDEX_NAME,
      query: "",
    };
  }
};
</script>

```

* ProductSingle.vue (child)
https://localhost:3000/products/4

```html
<template>
  <div>
    <ais-hits>
      <template slot="item" slot-scope="{ item }">

<!-- this is a loop with all entries -> but there should only be 1 entry according to
$route.params.id -->

        Id: {{ item.objectID }}
        Title: {{ item.title }}
      </template>
    </ais-hits>
  </div>
</template>

<script>
import { AisHits } from "vue-instantsearch";

export default {
  components: {
    AisHits
  },
  props: {
    item: {
      type: Object,
      default: () => {}
    }
  }
};
</script>
<style></style>

```

Here is kind of a good example which I want to achieve:

https://appapp.io/us/genre=Games;has_iap=false;price=Paid/search?q=ss => (filtered view)
https://appapp.io/us/app/7-billion-humans/1393923918 => (single view - 1 hit)

### What is the version you are using?

2.2.1

> Always try the latest one before opening an issue.

**Comment by francoischalifour** [comment]
Thanks for opening the issue @regenrek!

The easiest solution for now would be to apply filters based on the URL with the [`ais-configure`](https://www.algolia.com/doc/api-reference/widgets/configure/vue/) widget.

```vue
<template>
  <!-- ... -->
  <ais-configure :filters="filters" />
  <!-- ... -->
</template>

<script>
  // ...
  export default {
    data() {
      return {
        // ...
        // `OBJECT_ID` can be computed based on `window.location.pathname`
        // or `$route.params.id` in your case.
        filters: `objectID:${OBJECT_ID}`,
      };
    },
  };
  // ...
</script>
```

If you don't want any filters to be applied when there's no `objectID` in the URL, the `filters` variable should be an empty string.

I made an example [on this sandbox](https://codesandbox.io/s/vue-instantsearch-product-page-52tic).

**Comment by regenrek** [comment]
Omg this was too easy - thank you @francoischalifour
