### ISSUE TITLE
Passing stateMapping functions doesn't work with AisInstantSearchSsr

### ISSUE THREAD

**Issue by DavidRouyer** [algolia/vue-instantsearch#683]
**Bug 🐞**

### What is the current behavior?
I'm using Nuxt and the AisInstantSearchSsr component. I'm trying to update the URL when the state changes (next/previous page, add/remove filter...). I don't know how I'm supposed to track the changes otherwise.
The only way to do that is to create my own `router` and `stateMapping` via the `routing` parameter, but the stateMapping functions (`stateToRoute`, `routeToState`) are not working.

### Make a sandbox with the current behavior
https://codesandbox.io/s/nuxt-lwpb3

### What is the expected behavior?
The AisInstantSearchSsr should process the content of `stateToRoute` and `routeToState` when passed via the `routing` parameter.

### What is the version you are using?
2.2.1

> Always try the latest one before opening an issue.

**Comment by samouss** [comment]
The SSR component is not responsible for the creation of the instance. Its only responsibility is to expose the created instance through the tree. You can provide the `routing` option directly to the `createInstantSearch` function.

```js
import { history as historyRouter } from "instantsearch.js/es/lib/routers";
import { simple as simpleMapping } from "instantsearch.js/es/lib/stateMappings";

createInstantSearch({
  searchClient,
  indexName: "instant_search",
  routing: {
    router: historyRouter(),
    stateMapping: simpleMapping()
  }
});
```

**Comment by DavidRouyer** [comment]
@samouss Thank you for your answer.
I didn't know that I have to pass the `routing` to the `createInstantSearch` method since it differs from the non SSR approach and I couldn't find any documentation or example for the SSR version.

**Comment by samouss** [comment]
Yes you're right. Inside the documentation we don't have (yet) a dedicated section for the API Ref of the SSR API. Once this section is available this approach will documented. Thanks for the feedback!
