### ISSUE TITLE
How to remove ais-state-results default content?

### ISSUE THREAD

**Issue by CaddyDz** [algolia/vue-instantsearch#686]
**Bug 🐞**

### What is the current behavior?

`<ais-state-results>` show a paragraph on how to use the component

### Make a sandbox with the current behavior

Template: https://codesandbox.io/s/vue-instantsearch-app-b9qey

### What is the expected behavior?

Don't show anything until the user starts typing and the query string is no longer empty

### Does this happen only in specific situations?

No

### What is the proposed solution?

Have an attribute that replaces auto-search="false" from previous version

### What is the version you are using?

```
"algoliasearch": "^3.33.0",
"vue": "^2.5.17",
"vue-instantsearch": "^2.2.1"
```

> Always try the latest one before opening an issue.

**Comment by tkrugg** [comment]
it looks like you just need to make sure the template is not empty when `query.length === 0`
You could for example add an empty div:

```vue
<div v-if="query.length === 0" />
```

Let me know if this helped. I'll close the issue for now but feel free to reopen.

**Comment by CaddyDz** [comment]
It works! thanks
Would be great to note this in the docs though

**Comment by ValeSauer** [comment]
This is not a complete replacement for `auto-search="false"`. `auto-search="false"` prevented the API call completely (thus saving bandwith and costs) while hiding the results does nothing but hide them. Did anyone find a solution that completely prevents API calls?

**Comment by Haroenv** [comment]
@ValeSauer you can follow this guide https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-requests/vue/
