### ISSUE TITLE
What would be the most straight forward way to initialise vue instant search with a query string:question

### ISSUE THREAD

**Issue by benjam-es** [algolia/vue-instantsearch#693]
Hi,

I was just wondering if someone could point me in the right direction please.

I'm looking for the simplest solution to use php variables to initialise my vue instant search - specifically the initial search value. I have previously initialised variables by storing them on the window and pulling them in, but can't find/remember the way I had previously accomplished this for the initial search query. (N.B lost uncompiled code).

**Comment by Haroenv** [comment]
I'm not fully  sure what you mean, but you're likely looking for the configure component: https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/vue/?language=javascript#apply-default-value-to-widgets

**Comment by benjam-es** [comment]
I want to have www.mysite.com/search?s=abc, and then have abc be pre populated into the vue instant search on that page.

**Comment by Haroenv** [comment]
Oh, in that case you will want: https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/#overview

**Comment by Haroenv** [comment]
I'll close this issue now, let me know if this didn't solve your issue
