### ISSUE TITLE
Sort not available to the routing

### ISSUE THREAD

**Issue by drpeck** [algolia/vue-instantsearch#699]
**The current sort is a binding with routing**

### What is your use case for such a feature?
Having the page number in the url is somewhat useless, when you allow sorting by a different index, if the index/replica is not also persisted through the url

### What is your proposal
The [stateToRoute and routeToState](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/?language=vue#user-friendly-urls) methods also scope a parameter that includes the current index.

### What is the version you are using?
2.1

**Comment by drpeck** [comment]
Sorry. There is a uiState.sortBy. My complex vue routing sync was masking it

**Comment by Haroenv** [comment]
Glad you found it!
