### ISSUE TITLE
Is it possible to watch state changes from connectGeoSearch mixin?

### ISSUE THREAD

**Issue by regenrek** [algolia/vue-instantsearch#700]
**Feature ⚡️**

### What is your use case for such a feature?

Hi I would like to ask if I can watch changes from `state.items` from
`connectGeoSearch` mixin?

Currently, I have no information about `state.items` see also [official docs tutorial](https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/geo-search/vue/) for context.

Currently, i need to create a workaround with `setTimeout` to get sure the `state.items` has been updated. Is there any better solution (subscription, watcher) to let us know when the state has been updated?

* Map.vue (child)
```
  methods: {
    async recenterMap() {
      console.debug("this.state.items:",this.state.items);

      // i need this in an real app to get sure the store has been updated
      await new Promise(resolve => setTimeout(resolve, 150));

      let geoloc = this.state.items.map(ds => [ds._geoloc.lat, ds._geoloc.lng]);
      this.map.fitBounds(geoloc);
    }
  }
```

* Index.vue (parent)

```
onSearch() {
      this.$refs.mjmap.recenterMap();
}
```

### What is your proposal

watcher, subscription ...

### Demo

I tried to rebuild this in a codesandbox with two different fakedata which should replace the current state with math.random (i know poor example): https://codesandbox.io/s/algolia-vue-instantsearch-v3-geosearch-recenter-m9clf

### What is the version you are using?

latest.

**Comment by Haroenv** [comment]
If you're in the component that has the connector enabled, you can definitely use a Vue watcher on `state.items`

**Comment by Haroenv** [comment]
I'm not exactly sure what the method `recenter`  is supposed to do, is it supposed to update the items on the map?

**Comment by regenrek** [comment]
> I'm not exactly sure what the method `recenter` is supposed to do, is it supposed to update the items on the map?

The method recenter is here to call leaflet methods like `setView` or `fitBounds` e.g. to move the view to the located markers. 

Use Case:

* If you do search within an location like `new york city` then the view should fly to the marker which has been found. `leaflet.setView`
* If you search for ice cream stores around `new york` the view should move to the area where the ice cream stores are located `leaflet.fitBounds`.

When I'm searching for ice cream stores around `Washington` the `store.items` get filled and the view will move to `washington`. Then I'm looking for ice cream stores around `new york` the store.items get populated with all stores around new york. __But this takes a while__ and so the `fitBounds` will still move to `washington` since the `store.items` aren't populated yet.

Using it watch (but not really my use case since I want to trigger it from another component)

## watch

```js
export default {
  watch: {
    ["store.items"]() { // pseudo...
    console.log("store.items has been updated");
    this.recenterMap();
    }
 },
 methods: {
    recenterMap(geoloc) {
      // call leaflet .fitBounds
      if (typeof geoloc === "undefined" && this.state) {
        geoloc = this.state.items.map(item => [item._geoloc.lat, item._geoloc.lng])
      }
      this.map.fitBounds(geoloc, args);
    }
  }
}
```

or better

## promise based

* search.vue
```js
import { onStoreItemsChanged } from "instantsearch.js/es/connectors";

export default {
  methods: {
    onSearchButtonClicked(e) {
          await onStoreItemsChanged() // maybe something like this...
          // now its safe that store.items has been updated and we can recenter the map
          // to the new geoloc
          this.$refs.mjmap.recenterMap();
    }
  }
}
```

* map.vue
```js
import { connectGeoSearch } from "instantsearch.js/es/connectors";

export default {
  mixins: [createWidgetMixin({ connector: connectGeoSearch })],
  mounted() {
    this.$nextTick(() => {
      // get leaflet mapObject
      if (typeof this.$refs.mapRef !== "undefined") {
        this.map = this.$refs.mapRef.mapObject;
        // center map to default _geoloc
        this.recenterMap(centerMapDefault);
      }
    });
  },
  methods: {
    recenterMap(geoloc) {
      // call leaflet .fitBounds
      if (typeof geoloc === "undefined" && this.state) {
        geoloc = this.state.items.map(item => [item._geoloc.lat, item._geoloc.lng])
      }
      this.map.fitBounds(geoloc, args);
    }
  }
}
``

**Comment by Haroenv** [comment]
Is there a reason `watch: { 'state.items' ...` does not work for you?

**Comment by regenrek** [comment]
Thanks for your answer. Yeah I ended up using watch. Works for me

```
    "state.items"() {
      if (this.state.items.length > 0) {
        this.recenterMap();
      }
      console.debug("state.items updated", this.state.items);
    }
```
