### ISSUE TITLE
v2 - arrow keys not working

### ISSUE THREAD

**Issue by meSingh** [algolia/vue-instantsearch#701]
### What is the current behavior?
Everything else works fine but for some reason I'm not able to use arrow keys to move selection up/down.

### Make a sandbox with the current behavior
https://codesandbox.io/s/vue-instantsearch-app-pblct

### What is the expected behavior?
I should be able to move focus between elements using arrow keys. 

### Does this happen only in specific situations?
It worked when I initially started implementing autocomplete but when I was ready with the functionality it just stopped working at some point. I tried removing bits and pieces of code but nothing works.

**Comment by Haroenv** [comment]
Hi @meSingh, the default autocomplete component does not move focus, to avoid being too opinionated (there are many options, especially on how to work together with the mouse). I think you likely were using vue-autosuggest before, which has focus built-in: https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/Vue%20InstantSearch/autocomplete-results-page

**Comment by meSingh** [comment]
Thanks @Haroenv for your help, I tried it and it seems to be working with autosuggest. 

The problem here is that autosuggest can't handle routes and other state changes which make use of ais-search-box more lucrative. I'm going to stick with it for now. Use of keyboard is a very nice to have feature but not that huge to stop my delivery. 

Closing this thread for now.
