### ISSUE TITLE
cannot setSettings in vue

### ISSUE THREAD

**Issue by mateuszgwozdz** [algolia/vue-instantsearch#704]
I would like to use `optionalFilters` https://www.algolia.com/doc/api-reference/api-parameters/optionalFilters/?language=javascript for which I need to set `attributesForFaceting` but there's no documentation on how to do this. https://www.algolia.com/doc/api-reference/api-parameters/attributesForFaceting/

1. This throws an error 400 Unknown parameter: attributesForFaceting
```
<ais-configure
  :hitsPerPage="8"
  v-bind="searchParameters"
  attributesForFaceting="brand"
/>
```

2. trying to pass it through search client parameters doesn't work 
```
searchClient: algoliasearch(
  'ABCDEFGH',
  '01234567890123456789',
  {attributesForFaceting:'brandName'}
),
```
3. I added an `ais-refinement-list` component with the attribuets `brandName`. Nothing
4. I set the `attributesForFaceting` in the dashbaord configuation https://www.algolia.com/apps/VDJXSOGAAQ/explorer/configuration/INDEXNAME/facets Still cannot get results to work with optionalFilters

These are my optional filters:
```
searchParameters: {
  optionalFilters: 'brandName:SOMEBRANDNAME'
},
```

No hits fullfill the criteria of `brandName:SOMEBRANDNAME` even though there's many entries in my indice that have should.

The same set up works with official codesandbox.io example `instant_search`

**Comment by Haroenv** [comment]
Hi @mateuszgwozdz, methods which change the index require a "write" API key, as contrast with settings which don't change the index. You can set `attributesForFaceting` via the dashboard, or via a node (or other language) script, but not frontend

**Comment by mateuszgwozdz** [comment]
Please refresh, I edited the comment. I have tried that too

**Comment by mateuszgwozdz** [comment]
<img width="821" alt="Screenshot 2019-07-30 at 10 06 11" src="https://user-images.githubusercontent.com/7168481/62111826-c2e12000-b2b1-11e9-92c9-521b61f6487c.png">

**Comment by Haroenv** [comment]
this happened because you changed the "sorting", putting sort-by before the basic  textual  filters, and thus always tie-breaking on "sort-index", and never using the regular sorts 

<img width="636" alt="Screenshot 2019-07-30 at 10 18 26" src="https://user-images.githubusercontent.com/6270048/62112642-60891f00-b2b3-11e9-8198-0c994f4b63d8.png">

I have fixed that for you, and it works as expected now

**Comment by mateuszgwozdz** [comment]
Yes, it works now as expected! Thank you!

**Comment by Haroenv** [comment]
For future reference, issues like this are best debugged by looking in the dashboard, where you can see the "trophy", which will explain why records are sorted as they are. There you can see that in your previous case, the ranking always came down to "sortIndex", which shouldn't be the tie-break, so it should come after other criteria.

**Comment by mateuszgwozdz** [comment]
I followed the trophy at the beginning, before setting `optionalParameters`, and then spent hours trying to solve this issue. Maybe ranking should never overwrite other paramters, or there could be a warning message displayed. I really tried my best before posting here
