### ISSUE TITLE
change algolia server url to my own servers

### ISSUE THREAD

**Issue by moosapour-arash** [algolia/vue-instantsearch#708]
hi,this is not a bug or a feature request .
my service have customers in a location that algolia servers are blocked and unreachable from their browsers.
so vue instant search wont work when it can not reach the algolia servers.
i want to swap the default algolia urls with a nginx proxy pass server address , so instant search sends the whole request to proxy server, and then proxy send to algolia to workaround the blockage 
i know i can use the [Backend Search](https://www.algolia.com/doc/guides/building-search-ui/going-further/backend-search/in-depth/backend-instantsearch/vue/) and actually im doing this at the moment to keep my service up, but this approach is booting the whole framework(laravel) for every single customer interaction with instant search , so i prefer a hackish way to use the proxy pass solution because its a lot more light weight
 **so can anyone please point me where in the source code i can modify this url ?**

**Comment by Haroenv** [comment]
You could change the url via the “hosts” option of the search client, but I don’t see how that would give you any less traffic

**Comment by moosapour-arash** [comment]
sorry i edited the question , to be more clear 🙏🏻

**Comment by eunjae-lee** [comment]
Hi there,

```js
  data() {
    return {
      searchClient: algoliasearch(
        'B1G2GM9NG0',
        'aadef574be1f9252bb48d4ea09b5cfe5', 
        { /* here */ } 
      ),
    };
  },
```

You can check the following URLs:

- https://www.algolia.com/doc/api-client/getting-started/instantiate-client-index/#client-options
- https://github.com/algolia/algoliasearch-client-javascript/blob/develop/src/AlgoliaSearchCore.js#L27

**Comment by moosapour-arash** [comment]
thank you @eunjae-lee ,the second link you provided was a great help , now i can pass requests from vue client to my proxy servers
im closing this
