### ISSUE TITLE
Change in component data erases hierarchicalMenu filters

### ISSUE THREAD

**Issue by paulden** [algolia/vue-instantsearch#709]
**Bug 🐞**

Hello everyone, thanks a lot for your work on this package, it's been great so far. However, I have been having trouble lately using Algolia components in a Vue component while modifying a `data` from the component.

### What is the current behavior?

I am using an `ais-hierarchical-menu`, when selecting a value from this menu, the results are filtered as expected and the URL is updated. However, I want my user to be able to toggle another panel so in my Vue component I have a `isPanelVisible` in my `data()` and clicking on a button causes this attribute to be switched (`this.isPanelVisible = !this.isPanelVisible`).

When clicking on this button and modifiying this data, part of the DOM is re-rendered and it seems that Algolia unmounts and re-adds the widgets, loosing the filter state (and thus cleaning the URL). In the end, my filters have been erased.

### Make a sandbox with the current behavior

Here is a sandbox based on the default Vue app provided in this repository : https://codesandbox.io/s/e518n

To reproduce the issue:
- Select a category (e.g. Appliances > Dishwasher) : filters and URL are set properly.
- Click on the button `Something: false`, which triggers the change of `something` attribute.
- Filters and URL are cleaned.

### What is the expected behavior?

Behavior expected:
- Select a category (e.g. Appliances > Dishwasher) : filters and URL are set properly.
- Click on the button `Something: false`, which triggers the change of `something` attribute.
- Filters and URL are kept as originally.

### Does this happen only in specific situations?

The issue does not seem to arise for other components.

### What is the proposed solution?

I am not sure how to tackle this. Currently, we found an extremely hacky workaround by storing the arguments used in the `refine` in a variable and re-using them after switching the `something` variable.

I may be missing something else or doing something wrong, let me know if that's the case or if you have another strategy.

### What is the version you are using?

Here are the versions from the `package.json` (see the sandbox):
```    
    "algoliasearch": "^3.33.0",
    "instantsearch.css": "^7.1.1",
    "instantsearch.js": "^3.6.0",
    "vue": "^2.6.7",
    "vue-instantsearch": "^2.3.0"
```

I hope I provided enough information (if not, let me know). 

Again, thanks a lot for you work, guys, the components have been quite easy to use so far.

**Comment by Haroenv** [comment]
This is a longstanding problem which we have tried many methods to fix, but haven't yet found a good solution. A simple workaround for now is avoiding any inline props which can't be referentially equal (like arrays). See here a fixed version: 

https://codesandbox.io/s/default-theme-hwqkz

**Comment by Haroenv** [comment]
Is this using the latest version of Vue InstantSearch? We fixed an issue with routing + rerendering hierarchical menu in the very latest minor: https://github.com/algolia/vue-instantsearch/pull/705

**Comment by paulden** [comment]
Thanks a lot for your help, appreciate it! That has indeed fixed this issue! :)

I'm closing the issue if that's ok for you.
