### ISSUE TITLE
serialize and restore state on demand

### ISSUE THREAD

**Issue by WavyWalk** [algolia/vue-instantsearch#714]
**Feature ⚡️**

serialize and restore state on demand

### What is your proposal:
  change in the behavior:

### What is the version you are using?

2.4.0

Would be nice to have something like `.saveSerializedState()` and `.replaceState(serializedState)` on `ais-instant-search`'s scope.

Or is there such thing already available?

**Comment by tkrugg** [comment]
It's not clear whether the state of the query or the results you need.
- If it's the state of the results (contains hits, nb of hits, etc) it's exposed by this widget https://www.algolia.com/doc/api-reference/widgets/state-results/vue/
- If it's the state of the query (contains value of the search box, the refinements), it's exposed in the routing `write` function. A little hacky but the code is small. Here are the steps:

step 1: add routing
```vue
<script>
import { history as historyRouter } from 'instantsearch.js/es/lib/routers';
import { simple as simpleMapping } from 'instantsearch.js/es/lib/stateMappings';

const router = historyRouter();
const stateMapping = simpleMapping();

export default {
  data() {
    return {

      routing: {
        router
        stateMapping ,
      },
    };
  },
};
</script>

<template>
    <ais-instant-search :routing="routing"> ... </ais-instant-search>
</template>
```

step 2: override the write method of router
```js
const router = historyRouter();
const originalWrite = router.write;
router.write = queryState => {
  console.log(queryState);
  originalWrite.apply(router, queryState);
};

```

Full example is here: https://codesandbox.io/s/vue-instantsearch-v2-starter-wd9yo
I hope it helps.

**Comment by WavyWalk** [comment]
@tkrugg Thanks pall, you're awesome. But is there any way to restore the retrieved hits and render them, e.g. fully serialize them and cache related state, say put it in all in store, and rerender the whole thing once again?

**Comment by tkrugg** [comment]
yes it's possible. As I said at the end, you just need to do the same thing on the `read` method.
All methods are documented here: https://www.algolia.com/doc/api-reference/widgets/instantsearch/js/#widget-param-routing
