### ISSUE TITLE
Support float values in <ais-rating-menu>

### ISSUE THREAD

**Issue by Meschreiber** [algolia/vue-instantsearch#715]
**Feature ⚡️**

### What is your use case for such a feature?

Currently only integers are supported so that if the widget is clicked upon, any records with float values are lost.

### What is your proposal

Support float values without having users add an additional integer version.

### What is the version you are using?

2.x

**Comment by keyuls** [comment]
@Meschreiber can you also add same issue in the angular plugin?
https://github.com/algolia/angular-instantsearch

**Comment by tkrugg** [comment]
For anyone stumbling on this issue: it's worth nothing that it's currently possible with a custom range-input widget (for both Vue InstantSearch and Angular InstantSearch)
https://www.algolia.com/doc/api-reference/widgets/range-input/vue/#customize-the-ui.

**Comment by hamblin** [comment]
I'm seeing the same issue with vanilla InstantSearch.js (v3.4.0) and don't see an issue open in that repo.  Probably should add one there too.  Any record with float values for rating are not shown.

**Comment by Haroenv** [comment]
This has been solved since https://github.com/algolia/instantsearch.js/pull/4611 I believe
