### ISSUE TITLE
Initial values for components

### ISSUE THREAD

**Issue by MrRossBennett** [algolia/vue-instantsearch#717]
Hello all

When our `<ais-configure>` component mounts we pass it a bunch of default filters that are hidden from the user and are always in place. 

<ais-configure :filters="defaultFilters" />

We would also like to set a bunch of initial values in some of the `vue-instantsearch` components. For example, the `<ais-refinement-list>` component would have some values already checked. The user would then be able to check/uncheck as usual in order to filter the search results.

What's the recommended way to do this? I've seen this sort of suggestion, but I'm not convinced:

```routeToState: (routeState) => {
  if(!routeState.foo) {
    routeState.foo = this.bar
  }
```

Thanks!

**Comment by Haroenv** [comment]
For refinement list specifically you need to use disjunctive facets refinements in configure. This is something which isn't clear enough in the doc, and we long-term want a better solution. The workaround now is:

```vue
<template>
<ais-configure disjunctive-facets-refinements.camel="" />
<ais-refinement-list />
</template>

<script>
</script>For refinement list specifically you need to use disjunctive facets refinements in configure. This is something which isn't clear enough in the doc, and we long-term want a better solution. The workaround now is:

```vue
<template>
  <ais-configure
    disjunctive-facets-refinements.camel="disjunctiveFacetsRefinements"
  />
  <ais-refinement-list attribute="myAttribute"/>
</template>

<script>
export default {
  data() {
    return {
      disjunctiveFacetsRefinements: {
        myAttribute: ['default', 'values']
      }
    }
  }
}
</script>
```

**Comment by MrRossBennett** [comment]
Thanks @Haroenv 

And how would we apply the same to numeric components and the range-slider component? Can't seem to find reference to this in the docs.

`numericFacetsRefinements`?
`numericRefinements`?

**Comment by Haroenv** [comment]
For numeric refinements it's both numeric & disjunctive: 

```
 "numericRefinements": {
    "price": {
      ">=": [
        3
      ],
      "<=": [
        4
      ]
    }
  },
```

For future reference, I made a small debugger to see which state is currently applied, so it can be used with configure: https://codesandbox.io/s/vue-instantsearch-app-hk54z

**Comment by MrRossBennett** [comment]
.Ah, cool, thanks @Haroenv 

And will `numericRefinements` accept a nested array? How would that work with the above? I see in the docs:

```If you want to use a disjunction (OR), use a nested array.```

**Comment by Haroenv** [comment]
This should work, but the component might not take it in account, since the native component can't do it

**Comment by MrRossBennett** [comment]
Ah, right, I see. Thanks @Haroenv. 

Is there a way to set the `currentRefinement` of the `ais-range-input` when it mounts. If I pass an object to `numericRefinements` as suggested above, it changes the `range` rather than actually setting the value. 

For example, I'd like the range to always be between 10 and 100, but want the value to be 50 on mount and that be reflected in the search results. Then the user can freely move the slider between 10 and 100 to change the results.

**Comment by Haroenv** [comment]
the way i described seems to work for me: https://codesandbox.io/s/vue-instantsearch-v2-starter-1rlvo

**Comment by MrRossBennett** [comment]
Ah, so it does. Thanks @Haroenv. For some reason our range was `min:0, max: 0`.

Last one... is there anything that has to be done to the routing settings? For example, if I set the price to be 100 via `numericRefinements` and then user changes the min value to 50 this is reflected in the url (`range%5Bprice%5D=50%3A`) which is great.

However, when the page is refreshed the 100 value gets added back in as well as the 50:

`range%5Bprice%5D=100%2C50%3A`

Is there a way to stop that happening? 

We're using:

``` routing: {
         router: historyRouter(),
         stateMapping: simpleMapping()
}```

**Comment by Haroenv** [comment]
You could read from the URL, and only add the configure if the value isn't added already

**Comment by Haroenv** [comment]
The correct way to initialise Vue InstantSearch refinements is either through routing or through initialUiState. If you have any complicated custom logic, that usually would fit in the parseURL of router.
