### ISSUE TITLE
ais-hits reset when my refinements is less than hits-per-page

### ISSUE THREAD

**Issue by paulofellix** [algolia/vue-instantsearch#719]
My hits-per-page is default 15, but when i use a refinement that results is less than 15, ais-hits "reset" and get all dataset again, other example happens when my refinements has 20 results, the first page will show 15 hits, the second page should show another 5 hits, but component again "reset" and get all dataset.

when then refinements results is less than 15 the checkbox not keep checked, it's as if all components are reset

**Comment by Haroenv** [comment]
Can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch). Thanks!

**Comment by paulofellix** [comment]
@Haroenv, I redid using a simple page and the error did not happen, I will try to do it again from scratch, anyway I will close this issue. Thanks :)
