### ISSUE TITLE
Proper way to highlight an array?

### ISSUE THREAD

**Issue by wassim** [algolia/vue-instantsearch#720]
Hi!

I'm wondering if there was a proper way to highlight an array of strings? I haven't found anything in the docs so atm I'm using some dirty code:

```
<ul>
  <li v-for="tag in item._highlightResult.tags">
    <span v-html="tag.value"></span>
  </li>
</ul>
```

Is there a way to use the `<ais-highlight>` component to iterate trough an array?

**Comment by eunjae-lee** [comment]
Hi there,

You can iterate and highlight the items in an array.

```js
<ais-highlight
  :hit="item"
  :attribute="'tags.' + index"
  v-for="(tag, index) in item.tags"
  :key="tag"
/>
```

You can find a working example here: https://codesandbox.io/s/vue-instantsearch-app-w5ed0
Let me know how it goes!

**Comment by wassim** [comment]
@eunice you're awesome, thanks!
