### ISSUE TITLE
I get many “indexName is not valid” after adding ais-sort-by component

### ISSUE THREAD

**Issue by msassa** [algolia/vue-instantsearch#723]
**Bug 🐞**

### What is the current behavior?
After adding the sort-by component, I start getting errors like this 'AlgoliaSearchError: indexName is not valid' for all the place.
After changing the way to import modules, I change from `'ais-mile-range-slider': () => import(/* webpackChunkName: "js/chunk/aisMileRangeSlider" */'./aisMileRangeSlider.vue'),
'ais-price-range-slider': () => import(/* webpackChunkName: "js/ch` to `'ais-mile-range-slider': require('./aisMileRangeSlider.vue').default,` I thought it had been fixed ... but not. I'm still have two fields that show that error when I change it.

You can see my ticket in algolia community
https://discourse.algolia.com/t/i-get-many-indexname-is-not-valid-after-adding-ais-sort-by-component/8502/5

### Make a sandbox with the current behavior
I can't duplicate this in codesandbox

### What is the version you are using?
"algoliasearch": "^3.32.1",
"instantsearch.js": "^3.6.0",
"vue-instantsearch": "^2.3.0",

**Comment by Haroenv** [comment]
Does it make a difference if you add `default: true` to the main index in the sort by?

Another thing to check is also if there isn't an infinite loop created, this can be caused by having data inline in the template, if you replace the inline array, with one in `data`, does that change anything?

**Comment by msassa** [comment]
YES ... thanks @Haroenv 
I made both changes, put the default: true, and remove the array inline.
This works.
Thank you so much ...
