### ISSUE TITLE
Problem with router history

### ISSUE THREAD

**Issue by marekalgoud** [algolia/vue-instantsearch#724]
**Bug 🐞**

### What is the current behavior?
On the firt load of the page, the history is filled with the same page two times. It only occurs if I add the ais-state-results in the page.

### Make a sandbox with the current behavior

I've reproduced the issue here :
https://codesandbox.io/embed/vue-instantsearch-app-0lhzx

As you can see, the back button is available and lead to the same page

### What is the expected behavior?
The history should not contains the same page twice.

### What is the version you are using?

"vue": "^2.6.10",
"vue-instantsearch": "^2.5.0",

**Comment by Haroenv** [comment]
This issue is very complicated to solve, I think it's a duplicate of https://github.com/algolia/vue-instantsearch/issues/589, can you try  the "workarounds" mentioned there?

**Comment by Haroenv** [comment]
You can work around this issue by making a custom router (not historyRouter), and doing a conditional check to see the URL is the same as the currrent one, but with `?` added. In that case you can choose not to push the URL. This is in fact an issue we have recently fixed upstream (i was confusting it with #589 which is indeed differently). You can check the solved implementation for that router here: https://github.com/algolia/instantsearch.js/pull/4130

**Comment by marekalgoud** [comment]
I managed to make it works as wished : I copied the instantsearch.js/es/lib/routers/history.js file and add a hack around the pushState function. It's a bit ugly but it works :)

Thanks for your help.

**Comment by Haroenv** [comment]
thanks! for anyone else seeing this, can you share your modifications?

**Comment by marekalgoud** [comment]
Hello,

here my ugly hack : 

I replaced the following code

``` 
this.writeTimer = window.setTimeout(function () {
            setWindowTitle(title)
            window.history.pushState(routeState, title || '', url)
            _this.writeTimer = undefined
          }, this.writeDelay)
```
by

```
if ((window.location.href.indexOf('?') > -1 || url.substr(-1) !== '?') && window.location.href !== url) {
          this.writeTimer = window.setTimeout(function () {
            setWindowTitle(title)
            window.history.pushState(routeState, title || '', url)
            _this.writeTimer = undefined
          }, this.writeDelay)
  }
```
There is still an issue with the history when we load the page with params, but it almost never occurs when navigating on the website.
