### ISSUE TITLE
ais-hierarchical-menu: not able to keep root menu when clicking on a menu item

### ISSUE THREAD

**Issue by tfossoul** [algolia/vue-instantsearch#728]
Hi

I am trying to get the same behavior than the one you can see on the default example you can find [here](https://vue-instantsearch.netlify.com/stories/?selectedKind=ais-hierarchical-menu&selectedStory=default&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel) which is: I wanna keep seeing all the root menu and be able to navigate on it even if I clicked on several sublevel of my menu.
What is excepted:
![image](https://user-images.githubusercontent.com/7678234/66126906-cfa02e00-e5ea-11e9-8229-5a8c2355349c.png)

What I got:
On the left: the entire root level of menu: "products", "products1".
![image](https://user-images.githubusercontent.com/7678234/66127117-463d2b80-e5eb-11e9-8165-3f0f29f22045.png)
On the right: "products" menu disappear when I click on the "products1".

Thanks in advance for your help,

Thomas

### What is the version you are using?

"vue-instantsearch": "^2.5.0",

**Comment by Haroenv** [comment]
@tfossoul could you give the code you are using that displays this?

**Comment by samouss** [comment]
Like @Haroenv mention, an example always helps to better understand the problem. We provide a template to avoid the boilerplate part. You can find it on [CodeSandbox](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch). Don't hesitate to take a look at [the source code of our default implementation](https://github.com/algolia/vue-instantsearch/blob/master/src/components/HierarchicalMenu.vue) if it can help.

**Comment by tfossoul** [comment]
Sorry guys I found the problem. It is something on my proxy. thanks for your time.
