### ISSUE TITLE
Compatibility with core-js@3 (ex. using Nuxt)

### ISSUE THREAD

**Issue by LuXDAmore** [algolia/vue-instantsearch#733]
**Feature ⚡️**

### What is the current behavior?

The build is missing some required dependencies:

> Cannot find module 'core-js/modules/web.dom.iterable'

> core-js/modules/es6.function.name in ./.nuxt/client.js, ./node_modules/instantsearch.js/es/connectors/breadcrumb/connectBreadcrumb.js and 11 others
> core-js/modules/es6.number.constructor in ./node_modules/instantsearch.js/es/connectors/current-refinements/connectCurrentRefinements.js, ./node_modules/instantsearch.js/es/connectors/hits-per-page/connectHitsPerPage.js and 4 others
> core-js/modules/es6.object.freeze in ./node_modules/vue-instantsearch/dist/vue-instantsearch.esm.js
> core-js/modules/es6.object.keys in ./.nuxt/index.js, ./node_modules/instantsearch.js/es/connectors/configure/connectConfigure.js and 21 others
> core-js/modules/es6.object.set-prototype-of in ./node_modules/instantsearch.js/es/lib/InstantSearch.js, ./node_modules/instantsearch.js/es/lib/routers/history.js

##### Links
[Codesandbox](https://codesandbox.io/s/nuxt-algolia-core-js3-z1hhm) and [NUXT, since v2.6.0, core-js documentation](https://nuxtjs.org/guide/release-notes#v2.6.0)

### Does this happen only in specific situations?

It happen only with `@babel/runtime-corejs3` and `core-js@3`, everything goes fine with  `@babel/runtime-corejs2` and `core-js@2`.

### What is the version you are using?

- "@babel/runtime-corejs3": "7.6.3";
- "algoliasearch": "3.35.1";
- "core-js": "3.3.1";
- "nuxt": "2.10.1";
- "vue-instantsearch": "2.5.0".

**Comment by Haroenv** [comment]
You closed the issue, do you mean by this you solved everything?

**Comment by LuXDAmore** [comment]
Yes, i've fixed it, there's a _broken package-lock.json_ , so it's probably related to something else, sorry for the inconvenience.

I'm unable to fix it in the `codesandbox`, but in _localhost_ everything goes fine.
