### ISSUE TITLE
Ais-infinite-hits with show previous="true" prop doesn't update page in the route

### ISSUE THREAD

**Issue by marekalgoud** [algolia/vue-instantsearch#736]
**Bug 🐞**

### What is the current behavior?

With ais-inifinite-hits components, configured with :show-previous="true", when user clicks on the button "show previous" the current page is not updated in the route (but the previous product are loaded correctly). 
If I console.log the props sent to the stateToRoute function of the router, the "page" prop is undefined.

### What is the expected behavior?

The page param should be sent to the stateToRoute function when the refinePrevious function is called

### Does this happen only in specific situations?

It happens with simpleMapping or custom Mapping

### What is the version you are using?

vue-instantsearch: 2.6.0
algoliasearch:  3.35.1

**Comment by eunjae-lee** [comment]
Hi there,
thanks for reaching out to us.
Could you give us a reproducible example?
It will be very helpful for us to tackle this issue.

You can use this [basic template](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch), or [this sandbox](https://codesandbox.io/s/vue-instantsearch-app-mrelv) which I made trying to reproduce your issue.

Thanks.

**Comment by marekalgoud** [comment]
Hi @eunjae-lee ,

Thanks for your feedback.
I reproduce the issue on your sandbox (https://codesandbox.io/s/vue-instantsearch-app-mrelv) : If I load the page=2 directly and then click on the "gimme previsous page" button, the url is not updated (I still have page=2 in the route).

**Comment by francoischalifour** [comment]
This is the expected behavior that we decided to go for when implementing this feature. The reasoning is that even though you loaded previous pages, the _last_ page (in terms of highest number) loaded remains 2.

Would you rather expect another behavior?

**Comment by marekalgoud** [comment]
Hi @francoischalifour,

I understand your answer, but I think it's more logic that the prev button behaves like the next button (changing the page param). Anyway, it's not a big deal if it stays like this.
By the way, it would be great for SEO purpose to have the generated url in the scope attribute of the ais-infinite component :)
