### ISSUE TITLE
Clear Refinements outside of render template

### ISSUE THREAD

**Issue by alexcroox** [algolia/vue-instantsearch#741]
### What is your use case for such a feature?

I'd like more programmatic control over clearing the search filters. I can currently add a "reset filters" button inside `AisClearRefinements`, but I'd like to perform the same action elsewhere in the parent component, and not based on the user clicking a button themselves. 

Is this currently possible and I'm just missing the API method?

**Comment by Haroenv** [comment]
By outside of a parent method, do you mean outside of the `ais-instant-search` component? If so, then unfortunately I don't think there's a hidden API. All I can think of that would be usable for you is either:

- clear refinements
- transformItems on clear refinements
- setting the URL if you're using routing
- Vue portal to move where in the tree an item is

Can you clarify somewhat what your use case is, preferably with a reproduction? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch). Thanks!

**Comment by alexcroox** [comment]
Thanks for the ideas. My solution in the end was to :key the ais-instant-search with a data value which I could change when I needed to force the re-render. This seemed to work well in clearing the params.
