### ISSUE TITLE
Router in Wordpress integration using Vue-instantsearch

### ISSUE THREAD

**Issue by alishanster** [algolia/vue-instantsearch#746]
**Bug 🐞**

### What is the current behavior?
Currently when I pass an object to ```:routing="routing"```

with 

```
routing: {
	stateMapping: {
		stateToRoute(uiState) {
			return {
				query: uiState.query,
				models:
				   uiState.refinementList &&
				   uiState.refinementList.model &&
				   uiState.refinementList.model.join('~'),
				page: uiState.page
				};
			},
		routeToState(routeState) {
			return {
				query: routeState.query,
				refinementList: {
				    model: routeState.models && routeState.models.split('~')
				},
				page: routeState.page
				};
		}
	},
},
```
I get an error in console
```[Vue warn]: Invalid prop: custom validator check failed for prop "routing".``` 
And page freezes when I try to sort hits according to ```:around-lat-lng.camel="aroundLatLng"``` and ```:around-radius.camel="searchRadiusToMiles ? searchRadiusToMiles : ''  "```

I get the same error in console when I put ```:routing="true"```

My use case here is pretty much completely solved in stateMapping, so I don't really need a 'router' key. However it still gives a console error if I don't use it. 

Eventually I still get console errors if I try to put ``` router: history()```

Note: I use WordPress integration and enqueued instantsearch.production.min.js, algoliasearchLite.min.js and vue-instantearch.js in my function.php
### Make a sandbox with the current behavior

https://codesandbox.io/s/vue-instantsearch-app-30cdw

### What is the expected behavior?
No errors in console.
[Guide](https://www.algolia.com/doc/api-reference/widgets/instantsearch/vue/#widget-param-routing) says that object is excepted if if has either of keys (router or stateMapping)
### Does this happen only in specific situations?
Happens always
### What is the version you are using?
Must be v3, as I started development in the beginning of October 
> Always try the latest one before opening an issue.

**Comment by Haroenv** [comment]
Hmm, that's a good point, the vue check seems to be too strict, and should allow _either_ of the keys to be set, and not require them both.

**Comment by alishanster** [comment]
On sandbox everything works if I put ``` router:history()``` and import history from instantsearch.js library. However on my WordPress I have instantsearch.prod.min.js file enqueued  and not sure if I can import separately one function from it. Is there some sort of work around?

**Comment by Haroenv** [comment]
if you have the UMD loaded you should be able to read it from the global like this: `instantsearch.routers.history()`. Here's a demo with just InstantSearch loaded via umd https://codesandbox.io/s/instantsearchjs-app-ygwdi

**Comment by Haroenv** [comment]
This is an old issue, so I'll assume that it has been fixed in the mean time. If you have more issues, please open a new issue and give a reproduction. Thanks
