### ISSUE TITLE
Add search parameter to the query with ais-autocomplete

### ISSUE THREAD

**Issue by velinapetrova** [algolia/vue-instantsearch#747]
Hello all, 
I am using the ais-autocomplete component to perform multi-index search and pull results from the Algolia server. I would like to add a search parameter that will only return me a certain subset of results. 
For example I only want to get results that have been classified as published. 
(all my results contain the attribute `published` that has value of true or false) 
I want to add the search parameter behind the scenes. I don't want to tie it up to the UI and the user doesn't need to know about it. 
How can I achieve that with vue-instantsearch?

**Comment by Haroenv** [comment]
Hi Velina,

I'm not too sure where you want this parameter to apply, but the widget [configure](https://www.algolia.com/doc/api-reference/widgets/configure/vue/) is for this purpose. You pass it as a child of the `ais-instant-search` you want the parameters to apply. In this case that would be ``<ais-configure :filters="`published:${true}`" />``.

I'll close this issue, but will reopen if something is unclear. If so, please attach a sandbox of your current situation. We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch). Thanks!
