### ISSUE TITLE
Site crashes when using :routing and :around-lat-lng.camel with :around-radius.camel

### ISSUE THREAD

**Issue by alishanster** [algolia/vue-instantsearch#748]
**Bug 🐞**

### What is the current behavior?
Page becomes irresponsive when values that are passed to ```:around-lat-lng.camel="aroundLatLng"``` or ```:around-radius.camel="searchRadiusToMiles ? searchRadiusToMiles : ''"```  change dynamically (through v-model) and ```:routing="routing"``` is used. 

I have an input: `<input class="noSpinner" type="number" v-model.lazy="zip" />` 
and select 
  ```
  <select v-select v-model="radius">
		<option value="25">Up to 25 miles</option>
		<option value="50">Up to 50 miles</option>
		<option value="100">Up to 100 miles</option>
		<option value="200">Up to 200 miles</option>
		<option value="300">Up to 300 miles</option>
		<option value="400">Up to 400 miles</option>
		<option value="500">Up to 500 miles</option>
		<option value="1000000">Any distance</option>
	</select>
```
```zip``` value is watched and returns correct lat and lng that is passed to ```aroundLatLng```

and ``` radius``` is computed (turns miles to meters) and new value is passed to ```searchRadiusMiles```

I use all that to filter records according to input zip number and search radius. All that works great without routing.

### Make a sandbox with the current behavior
Could not use demo records, need _geoloc in them. 
However here is the link to my [development](https://myelectric.stylemix.live/listings/)

### What is the expected behavior?
Page not crashing when ```:around-lat-lng.camel``` or ``` :around-radius.camel``` values changed while using ```:routing```

### Does this happen only in specific situations?
Happens always
### What is the version you are using?
v4 and v3, tried on both of them
> Always try the latest one before opening an issue.

**Comment by Haroenv** [comment]
You can use the `airbnb`  index on the demo application, would definitely like to see this on a sandbox

**Comment by alishanster** [comment]
Alright, after playing around with my development and sendbox I think I found out why my site keeps crashing.. 
For some reason if ```:around-lat-lng.camel``` or ```:around-radius.camel``` changes dynamically Algolia makes extra two requests for every refinement widget that has a ```:sort-by``` attribute. 

Please take a look at [this sendbox](https://codesandbox.io/s/vue-instantsearch-app-wt0se), here whenever you type in zip code (eg. 75202 for Dallas), you get hits closest to zip. However If you look at the number of requests, it is like 6 or 8. If you remove```:sort-by``` attribute from one of the refinement widgets, number of requests in network will be two less for every removed attribute. 

In my use case I have a lot of refinement widgets, almost all of them are using ```:sort-by``` attribute and are customized for my needs.

**Comment by Haroenv** [comment]
Ah, I think I misunderstood what was going on initially, this is a case of #575 and related issues. If you put a prop as inline (vs. a referentially  equal value, via putting it in `data`) it will cause a remount, and thus also losing its refinements. Can you try moving those values?

**Comment by alishanster** [comment]
@Haroenv Thank you, it did work!

 [Here](https://codesandbox.io/s/vue-instantsearch-app-wt0se) I did what you suggested and it works.

However now for some reason the number of requests keep increasing with each new ```zip``` input changed. 

After a lot of experiments I found out that it happens when ```ais-hierarchical-menu``` is used.
I could probably reproduce the issue in codesandbox, does airbnb have a hierarchical categories in records? Need both _geoloc and hierarchical categories in records.

**Comment by Haroenv** [comment]
Sorry, that index doesn't have hierarchical categories, but you can just add it on a different attribute, and i'll try it out

**Comment by alishanster** [comment]
Hi,
Um I am not sure, but here is [sendbox](https://codesandbox.io/s/vue-instantsearch-app-x50nw) with hierarchical menu, but as there aren't special hierarchical attributes, it is not working. Or did I misunderstood how to add on a different attribute?

**Comment by alishanster** [comment]
Any ideas what could be happening? 
Interestingly somehow when I reproduce everything on codesendbox with my index (that have ```_geoloc``` and ```hierarchical``` menu) It works with ```:routing``` and ```ais-hierarchical-menu```. But on my development search starts lagging after few operations (zip changes only), if I remove either ```:routing``` or ```ais-hierarchical-menu``` everything works fast again.  
Is there a way to share my index privately?

**Comment by Haroenv** [comment]
Sorry, I haven't yet been able to fully  reproduce what you're describing. It definitely should not be reloading. However, the reloading only seems to be happening within the codesandbox embed, and not anymore once you're on the "full page" (cc @compuives)
