### ISSUE TITLE
ais-pagination not renewing to page 1 on filters change in ais-configure element

### ISSUE THREAD

**Issue by An147** [algolia/vue-instantsearch#749]
**Feature ⚡️**
I really don't know is it a feature or bug yet. I thought it should be a bug.

### What is your use case for such a feature?

The initial feature I needed to support ais-range-input that can handle 2 attributes: 1 per each input field. This is done through connectors, I'm new to InstantSearch so I decided to make a quick fix.
My quick fix:  I have 2 data variables in my App.vue component, I update them directly through common HTML `<input/>`s and substitute into computed "filter" data.
Then I have configured the filter to work like this: `<ais-configure :filters="filter"/>`

It works well and updates the results instantly as I type in any of these inputs, but there is one bad thing: if I were on page 2 or more on the previous query, and then change filter, the pagination doesn't go to page 1 as it does for any other refinement. So I end up with an empty results page, and user needs to click on pagination page [1] button to see results again.

### What is your proposal

Change in the behavior or give us API entry to change page number directly from the code.

### What is the version you are using?

vue-instantsearch 2.6.0 (current latest)

**Comment by Haroenv** [comment]
Have you seen the solution here? https://discourse.algolia.com/t/creating-widget-that-filters-with-2-attributes/9088/4?u=haroen

https://codesandbox.io/s/vue-instantsearch-app-m3lon

Configure isn't exactly meant for filters which are showing in the UI, since those indeed need to reset the page, but many of the parameters set don't require a page reset, and would cause that to be confusing.

**Comment by An147** [comment]
> Have you seen the solution here? https://discourse.algolia.com/t/creating-widget-that-filters-with-2-attributes/9088/4?u=haroen
> 
> https://codesandbox.io/s/vue-instantsearch-app-m3lon
> 
> Configure isn't exactly meant for filters which are showing in the UI, since those indeed need to reset the page, but many of the parameters set don't require a page reset, and would cause that to be confusing.

Sorry, I misunderstood the concept then.



> Have you seen the solution here? https://discourse.algolia.com/t/creating-widget-that-filters-with-2-attributes/9088/4?u=haroen

Yes, sure, thanks, I just had an angry client and needed a very quick fix. Your solution seems a harder to understand for me, so I decided to postpone it on the coming business days.
