### ISSUE TITLE
Highlighted element classes are not applied

### ISSUE THREAD

**Issue by onebrightlight** [algolia/vue-instantsearch#759]
**Bug 🐞**

### What is the current behavior?
Vue InstantSearch does not apply a highlighted element’s class names. I found Issue #639 had been closed but it appears it’s still affecting behavior.

### Make a sandbox with the current behavior

I’ve added [Tailwind](https://www.tailwindcss.com) to the example and applied some classnames to lines 33-35. The classes that are assigned to `ais-Highlight` are rendered, but the classes that are assigned to `ais-Highlight-highlighted` are not.

https://codesandbox.io/s/reverent-payne-n4h68?fontsize=14&hidenavigation=1&theme=dark

### What is the expected behavior?
In my sandbox, we should see classes of `normal font-bold` applied to the marked highlighted elements.

### Does this happen only in specific situations?
Happens consistently for me.

### What is the proposed solution?
Ensuring that InstantSearch respects the properties in its documentation

### What is the version you are using?
Vue InstantSearch 2.0.1

**Comment by Haroenv** [comment]
You're right, this seems to be wrong. I'm looking now what solution is possible. It seems like we are skipping generated class names

**Comment by NidalGhonaim** [comment]
Having a similar issue. Been trying to solve it for hours thinking i have been doing something wrong.

**Comment by Haroenv** [comment]
Sorry! We have since given the ability in InstantSearch.js to forward highlighted class name, but it couldn't yet have been used in Vue InstantSearch. I'll remove it from the docs in the mean time before it can be used here.

**Comment by Haroenv** [comment]
This has been fixed in v3, as well as 2.7.0 :) https://codesandbox.io/s/sad-moon-z0zd7
