### ISSUE TITLE
How to call searchFunction manually

### ISSUE THREAD

**Issue by alexcroox** [algolia/vue-instantsearch#762]
**Feature ⚡️**

### What is your use case for such a feature?

I have the following search page filters:

![ss](https://p193.p3.n0.cdn.getcloudapp.com/items/z8uXJNBP/Screenshot+2020-02-17+at+12.36.40.png?v=184e32d5224146deb8bed0ab35f77fdf)

Since there is no vue-instantsearch widget for aroundLatLng/aroundRadius I have created this outside of vue-instantsearch and am storing the values for aroundLatLng/aroundRadius inside my vuex store.

I have the following:

```
<AisInstantSearch
      ref="mainSearch"
      :searchClient="searchClient"
      :searchFunction="performSearch"
      :routing="routing"
      :indexName="defaultSearchIndex"
      :key="search.childCommodity"
    >
```

```
performSearch(helper) {
      const page = helper.getPage()

      helper
        .setPage(page)
        .setQueryParameter('aroundLatLng', this.$store.state.search.aroundLatLng)
        .setQueryParameter('aroundRadius', his.$store.state.search.aroundRadius)
        .search()
    }
```

I'm then watching the store for changes to these values and it's at this point I need to trigger the `performSearch` function manually. Of course I can't do this directly because it expects the `helper` parameter.

I have tried:

```
this.searchClient.search()
this.$refs.mainSearch.searchClient.search()
```

 with no joy.

**How do I trigger the `searchFunction` manually?**

### What is the version you are using?

^2.7.0

**Comment by Haroenv** [comment]
This seems like a thing which is more suited for a configure widget:

```vue
<ais-configure
  :around-lat-lng.camel="$store.state.search.aroundLatLng" 
  :around-radius.camel="$store.state.search.aroundRadius" 
/>
```

Does that work for you?

**Comment by alexcroox** [comment]
@Haroenv oh you hero that's much easier! Thank you!!
