### ISSUE TITLE
ais-toggle-refinement ignores ON prop

### ISSUE THREAD

**Issue by alexcroox** [algolia/vue-instantsearch#767]
**Bug 🐞**

### What is the current behavior?

When providing ais-toggle-refinement with an `on` prop value it is always ignored and defaults to `true`

### What is the expected behavior?

Set the `toggle` object key value to my custom `on` value

### What is the version you are using?

"vue-instantsearch": "^2.7.0"

![ss1](https://p193.p3.n0.cdn.getcloudapp.com/items/6quBGe1P/Screenshot%202020-03-17%20at%2010.12.56.png?v=7ace29abb57a9d752421b7232a46992d)

![ss2](https://p193.p3.n0.cdn.getcloudapp.com/items/geu2yzDp/Screenshot%202020-03-17%20at%2010.14.18.png?v=b9478e172e6156e22025da062832030c)

**Comment by eunjae-lee** [comment]
Hi @alexcroox ,

It's weird. It's supposed to work.
https://codesandbox.io/s/ecstatic-sound-vhnrl

Can you test this example and see if you can reproduce your issue there?

![Kapture 2020-03-17 at 12 06 00](https://user-images.githubusercontent.com/499898/76850500-cc6ec680-6847-11ea-85c4-3edc0c16babd.gif)

**Comment by alexcroox** [comment]
It's quite hard to replicate in a sandbox as I had to spend weeks painfully working out and building out a custom router because of the well documented "double back bug". As such it's interlaced with vuex calls etc.

But the summary is that while `ais-current-refinements` correctly shows the custom value, when using a custom router the `stateMapping.stateToRoute(uiState)` function is showing it as `true`

![ss](https://p193.p3.n0.cdn.getcloudapp.com/items/BluBWQNK/Screenshot%202020-03-17%20at%2011.24.36.png?v=6f30a7c53a9bbb208b9976275a7f7d55)

Below is the code I've tried to put in but failed to compile to try give you a little more context:

https://codesandbox.io/s/affectionate-bush-1owdp

**Comment by alexcroox** [comment]
OK chalk this one up to a another massive miss-understanding on my part on how this all works!

I did some more debug output and various testing and realised the "true" in the URL has nothing to do with it's actual value when read back in on page reload!

![ss](https://p193.p3.n0.cdn.getcloudapp.com/items/E0uqZ4Lp/Screenshot%202020-03-17%20at%2011.45.27.png?v=b1667fd08c8adc77ec2ef6204026a7bc)

For anyone who might stumble on this thread, if you see "true" in the URL it doesn't actually reflect the refined value.

Sorry for wasting your time @eunjae-lee

**Comment by Haroenv** [comment]
Sorry that your experience wasn't great. I've been thinking about solutions for the "double back" bug lately and thought of something that might work. In the mean time you can use a custom router which would be the same as the history router, but without the dispose / write part

**Comment by gabz57** [comment]
Hello, currently I'm experiencing the same difficulty with this component, we have a product search page, and display 2 checkboxes using ais-toggle-refinement, the first is set using **on="true"**, the second with **on="false"**.
```
<ais-toggle-refinement attribute="is_published" :label="Published" :on="true">
  <my-checkbox
    slot-scope="{ value, refine }"
    :checked="value.isRefined"
    @change="refine(value)">
      Published
  </my-checkbox>
</ais-toggle-refinement>
<ais-toggle-refinement attribute="is_published" label="Not published" :on="false">
  <my-checkbox
    slot-scope="{ value, refine }"
    :checked="value.isRefined"
    @change="refine(value)">
      Not published
  </my-checkbox>
</ais-toggle-refinement>
```
When we click any or both of them, the response is correct.

However, as described above, even if the right query to algolia is sent, the query param in my application shows **in both cases** the value "true" in the url:

> ?toggle%5Bis_highlighted%5D=**true**

-> which leads to a bug when we refresh the page as we only have one info set to true
I wonder if we shouldn't have instead : 
- if I only check the second checkbox, the value related to the attribute in the url should be false (the prop named **on**)
> ?toggle%5Bis_highlighted%5D=false
- when both are checked, the query parameters presents both values
> ?toggle%5Bis_highlighted%5D=true&toggle%5Bis_highlighted%5D=false
