### ISSUE TITLE
AisPagination, specify max number of visible pages

### ISSUE THREAD

**Issue by alexcroox** [algolia/vue-instantsearch#770]
**Feature ⚡️**

### What is your use case for such a feature?

I'd like to control the max number of pages visible in the pagination widget to show more or less depending on how much screen space there is.

### What is your proposal

Currently there is a `totalPages` prop, but this actually limits the max number of pages the user can reach, not the *current visible total*.

By default this is set to `infinity` and it shows a maximum of 7 visible pages, but you can click through to 80 pages if you wanted to. If you change this value to say `4`, then it treats it as 4 pages being the maximum possible number, you cannot browse past 4 pages, even if there are 80 pages in total.

### What is the version you are using?

2.7.0

**Comment by Haroenv** [comment]
I don't understand the difference between what you're suggesting & `totalPages`. Could you maybe make a diagram clarifying what you want your limit to behave like?

**Comment by alexcroox** [comment]
Sure, this is totalPages = undefined (not specified) and I've navigated to page 4 for demo purposes. 

`<AisPagination>`

![ss](https://p193.p3.n0.cdn.getcloudapp.com/items/rRu6292j/Screenshot%202020-04-03%20at%2012.59.16.png?v=db3fa4d794a3f519d0c683dc60e52111)

This is totalPages = 4 (which I would expect to visibly limit the number of pages 4, and you should be able to click the > button to go past 4, or click 4 and see 5 appear, as is the behaviour when totalPages = undefined

`<AisPagination :totalPages="4">`

![ss2](https://p193.p3.n0.cdn.getcloudapp.com/items/7KuRO0K9/Screenshot%202020-04-03%20at%2012.58.43.png?v=1da1c0f92cdd3bcd7c6c82396786d05f)

However as you can see, it doesn't limit the number of clickable page buttons to 4, it limits the overall total number of pages to 4, when there are many more available.

**Comment by Haroenv** [comment]
Is it possible what you're looking for is `:padding="2"`? In this case an even number of total pages isn't possible however, since we wouldn't be able to put the actual page centered

**Comment by alexcroox** [comment]
Ah I totally glossed over the padding option in the docs, assuming it had something to do with the dom padding! Thank you for the fast response.
