### ISSUE TITLE
Ais-Highlight breaking on Nuxt Client-Only (No-ssr) 

### ISSUE THREAD

**Issue by joaomarcelofm** [algolia/vue-instantsearch#773]
**Bug 🐞**

### What is the current behavior?

`ais-hightlight` breaks when used in combination with `client-only` component in Nuxt.

### Make a sandbox with the current behavior

https://codesandbox.io/s/nuxt-tzoob?file=/pages/search.vue:321-322

Steps for reproduction

1. Type something in the search box (the text will be highlighted in yellow).
2. Hit backspace you remove a character from the search.
3. The rendering breaks and instead of showing the yellow highlight it renders the <mark> tag.

### What is the expected behavior?

The `mark` tag should never be rendered as text in the `ais-highlight` component.

### What is the version you are using?
AlgoliaSearch - 4.2.0
Vue-InstantSearch - 2.7.0

**Comment by Haroenv** [comment]
This seems to be correct, I can't explain why it's happening, but here's a workaround (remaking highlight on your side, without relying on InstantSearch' highlighting):

```
vue
<template>
  <div class="ais-Highlight" v-html="innerHtml"></div>
</template>

<script>
function getPropertyByPath(object, path) {
  const parts = path.split('.');

  return parts.reduce((current, key) => current && current[key], object);
}

const htmlEscapes = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

const regexUnescapedHtml = /[&<>"']/g;

// make sure escape can be done only once, by doing it per hihglight component
function escapeHtml(html) {
  return html.replace(regexUnescapedHtml, character => htmlEscapes[character])
}

export default {
  props: {
    hit: {
      type: Object,
      required: true,
    },
    attribute: {
      type: String,
      required: true,
    },
  },
  computed: {
    innerHtml() {
      const highlight = getPropertyByPath(this.hit._highlightResult, this.attribute)
      return escapeHtml(highlight.value)
        .replace(/__highlight__/g, '<mark>')
        .replace(/__\/highlight__/g, '</mark>')
    }
  }
}
</script>
```

(and in the main code:

```
          <ais-configure
              highlightPreTag="__highlight__"
              highlightPostTag="__/highlight__"
            />
            <ais-hits :escapeHTML="false">
```


https://codesandbox.io/s/async-silence-xwybd?file=/src/NonEscapedHighlight.vue

**Comment by joaomarcelofm** [comment]
@Haroenv I've implemented your suggesting in the reproduction sandbox (search.vue) and it works well, thanks for the suggestion. 👍

**Comment by Haroenv** [comment]
In the mean time we have rewritten highlight, and it no longer uses v-html, which means this issue should be fixed.
