### ISSUE TITLE
Adding security to algolia + firestore

### ISSUE THREAD

**Issue by gqoew** [algolia/vue-instantsearch#775]
Hi

I'm using firestore in my app and I would like to implement full-text search for users. I'm following the official [firebase Full-text search](https://firebase.google.com/docs/firestore/solutions/search) tutorial and I managed to sync my algolia index  with my firestore each time users add a modification in the firestore. However, I would like to limit the search results users see in a secured manner.

The official docs propose a [solution](https://firebase.google.com/docs/firestore/solutions/search#adding_security) that consits in adding an HTTP Cloud Function that generates a Secured API Key, which adds specific filters to every query performed by a user.

I'm not sure however how it is possible to integrate this logic with `vue-instantsearch`. Do you have any advice?

Thank you!

**Comment by Haroenv** [comment]
You'd be best off either having an endpoint which creates a secured API Key before making the search client in the frontend, or inlining the API Key in the html
