### ISSUE TITLE
Range input resets if updated after an URL change with routing

### ISSUE THREAD

**Issue by dotboris** [algolia/vue-instantsearch#776]
**Bug 🐞**

### What is the current behavior?

Here are the steps to reproduce this:

1. Open this example: https://codesandbox.io/s/reverent-currying-sgs8t?file=/src/App.vue
1. Enter in `50` to `100` in the range input field (right above the results)
1. Press `Go`
1. Refresh the page
1. Press `Go` again (without touching the values in the inputs)

Once you've done this, you'll notice that the range input part of the search got reset completely.

This also happens if you adjust one of the fields. Lets say that after the refresh, you change the max value and you hit `Go`. The max value will stay as the new value you entered but the min value will be reset.

### Make a sandbox with the current behavior

https://codesandbox.io/s/reverent-currying-sgs8t?file=/src/App.vue

### What is the expected behavior?

I expect the search to be left as is. The values should not be erased when I hit `Go` a second time.

### Does this happen only in specific situations?

I can systematically reproduce this when doing a refresh. I did some playing around and I found that strange behavior also happens when use the browser's back button and the hit `Go`.

I have tried reproducing this with the `instantsearch.js` lib and it works fine. See: https://codesandbox.io/s/prod-tdd-xcsj1?file=/src/app.js

### What is the proposed solution?

Honestly, I don't know. I haven't debugged this enough to be able to tell how to fix it at this point.

### What is the version you are using?

I'm using the latest version as of writing this.

```
vue-instantsearch@2.7.0
```

**Comment by dotboris** [comment]
I think that I know what's going on.

`RangeInput` refines the search with the values from `minInput` and `maxInput` (they're data fields). 

https://github.com/algolia/vue-instantsearch/blob/4f8eb4bf1fa0bc3939a808e435e3ce7bfd6f2e89/src/components/RangeInput.vue#L12-L15

Those two fields are populated when the textboxes change: See `@change`.

https://github.com/algolia/vue-instantsearch/blob/4f8eb4bf1fa0bc3939a808e435e3ce7bfd6f2e89/src/components/RangeInput.vue#L18-L27

While debugging, I found that the value of `minInput` & `maxInput` are in sync when I start playing with the component but they are set to `undefined` once I refresh.

When the values are entered by the user:

![image](https://user-images.githubusercontent.com/1874242/81859954-069cd180-9534-11ea-99ee-46f334b11f2b.png)

After a refresh:

![image](https://user-images.githubusercontent.com/1874242/81859999-17e5de00-9534-11ea-9d12-ae4c2acd6da5.png)

I think that the bug happens because the `minInput` and `maxInput` are not updated when the search state is updated from somewhere else like the URL during a page load.

**Comment by eunjae-lee** [comment]
Hi there,
Thank you for the investigation.
We are on it!
