### ISSUE TITLE
UX components disappear when using <ais-instant-search :search-function

### ISSUE THREAD

**Issue by antongorodezkiy** [algolia/vue-instantsearch#782]
**Bug 🐞**

### What is the current behavior?

UX components disappear when using `:search-function="searchFunction"` in `<ais-instant-search :search-client="searchClient" index-name="instant_search" :search-function="searchFunction">`

```
searchFunction(helper) {
      if (helper.state.query) {
        helper.search()
      }
    }
```

### Make a sandbox with the current behavior

https://codesandbox.io/s/crimson-cache-hyr6m?file=/src/App.vue

### What is the expected behavior?

UX components do not disappear

### Does this happen only in specific situations?

It happens always

### What is the version you are using?

https://www.npmjs.com/package/vue-instantsearch/v/2.7.0

---

I'm not sure is that behaviour intended, but I thought it will only prevent empty search request on page load.

**Comment by yannickcr** [comment]
It is intended. By doing:

```js
searchFunction(helper) {
  if (helper.state.query) {
    helper.search()
  }
}
```

You prevent InstantSearch to do the initial query, so the components are not rendered since we did not get any data to render yet.

**Comment by antongorodezkiy** [comment]
@yannickcr I see, thank you.

I had a search field inside Algolia component and lost it when tried to use `searchFunction` for conditional requests

```
<ais-instant-search>
    <ais-autocomplete>
        <input />
    </ais-autocomplete>
</ais-instant-search>
```

> You prevent InstantSearch to do the initial query, so the components are not rendered since we did not get any data to render yet.

Not too obvious decision for me, but I glad that everything is working as expected.

---

For those who will face the same case when you try to avoid initial request but to still have markup rendered inside `<ais-instant-search>` I could solve it using custom `searchClient` as described here https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-requests/vue/
