### ISSUE TITLE
Possibility to pass lat and lng in url using router

### ISSUE THREAD

**Issue by sl0wik** [algolia/vue-instantsearch#790]
**Feature ⚡️**

### What is your use case for such a feature?

I'm trying to pass `lat` and `lng` to use as `aroundLatLng` in URL but it seems to be not supported by the router.

Currently [routeToState](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/js/) allow to pass parameters like `page`, `refinementList` or `query` but no `aroundLatLng`. I was trying to use `configure` instead but it seems to be not supported.

### What is your proposal

Allow passing `aroundLatLng` inside `routeToState(routeState)` response, or (preferred) allow passing parameters inside `configure` so `state.configure.aroundLatLng` can be passed as a response.

### What is the version you are using?

2.6.0

**Comment by Haroenv** [comment]
Configure is indeed not supported in this version (it is added in the next major version, if you are not using server side rendering, you can use beta.0). To work around this, it's best to create a custom widget specifically for lat/lng. An example connector like this is the geo search widget (note that you'll need to change the actual parameter to `aroundLatLng`): 

https://github.com/algolia/instantsearch.js/blob/master/src/connectors/geo-search/connectGeoSearch.js#L271-L305

**Comment by sl0wik** [comment]
Thanks @Haroenv , 

In ref to `beta.0` branch:
`routeToState` working fine and passing parameters to configure, but `stateToRoute` would not include parameters passed during `routeToState`.

Example:
In `routeToState`, `state.index.configure['aroundLatLng'] = route.around;` correctly passing dat into AIS but
```
mapping.stateToRoute = function(uiState) {
  console.log(uiState);
  ...
}
```
would return only `configure` information passed inside `<ais-configure ...>` and no configuration passed from the route.

To 3.0 beta users:
You need to include index name inside state so its `state.index_name.pages` instead of `state.pages`.

**Comment by Haroenv** [comment]
could you make a sandbox with behaviour which is not as expected please? I'm not sure if I fully understand :)

**Comment by Haroenv** [comment]
I'm not sure if that was clear (per your email), but I've made an example on how to make a custom connector, modelled around geo search, but for aroundLatLng specifically: https://codesandbox.io/s/flamboyant-galileo-tncet?file=/src/GeoSearch.vue

Hope that's clear!

**Comment by Haroenv** [comment]
Since Vue InstantSearch v3 this has been fixed.
