### ISSUE TITLE
Searchable RefinementList ignores item.label customized with transformItems

### ISSUE THREAD

**Issue by dotboris** [algolia/vue-instantsearch#802]
**Bug 🐞**

### What is the current behavior?

When a `RefinementList` is set to be searchable with the `searchable` prop, it will ignore the value of `item.label`. This is a problem when you use `transformItems` to format those values.

The following example doesn't work:

```Vue
<template>
  <ais-refinement-list
    attribute="..."
    searchable
    :transform-items="transformItems"
  />
</template>

<script>
  export default {
    methods: {
      transformItems(items) {
        return items.map(item => ({
          ...item,
          label: item.label.toUpperCase(),
        }));
      },
    },
  };
</script>
```

The values are displayed in their original case instead of in uppercase.

### Make a sandbox with the current behavior

Sandbox demonstrating the issue: https://codesandbox.io/s/vue-instantsearch-transformitems-searchable-bug-618m2?file=/src/App.vue

There are two `RefinementList` components. They're both configured exactly the same except that one of them is searchable and the other one is not.

### What is the expected behavior?

I expect to see the contents of `item.label` as modified by my `transformItems` function.

### Does this happen only in specific situations?

It seems like this only happens when `searchable` is set.

### What is the proposed solution?

Always show `item.label` to the user.

### What is the version you are using?

```
vue-instantsearch@3.0.1
```

**Comment by dotboris** [comment]
This seems to happen because of the highlight feature of `RefinementList`.

When the `RefinementList` is searchable, it uses the `Highlight` component. When it's not searchable, it displays the contents of `item.label`.

https://github.com/algolia/vue-instantsearch/blob/62b26456e5f3e3713c50659a05e5e86ab26e05eb/src/components/RefinementList.vue#L59-L71

If we look at the `Highlight` component, we see that it's a wrapper around the `Highlighter` component. That component seems to use `item.value` and not `item.label`.

https://github.com/algolia/vue-instantsearch/blob/62b26456e5f3e3713c50659a05e5e86ab26e05eb/src/components/Highlighter.vue#L5-L10

**Comment by Haroenv** [comment]
It actually takes `item.highlighted`, and not `item.label`, so that it works when searching too

**Comment by dotboris** [comment]
My colleague tested out using `item.highlighted` instead of `item.label` in our `transformItems` function and it works great. This is no longer a problem for us so I'm closing this issue.
