### ISSUE TITLE
Nuxt SSR Routing URLs doc inconsistency

### ISSUE THREAD

**Issue by sugud0r** [algolia/vue-instantsearch#810]
**Bug 🐞**

I'm integrating Algolia in my project, but I searched to integrating routing urls, there appear to be a inconsistency abou to do that:

https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/#combining-with-nuxtjs

Right here docs are telling me to use `createInstantSearch` and using custom params in `.findResultsState`, but here (the really updated doc):

https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/vue/#with-nuxt

I need to use `createServerRootMixin` because `createInstantSearch` is no longer available. ALso, `.findResultState` no longer accepts custom params.

Which is the updated way to do this?

**Comment by francoischalifour** [comment]
Hey—thanks for letting us know. We recently updated the documentation for Vue SSR but missed a few occurrences.

Starting from Vue InstantSearch v3, `createServerRootMixin` is the new API to use SSR ([see changelog](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/vue/#ssr-server-side-rendering)).

**Comment by sugud0r** [comment]
> Hey—thanks for letting us know. We recently updated the documentation for Vue SSR but missed a few occurrences.
> 
> Starting from Vue InstantSearch v3, `createServerRootMixin` is the new API to use SSR ([see changelog](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/vue/#ssr-server-side-rendering)).

Which is the new way to do URL Routing with Nuxt route? Thanks.

**Comment by Haroenv** [comment]
https://codesandbox.io/s/recursing-mountain-k8umi?file=/pages/search.vue is the updated method @sugud0r, I've updated the docs, which will be released soon with this.
