### ISSUE TITLE
ais-highlight removes spaces

### ISSUE THREAD

**Issue by dseeger** [algolia/vue-instantsearch#826]
**Bug 🐞**

### What is the current behavior?
When typing in the search-box, ais-highlight removes spaces between consecutive words.

![2020-07-31 08 14 12 vue-instantsearch netlify app 5327eff91408](https://user-images.githubusercontent.com/2930193/89005957-f5c75500-d305-11ea-9dc7-8ed877de4dcc.png)

### Make a sandbox with the current behavior
https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch

### What is the expected behavior?
Spaces between highlighted words should remain.

### What is the version you are using?
3.1.0

**Comment by Haroenv** [comment]
Thanks for finding this, it's indeed a bug. There's separate elements, but there are no spaces between the elements. I'm looking into a fix now.
