### ISSUE TITLE
ais-hierarchical-menu doesn't work when nested into an ais-index

### ISSUE THREAD

**Issue by sukei** [algolia/vue-instantsearch#831]
**Bug 🐞**

### What is the current behavior?

When using a `ais-hierarchical-menu` widget into a `ais-index`, nothing is rendered. When extracting the `ais-hierarchical-menu` out of the `ais-index`, the tree showed-up.

### What is the expected behavior?

The `ais-hierarchical-menu` should be the same whereas it is under an `ais-index` or not.

### Does this happen only in specific situations?

When the `ais-hierarchical-menu` widget is nested into a `ais-index`.

### What is the version you are using?

`instantsearch.js (4.7.0)`, `Vue InstantSearch (3.0.2)`

**Comment by Haroenv** [comment]
Is it possible the index in which you were rendering does not have `attributesForFaceting` set up like the main index has? 

I've tried to replicate this in our demo application, but it works: https://codesandbox.io/s/epic-tdd-ujwt2?file=/src/App.vue. If your use case was different, could you edit the sandbox and show where it's not working? 

Thanks!

**Comment by sukei** [comment]
Hi @Haroenv, You are right, it works. It was because of an other misconfigured `ais-toggle-refinement`. Thanks for the sandbox, it helps me find the issue.

**Comment by Haroenv** [comment]
Glad you found a solution!
