### ISSUE TITLE
ais-menu component variable canToggleShowMore never reports true

### ISSUE THREAD

**Issue by rizen** [algolia/vue-instantsearch#837]
**Bug 🐞**

### What is the current behavior?

If you add a limit (or use the default of 10) to an ais-menu component has no way to ever show more than whatever the limit is, because canToggleShowMore is never true. 

### Make a sandbox with the current behavior

In this example I set the limit to 5 categories, and there are almost 50, but I can never click on the "more" button.

https://jsfiddle.net/2kvw8hLo/1/

### What is the expected behavior?

If there are more than *limit* items, then canToggleShowMore should report true. 

### Does this happen only in specific situations?

No it always happens.

### What is the proposed solution?

My guess is that the underlying code is checking items.length, but that will always be set to limit. It should be looking at the total number if possible items, not the limited item count.

### What is the version you are using?

<script src="https://cdn.jsdelivr.net/npm/algoliasearch@4.4.0/dist/algoliasearch.umd.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-instantsearch@3.2.0/dist/vue-instantsearch.js" integrity="sha256-g2WfQlB3Fi75oVZSZeyIQQtMdR0I/xR5YyNh5b27260=" crossorigin="anonymous"></script>

> Always try the latest one before opening an issue.

3.2.0 is the latest as of this posting

**Comment by Haroenv** [comment]
Hi @rizen, this is because you passed `:show-more="false"` to the widget. In that case `canShowMore` is always false. Here's a fixed example: https://jsfiddle.net/ao5h8u64/

We chose to have "canShowMore" to report false in those cases, to allow people to create their own widgets which work both as show-more and non-show-more.

Hope that makes sense!

**Comment by rizen** [comment]
Wow, ok I totally misinterpreted the documentation on that. Thanks!
