### ISSUE TITLE
ais-menu with a bunch of facet filters creates duplicates in the results and can crash the browser

### ISSUE THREAD

**Issue by rizen** [algolia/vue-instantsearch#838]
**Bug 🐞**

### What is the current behavior?

If you create a search with a bunch of facet filters and an ais-menu you get 2 weird results:

When you click on the ais-menu instead of limiting to attribute, it creates a bunch of duplicate records in the search results. 

Also this seems to create an infinite loop or something, as Safari, Chrome, and Firefox will all lock up eventually. 

### Make a sandbox with the current behavior

https://jsfiddle.net/u5c3s0dx/

### What is the expected behavior?

In the example the "Indie Games" category has 4 results. So when I click on the menu I'd expect it to be limited to those 4 results. However, I get a big list of results instead.

### Does this happen only in specific situations?

It only appears to happen with a large number of facet filters. 

### What is the proposed solution?

Fix it!

### What is the version you are using?

3.2.0, which is the latest version as of this posting. 

> Always try the latest one before opening an issue.

**Comment by Haroenv** [comment]
This is happening because the `ais-menu` takes over the facetFilters you pass with configure. This means that you need to use the string form (`filters`) for those refinements.

As alternative, it's also possible to have null-rendering menus for the combination of filters you want, and use `initialUiState` to enable them

**Comment by Haroenv** [comment]
In your case, that's done like this: https://codesandbox.io/s/restless-paper-k8x6o?file=/src/App.vue

**Comment by rizen** [comment]
I've been using Algolia for years, but just now rebuilding everything in Vue. I feel like I'm learning everything all over again! Thank you so much for your help. You're amazing.

**Comment by Haroenv** [comment]
That's a fair criticism, we are indeed hiding over some of the more powerful features of search parameters in an attempt to make the usage overall simpler. If you have any feedback on how things could be more straightforward or easier for you, don't hesitate to continue giving feedback!

**Comment by rizen** [comment]
I'm sorry, it was not intended as criticism of you or Algolia. It was intended as criticism of me.

I know it's off topic, but I do have a question: Is there a drop-in replacement for urlSync in vue-instantsearch? I've read this page: https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/

And if I need to write my own then I will. Just wondering if there's something quick that has the features of urlSync.

**Comment by Haroenv** [comment]
for Vue InstantSearch we disabled `routing=true`, I think that was a mistake, and will allow that again in the future, but for now you can do as easy as it gets this https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/#basic-urls:

```vue
<template>
  <ais-instant-search
    :search-client="searchClient"
    index-name="instant_search"
    :routing="routing"
  >
    <!-- add the other components here -->
  </ais-instant-search>
</template>

<script>
import { history as historyRouter } from 'instantsearch.js/es/lib/routers';
import { singleIndex as singleIndexMapping } from 'instantsearch.js/es/lib/stateMappings';

export default {
  data() {
    return {
      searchClient: algoliasearch(
        'latency',
        '6be0576ff61c053d5f9a3225e2a90f76'
      ),
      routing: {
        router: historyRouter(),
        stateMapping: singleIndexMapping('instant_search'),
      },
    };
  },
};
</script>
```

**Comment by rizen** [comment]
I tried that. Nothing gets written to the URL. If I replace singleIndex with simple I get something written to the URL, but it's pretty ugly and doesn't encompass everything.

**Comment by rizen** [comment]
Ah! I just realized what it doesn't work. singleIndexMapping('instant_search') should be singleIndexMapping('my-index-goes-here').

There's a recommendation for you. Don't ever use names like "instant_search" for placeholders as it's hard to distinguish if you mean that literally or as a placeholder.
