### ISSUE TITLE
Navigation history is being flooded with duplicate paths

### ISSUE THREAD

**Issue by ctbradley** [algolia/vue-instantsearch#839]
**Bug 🐞**

### What is the current behavior?

On route enter navigation history is flooded with duplicate paths.

Example with our products

![Screen Shot 2020-08-18 at 11 49 08 AM](https://user-images.githubusercontent.com/11767079/90536209-be500980-e149-11ea-9169-374374de92b3.jpg)

Example with Algolia products

![Screen Shot 2020-08-18 at 12 19 04 PM](https://user-images.githubusercontent.com/11767079/90538981-42f05700-e14d-11ea-90d7-799df5d55ab8.jpg)

### Make a sandbox with the current behavior

https://github.com/ctbradley/uvue-sandbox

```sh
git clone https://github.com/ctbradley/uvue-sandbox.git
cd uvue-sandbox
npm i
npm run ssr:serve
```

**ATTN** Go to this route directly: http://localhost:3000/search

Right click on the back button in your web browser to observe the duplicate history.

### What is the expected behavior?

Route should load with on only one instance of path `/search`

### Does this happen only in specific situations?

I've been able to reproduce this behavior in all major browsers:

Chrome
Firefox
Safari
Edge

### What is the proposed solution?

It would appear that `router.write()` in `src/modules/createInstantSearchRouting.js` is being called multiple times causing the duplication.

Not sure why write is being called multiple times 🤷‍♂️

### What is the version you are using?

"vue-instantsearch": "3.2.0"

**Comment by Haroenv** [comment]
Hi @ctbradley, this is happening because your custom router always writes, even if the URL is the same as before. This can be avoided by doing a check before writing, like I've done here: https://github.com/ctbradley/uvue-sandbox/pull/2

**Comment by ctbradley** [comment]
Hey @Haroenv, your solution solves the initial history duplication but blows up once you start selecting filters. Is there any documentation the router.write() method or an updated example?

**Comment by Haroenv** [comment]
`write` is called whenever InstantSearch state changes: https://github.com/algolia/instantsearch.js/blob/master/src/middleware/createRouter.ts#L57

In your example, `query || path` is used to be written, but in the main example, we write a full url, since the string is easier to compare, see official source:

https://github.com/algolia/instantsearch.js/blob/master/src/lib/routers/history.ts#L131
