### ISSUE TITLE
Nuxt Routing in algolia

### ISSUE THREAD

**Issue by bootsmann95** [algolia/vue-instantsearch#842]
Hello i have some issues with the algolia router in nuxt with ssr.

I have tried to copy from the documentation but i could not make it work. So i wanted to create a code sandbox and make it work there. but it seems your codesandbox isn't working. 

Here is my code for algolia ssr in nuxt with routing.  Hope you can help me. it seems as the url isn't parsed correctly. 

![image](https://user-images.githubusercontent.com/53180316/91536476-0a9f0480-e915-11ea-99e8-419ad504ecf2.png)
![image](https://user-images.githubusercontent.com/53180316/91536488-0ffc4f00-e915-11ea-83c6-7b8cb9897523.png)
![image](https://user-images.githubusercontent.com/53180316/91536502-14c10300-e915-11ea-8311-f87f2b98fa96.png)

here is how the url is passed: 
![image](https://user-images.githubusercontent.com/53180316/91536539-25717900-e915-11ea-881a-29b628e55bfe.png)

Looking forward to hear from you guys!

**Comment by Haroenv** [comment]
Is `this.$nuxt.router` available where you are passing it? Could you make your setup into a sandbox please? it's easier to debug than a screenshot

**Comment by bootsmann95** [comment]
I tried sandbold but i can't run your nuxt sandbox, seems as there is an error.

**Comment by Haroenv** [comment]
Which error? I meant a sandbox you make from scratch, thanks! https://codesandbox.io/s/github/nuxt/codesandbox-nuxt/tree/master/ is a template for nuxt in general (without Vue InstantSearch)

**Comment by bootsmann95** [comment]
ahh that works i will be back with a demo

**Comment by bootsmann95** [comment]
https://codesandbox.io/s/brave-glitter-oxsm1?file=/pages/index.vue Here you go, the fiter works but not the routing.

**Comment by Haroenv** [comment]
Two things needed to be changed to make your sandbox work:

1. add qs serialisation to the nuxt.config.js:

```
import qs from "qs";

export default {
  router: {
    parseQuery(query) {
      const qs = require("qs");
      return qs.parse(query);
    },
    stringifyQuery(query) {
      const qs = require("qs");
      var result = qs.stringify(query);
      return result ? "?" + result : "";
    }
  },
```

2. the parameter is routing.router, not router

```
     routing: {
        router: nuxtRouter(this.$nuxt.$router)
      }
```

here's a fixed version: https://codesandbox.io/s/serene-tharp-bpkhp?file=/pages/index.vue:1942-2012

**Comment by bootsmann95** [comment]
It works! great!!  5stars out of 5!

now youre here aswell, is there anywhere you explain how you can filter a nuxt ssr. 

so for instance i only wanna show a brand and i have a query i load in a middlewere. 
can i execute a filter in the create server mixin to a apply to all instances on that page ?

**Comment by Haroenv** [comment]
What would you define that filter on? Is this based on certain conditions in the URL (in which case stateMapping or more customised read / write function could work). Can you reproduce what you have in that sandbox?

**Comment by bootsmann95** [comment]
Its not based on url but just so i get the ssr'ed result in my http response.  So when i load the page the filter is applied

**Comment by bootsmann95** [comment]
can it be true that the router runs rreally many times when loading the page? 
![image](https://user-images.githubusercontent.com/53180316/91564236-9ed29100-e940-11ea-8f6d-6fb7e4223be5.png)

**Comment by Haroenv** [comment]
it gets called for every widget's value (in case they have createURL, since that's best not ran on-demand). Do you have many widgets on that page?

**Comment by bootsmann95** [comment]
But to return to the filters issue, here is a sandbox of how we do it now. https://codesandbox.io/s/empty-tree-3xdl2?file=/pages/index.vue

As you can see in the html is there a configure widget.  And as i can see it doesnt get server-side rendered. How can i set filters in the initialize

**Comment by Haroenv** [comment]
You can use  `data` to store variables you want to use in render: https://codesandbox.io/s/hungry-cray-5h5mk?file=/pages/index.vue

**Comment by bootsmann95** [comment]
oh, so if I put a query here: 
![image](https://user-images.githubusercontent.com/53180316/91695901-1ede3e00-eb6f-11ea-8f74-0eab8a8bc6ef.png)
it will filter algolia?

**Comment by Haroenv** [comment]
yes, it will filter, like it does in the demo :)

**Comment by bootsmann95** [comment]
![image](https://user-images.githubusercontent.com/53180316/91700532-5a303b00-eb76-11ea-9544-de8d6c913cb8.png)

this is how the network tab looks like vs the frontend after using the defaultFilter in data and then in configure

**Comment by Haroenv** [comment]
sorry, but that's not a clear screenshot. Could you follow the template please?

**Comment by bootsmann95** [comment]
yea sure, but its a bit hard to see whats in network tab on reload with the code sandbox. 
![image](https://user-images.githubusercontent.com/53180316/91701591-cfe8d680-eb77-11ea-88c9-7c47c921a334.png)
 
but let me try to explain:

I have a query like in the template. And it gives me the result on the left. If I check the network tab and see the preview of the page load, it gives me the result on the right. 

So as you can see they are not the same. The one on the right is a result of aloglia without a filter. And the result on the left is a result with filter. 

This will give som issues when we make need crawlers to index seo based on the products on the page. The SEO crawler with read the result on the right, and not the actual filtered result.

**Comment by bootsmann95** [comment]
@Haroenv

**Comment by Haroenv** [comment]
that's still not clear, and not a reproducible example, but the same screenshot as earlier... Sorry!

**Comment by bootsmann95** [comment]
1. i cant show you in codesandbox
2. the image is side by side how the results are server side rendered.

**Comment by Haroenv** [comment]
sorry, then we won't be able to help you further. Please follow the issue template if you make a new issue, or contact support@algolia.com
