### ISSUE TITLE
ais-range-slider Storybook not working

### ISSUE THREAD

**Issue by djave-co** [algolia/vue-instantsearch#857]
**Bug 🐞**

### Make a sandbox with the current behavior

https://vue-instantsearch.netlify.app/stories/?selectedKind=ais-range-input&selectedStory=with%20vue-slider-component&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs

### What is the expected behavior?

To show a clear example of usage.

### What is the version you are using?

On Google Chrome

> Always try the latest one before opening an issue.

**Comment by Haroenv** [comment]
Good catch, we fixed this in the e-commerce example (this was a breaking change in v3), but not in the storybook.

**Comment by Haroenv** [comment]
I have pushed a fix, the comparison shouldn't be `minValue !== null`, but `typeof minValue === 'number'`
