### ISSUE TITLE
ais-configure calls request multiple times

### ISSUE THREAD

**Issue by hansfelix** [algolia/vue-instantsearch#860]
**Bug 🐞**

### What is the current behavior?
When I add `ais-configure` component to my vue app, it calls request multiple times each time I change vue data.

I add a button and a text, when I click the button, the text will be visible and request will made one more time, in the sandbox I'm using `algoliasearch` function, but if  use a custom search Client, the request is called multiple times.
When the app is loaded, only one query is called:
![image](https://user-images.githubusercontent.com/26641116/92765116-accddc00-f35a-11ea-8f5e-c6b9bc16ef29.png)

When I click button(and vue data change), another request is called:
![image](https://user-images.githubusercontent.com/26641116/92765362-e868a600-f35a-11ea-89e1-c9a2931d73b9.png)

If I remove `ais-configure` it works fine, no extra request is called.

### Make a sandbox with the current behavior
Sandbox: https://codesandbox.io/s/xenodochial-kowalevski-k7fn4?file=/src/App.vue

### What is the expected behavior?
If I change vue data, no additional request is needed.

### Does this happen only in specific situations?
When I Use `algoliasearch` function it calls one time more.
``` js
searchClient: algoliasearch(
        'B1G2GM9NG0',
        'aadef574be1f9252bb48d4ea09b5cfe5',
      ),
```
When I use a custom search Client(using a own backend), it calls multiple times, every time data in vue app is modified.
``` js
searchClient: {
                    search(requests) {
                        requests = requests != undefined ? requests : '{}';
                        console.log(JSON.stringify({ requests }));

                        return fetch('/myCustomUrl', {
                            method: 'post',
                            headers: {
                                'Content-Type': 'application/json',
                            },
                            body: JSON.stringify({ requests }),
                        })
                            .then((res) => {
                                return res.json();
                            })
                            .catch((err) => {
                                console.log(err);
                            });
                    },
                },
```

### What is the version you are using?
This sandbox uses these dependencies:

algoliasearch: 3.33.0
instatnsearch.js: 3.4.0
vue: 2.6.10
vue-instantsearch: 3.0.3

On my poduction enviroment I´m using vue and algolia with cdn, with the same result:
algoliasearch: @4.0.0
vue-instantsearch: @3.0.3

**Comment by Haroenv** [comment]
Custom clients are required to have a cache, like the real client. I think this is not clear enough in the documentation, but you can look at the official client's cache implementation (you can even use it, it's exported as a standalone package) and its usage:

- https://github.com/algolia/algoliasearch-client-javascript/tree/master/packages/cache-in-memory
- https://github.com/algolia/algoliasearch-client-javascript/blob/e6dec843932bdfaac13ffa1e0a11964975499078/packages/transporter/src/createTransporter.ts#L108
- https://github.com/algolia/algoliasearch-client-javascript/blob/e6dec843932bdfaac13ffa1e0a11964975499078/packages/transporter/src/createTransporter.ts#L131
- https://github.com/algolia/algoliasearch-client-javascript/blob/e6dec843932bdfaac13ffa1e0a11964975499078/packages/transporter/src/createTransporter.ts#L117-L120
- https://github.com/algolia/algoliasearch-client-javascript/blob/e6dec843932bdfaac13ffa1e0a11964975499078/packages/transporter/src/createTransporter.ts#L101
