### ISSUE TITLE
Update configuration on the client side after SSR

### ISSUE THREAD

**Issue by adamchipperfield** [algolia/vue-instantsearch#862]
I have set up the Nuxt.js SSR implementation which works great. However, on the client side I'd like to update the configuration based on the user's preferences (which are stored client side in cookies).

Is there any way I can update the `userHasOptedOut` property on the client side whilst retaining the SSR implementation?

**Comment by Haroenv** [comment]
is this something you could read in the `mounted` hook in your main component? Do you have a sandbox of your implementation and what you want to retrieve where?
