### ISSUE TITLE
Nuxt, routing without initial query parameters

### ISSUE THREAD

**Issue by bootsmann95** [algolia/vue-instantsearch#867]
**Bug 🐞**
Hey Algolia

We have a solution using algolia and vue instantsearch in nuxt. All the features wors as intended and everything is good. except the routing feature in algolia.

When we load a page using the queries in algolia it has some initial parameters even thoung nothing is set in the filter yet. is there any solution to change the initial url when no filter params is set

from: 
/alle-produkter/?AHjort%20Products%20da-DK%5BsortBy%5D=AHjort%20Products%20da-DK
to:
/alle-produkter/

This is the router code: 

```
export function nuxtRouter(vueRouter: any) {
    return {
      read() {
        return vueRouter.currentRoute.query;
      },
      write(routeState: any) {
        vueRouter.push({
          query: routeState
        });
      },
      createURL(routeState: any) {
        return vueRouter.resolve({
          query: routeState
        }).href;
      },
      onUpdate(cb: any) {
        if (typeof window === "undefined") return;

        (this as any)._onPopState = (event: any) => {
          const routeState = event.state;
          if (!routeState) {
            cb(this.read());
          } else {
            cb(routeState);
          }
        };
        window.addEventListener("popstate", (this as any)._onPopState);
      },
      dispose() {
        if (typeof window === "undefined") { return; }

        window.removeEventListener("popstate",  (this as any)._onPopState);
      },
    };
}
```

And when i use the route back (popstate) i have to go back 3 times to go back the the previous page.

Tell me if you need more from me to go more in depth with this issue.

**Comment by Haroenv** [comment]
Do you have a sandbox with this issue shown?

**Comment by bootsmann95** [comment]
@Haroenv  no but i can make one, do you have a link with nuxt ssr and routing setup?

**Comment by Haroenv** [comment]
there's eg https://codesandbox.io/s/busy-cartwright-wndg6

**Comment by bootsmann95** [comment]
https://codesandbox.io/s/beautiful-cori-0ukm2?file=/pages/search.vue here is how the example looks like, it adds the queries to the url and i have to press back 3 times to go back to the frontpage

**Comment by bootsmann95** [comment]
@Haroenv hope the codesandbox helps understanding the issue, otherwise let me know. 

We're soon going in production with the website so could be nice to have this fixed before that. 

Best regards Anders.

**Comment by Haroenv** [comment]
Could you try updating `instantsearch.js` (transitive dependency) to the latest (4.8.1). You can do that either by installing it explicitly or updating your lockfile

**Comment by bootsmann95** [comment]
https://codesandbox.io/s/beautiful-cori-0ukm2?file=/pages/index.vue now ive updated the yarn.lock to instantsearch.js 4.8.2

**Comment by bootsmann95** [comment]
@Haroenv that didn't do the trick :)

**Comment by Haroenv** [comment]
I see what's going on, you weren't talking about the bug fixed in 4.8.2, but just the fact that you are pushing an URL which isn't clean to the URL when the state is clean. You can fix it like this:

1. add singleIndex stateMapping
2. use `qs` in the vue router config to allow deep objects

Here's a fixed sandbox: https://codesandbox.io/s/agitated-tu-cbh17?file=/pages/search.vue

**Comment by bootsmann95** [comment]
That got a lot better!

but there is still something not working 100%. 

i have some replicas and it seems as it applies them and then remove it from the url in the start. So i still have to go back 3 times if i set one thing in the filter. To get back to the previous page. 

e.g hjer 

https://codesandbox.io/s/great-shtern-32dhw?file=/pages/search.vue

**Comment by bootsmann95** [comment]
@Haroenv  you can see our test site here: 
https://test2.a-hjort.dk/

press the "produkter" url in the navigation and you wil get to the page with aloglia. 

as you can see it applies something fast to the url in the start and then its removed agains. So i have to pres back 2 times to get back to the frontpage.

**Comment by bootsmann95** [comment]
@Haroenv  i can see its because my price filter is programatically setting som values. so everything works now thanks a lot! do you have any codesandbox with a range slider using vue-slider?

**Comment by bootsmann95** [comment]
@Haroenv  do you have any examples with ais-range-slider using nuxt? i can't make this work.

**Comment by Haroenv** [comment]
ais-range-slider doesn't exist, which component do you mean? If you were using e.g. `vue-slider-component` it will indeed not work in server-side rendering, because that component isn't supporting SSR. You can do `client-only` around the slider component itself

**Comment by bootsmann95** [comment]
@Haroenv  I keep getting a cannot set disabled of undefined when using this example https://codesandbox.io/s/vue-instantsearch-v2-starter-forked-2xgiv?file=/src/App.vue:819-871

![image](https://user-images.githubusercontent.com/53180316/94680215-ab704d80-0321-11eb-8aa7-f87fbd16bce8.png)

**Comment by Haroenv** [comment]
```
    <ais-range-input :attribute="'salesPrice'">
      <div slot-scope="{ currentRefinement, range, refine }">
        <client-only>
          <vue-slider
            :min="range.min"
            :max="range.max"
            :lazy="true"
            :value="toValue(currentRefinement, range)"
            @input="refine({ min: $event[0], max: $event[1] })"
          />
        </client-only>
      </div>
    </ais-range-input>
```

this is what I meant. Something is weird with nuxt on codesandbox, so it's not running, but locally I have no issues with this

**Comment by bootsmann95** [comment]
@Haroenv  i get this as soon as i touch the range bar: 

![image](https://user-images.githubusercontent.com/53180316/94685320-8d0e5000-0329-11eb-8045-fff6cd899162.png)
 
can i see the javascript?

**Comment by Haroenv** [comment]
https://codesandbox.io/s/hardcore-paper-tylb4?file=/pages/search.vue

**Comment by bootsmann95** [comment]
@Haroenv  Where is your toValue()?, 

I get this in console now 
![image](https://user-images.githubusercontent.com/53180316/94685826-43723500-032a-11eb-8921-f80947ef017e.png)

**Comment by bootsmann95** [comment]
@Haroenv 
 Now is it like my toValue is behind the actual value: 

e.g: 
Here I have default values: 
![image](https://user-images.githubusercontent.com/53180316/94693239-c0ee7300-0333-11eb-8bcf-52db1bb0c1d9.png)

min: 132
max: 220
My slider handles this as intended.


Next up i change "min" value to something higher: 
![image](https://user-images.githubusercontent.com/53180316/94693408-f72bf280-0333-11eb-9227-5f812d2072a4.png)


As you can see algolia works and it's all good(almost). 
I wanna show what the selected values is, and it's like it's a step behind, as you can see the "min" value "132 kr." displayed should've been "181 kr". 

If I now change the value back to the smallest value the new displayed "min" value changes to "181" but the actual value is 132:
![image](https://user-images.githubusercontent.com/53180316/94693612-3b1ef780-0334-11eb-900c-1d4bc2003007.png)

So it's like it's one step behind the actual value. 

The displayed values are some component data values I define like this in the "toValue" function: 

```    toValue(value: any, range: any) {
        this.currentValue[0] = value.min != null ? value.min : range.min;
        this.currentValue[1] = value.max != null ? value.max : range.max;
        return [
            value.min != null ? value.min : range.min,
            value.max != null ? value.max : range.max
        ];
    }```

@Haroenv  hope it make sense else let me know, it is a bit hard to show you the issue when vue-slider-component doenst work in sandbox.

**Comment by Haroenv** [comment]
That sounds wrong indeed. Can you still make a sandbox? There's an export as zip button that I can use to view the code misbehaving on my machine

**Comment by bootsmann95** [comment]
Here you go @Haroenv https://codesandbox.io/s/holy-rain-mnbf2?file=/pages/search.vue

**Comment by Haroenv** [comment]
Not sure what I changed, but it works on codesandbox now like this: https://codesandbox.io/s/370f6?file=/pages/search.vue

see also https://github.com/NightCatSama/vue-slider-component/issues/114#issuecomment-477314787

You probably don't want a local value of the "value" if you only need to display it

**Comment by bootsmann95** [comment]
Then how could i display the value then? @Haroenv

**Comment by bootsmann95** [comment]
Thank you haroenv it all works now! THANK YOU!!

**Comment by bootsmann95** [comment]
@Haroenv  hello can you tell me why i get the query params in url with first load? 

https://codesandbox.io/s/upbeat-rubin-oqrf3?file=/pages/search.vue

**Comment by bootsmann95** [comment]
@Haroenv  if i remove sort-by it works, but with sort-by it still applies queries to url on initial load
