### ISSUE TITLE
Nuxt.js and vuex: "TypeError: Cannot read property 'state' of undefined"

### ISSUE THREAD

**Issue by eljass** [algolia/vue-instantsearch#868]
**Bug 🐞**

### What is the current behavior?
When including:
```
serverPrefetch() {
    return this.instantsearch.findResultsState(this).then(algoliaState => {
      this.$ssrContext.nuxt.algoliaState = algoliaState;
    });
  }
```

with Vuex action:
```
nuxtServerInit({ commit }) {
    commit("SET_TEST", true);
 }
```

console prints Vue warning Error in render: `[Vue warn]: Error in render: "TypeError: Cannot read property 'state' of undefined"`

I'm not sure if this is fixed two days ago with [#864](https://github.com/algolia/vue-instantsearch/pull/864), but this version is not available through npm or yarn registry. [NPM registry](https://www.npmjs.com/package/vue-instantsearch) shows the last update to made month ago.

### Make a sandbox with the current behavior
https://codesandbox.io/s/vue-instantsearch-vuex-error-1n6qp

### What is the expected behavior?
Should not have an error and vuex state should be working correctly.

### What is the version you are using?
Nuxt.js v2.12.2
vue-instantsearch v3.2.0

**Comment by Haroenv** [comment]
Hey! We’ve merged a fix for this last week, but not yet released. Will do first thing Monday!

**Comment by Haroenv** [comment]
The fix (#864) has been released in version 3.3.0 now!

**Comment by eljass** [comment]
@Haroenv do you know when this will be available in NPM registry?

**Comment by Haroenv** [comment]
Hmm, this should have been available this morning, let me check what's going on!

**Comment by Haroenv** [comment]
Fixed now @eljass 👍
