### ISSUE TITLE
Cannot read property 'count' of undefined on refinement components

### ISSUE THREAD

**Issue by singhofmarco** [algolia/vue-instantsearch#874]
**Bug 🐞**

### What is the current behavior?
Console error is shown "Cannot read property 'count' of undefined" for every refinement component since last version. Component works as expected though.

Error in callback for watcher "state": "TypeError: Cannot read property 'count' of undefined"
 
### Make a sandbox with the current behavior
https://codesandbox.io/s/nice-ives-16unm?file=/src/App.vue

### What is the expected behavior?
No error should show up in the console.

### Does this happen only in specific situations?
No.

### What is the proposed solution?
-

### What is the version you are using?
v3.4.1

**Comment by Haroenv** [comment]
not sure yet what the solution is, but I can see it came from #871
