### ISSUE TITLE
Infinite hits load previous products aswell on click back. 

### ISSUE THREAD

**Issue by bootsmann95** [algolia/vue-instantsearch#878]
### What is the current behavior?
Right now when i make a search a go though my products in ais-infinite-hits, load a few pages and click on a product on e.g page 3. 

I go to the product page and then go back it only shows the result of page 3. 

is there any way i can set some setting that loads the previous pages down to the current page?

**Comment by Haroenv** [comment]
Hi @bootsmann95, this is what infinite hits cache is for. I saw that at the moment it hadn't been documented for Vue, but it has been for InstantSearch.js, which you can find here: https://www.algolia.com/doc/api-reference/widgets/infinite-hits/js/?language=sessionStorage#widget-param-cache

The code for Vue InstantSearch is:

```vue
<template>
  <ais-infinite-hits :cache="cache" />
</template>

<script>
import {
  createInfiniteHitsSessionStorageCache
} from 'instantsearch.js/es/lib/infiniteHitsCache'

export default {
  data() {
    return {
      cache: createInfiniteHitsSessionStorageCache(),
    }
  }
}
</script>
```

**Comment by bootsmann95** [comment]
@Haroenv do I have to implement more? When i implement that code it does not work

**Comment by Haroenv** [comment]
No, this should be enough. Here's an example that shows it's working: https://codesandbox.io/s/sharp-dhawan-7qt17?file=/src/App.vue

If it doesn't work for you, please check you're on the right version of Vue InstantSearch & InstantSearch.js (latest for both)

**Comment by Haroenv** [comment]
No, this should be enough. Here's an example that shows it's working: https://codesandbox.io/s/sharp-dhawan-7qt17?file=/src/App.vue

If it doesn't work for you, please check you're on the right version of Vue InstantSearch & InstantSearch.js (latest for both)

**Comment by bootsmann95** [comment]
this doesnt work, im using the same versions of  Vue InstantSearch & InstantSearch.js as you are in code sandbox.

**Comment by Haroenv** [comment]
No, that shouldn't be related. Can you please make a sandbox that shows it's not working?

**Comment by bootsmann95** [comment]
Yes i will try use the way we do, can you link me a nuxt ssr sandbox link ? :)

**Comment by bootsmann95** [comment]
@Haroenv  Hey you can close this issue, we are manipulating the facets programatically on data properties in nuxt and this affects the cache. 

Your sandbox made this work and we can now see the previous pages aswell when we go back.

**Comment by bootsmann95** [comment]
@Haroenv  I  made it work with some upgraded, now the problem is when i use infinite scroll and go back it does not go to the saved scroll position, is there something i have to do, to make this work ?
