### ISSUE TITLE
Algolia router parameters returnining object object in url. 

### ISSUE THREAD

**Issue by bootsmann95** [algolia/vue-instantsearch#880]
**Bug 🐞**
Hello vue-instantsearch 
we're having an issue with the routing in vue instantsearch, in nuxt. 

### What is the current behavior?
Every time we make a change in the filters we get the parameters:
![image](https://user-images.githubusercontent.com/53180316/97273437-a4126600-1833-11eb-992a-4f312d8a7ad6.png)

### Make a sandbox with the current behavior
We made a code sandbox trying to replicate the behavior but could not make this hapend. this is what we have now in the component: 

Template: https://codesandbox.io/s/prod-resonance-95pu7?file=/pages/search.vue

we have tried to cut it to the bone and make as few changes as possible and now it looks exactly like in the codesandbox. But we still get this url, do you have any idea of why? 

Thank you in advance

**Comment by Haroenv** [comment]
If you're using Vue Router, you need to set it up to allow complex URLs like this: https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/#combining-with-vue-router

```js
import qs from 'qs';

const router = new Router({
  routes: [
    // ...
  ],
  // set custom query resolver
  parseQuery(query) {
    return qs.parse(query);
  },
  stringifyQuery(query) {
    const result = qs.stringify(query);

    return result ? `?${result}` : '';
  },
});
```

Your sandbox works because of these lines in nuxt.config.js:

```js
/* eslint-disable import/no-commonjs */

module.exports = {
  build: {
    transpile: ["vue-instantsearch", "instantsearch.js/es"]
  },
  router: {
    parseQuery(q) {
      const qs = require("qs");

      return qs.parse(q);
    },
    stringifyQuery(q) {
      const qs = require("qs");

      const queryString = qs.stringify(q);
      return queryString ? "?" + queryString : "";
    }
  }
};
```

**Comment by bootsmann95** [comment]
Yes but this is what we have in the nuxt.config.js: 

![image](https://user-images.githubusercontent.com/53180316/97275152-dde46c00-1835-11eb-95d1-b2b64b9b967c.png)

**Comment by Haroenv** [comment]
it woks in the sandbox, I see you have routes set to an empty array, maybe that has an impact? Could you edit the sandbox to also not work?

**Comment by bootsmann95** [comment]
it's because we use extendRoutes to create the router. hmmm can try, was also more to hear if you had an idea why this is happening. We get the indexname and then object object in url, but i'll try recreating the bug in codesandbox again,

**Comment by bootsmann95** [comment]
now im getting this: 
![image](https://user-images.githubusercontent.com/53180316/97280963-353a0a80-183d-11eb-882a-dedcf0520564.png)

**Comment by bootsmann95** [comment]
@Haroenv 

![image](https://user-images.githubusercontent.com/53180316/97281745-27d15000-183e-11eb-9cdf-7964ca675c03.png)
 

if i have my router like this( with the console logs) 


i only hit the read event? is that as intended? 
![image](https://user-images.githubusercontent.com/53180316/97281836-41729780-183e-11eb-8892-278723139788.png)

**Comment by Haroenv** [comment]
sorry, but as we said before, without a failing _live_ example, it's impossible to debug

**Comment by bootsmann95** [comment]
I found a solution:

- uninstalled alogliasearch & vue-instantsearch
- updated nuxt from "2.14.0" ->  "2.14.6"
- installed algolia search & vue instantsearch
- changed nuxtRouter(this.$nuxt.$router) -> nuxtRouter(this.$router)

and then it worked.
