### ISSUE TITLE
Standard facet filtering

### ISSUE THREAD

**Issue by Geoffry304** [algolia/vue-instantsearch#881]
**Bug 🐞**

### What is the current behavior?

Using standard facet filters with the button 'changeFilter' in the sandbox, when I pressed the button and then filter on a category the standard facet filter is gone.

### Make a sandbox with the current behavior

https://codesandbox.io/s/elated-firefly-ubmr4

### What is the expected behavior?
That the standard filter stays and that the filtering on category and other facets works

### What is the version you are using?
latest version
> Always try the latest one before opening an issue.

**Comment by Haroenv** [comment]
You can set the ui state from a custom component instead of the filters. The search state will be overridden when controlled by another component, but the uiState will stay.

here's an example: https://codesandbox.io/s/crazy-keller-5tf6q?file=/src/CustomComponent.vue

**Comment by Geoffry304** [comment]
Thank you, but what I like on the way I am doing it is that only the filters will show that I want to have for filtering.
For example, I am making an app with tickets so I want to have my personal list filtered for myself together with some statuses.
Is there a way to do that?

**Comment by Haroenv** [comment]
Hey Geoffry, I don't understand what you mean. Could you show this with an example in the sandbox? Is there a website which behaves how you want it?

**Comment by Geoffry304** [comment]
Hello Haroen, Well if you check my sandbox link, when clicking on the button changeFilter you have only HP and Apple where you can choose from. 
For example if you go to the website of https://www.coolblue.be/en/laptops you have the filters on top 
![image](https://user-images.githubusercontent.com/3656871/97565234-2c386d00-19e6-11eb-9ca5-6b7775aba4f3.png)

Business laptops will have some standard filters, like maybe every business laptop needs to have 8gb ram or more, so the 4gb doesn't need to be shown, together with a screen size of 15inch, ...

I hope you understand it now? :)

Thx in advance!

**Comment by eunjae-lee** [comment]
Hey @Geoffry304 , I think I get it.

In this case you can provide `initialUiState`.
https://codesandbox.io/s/strange-pasteur-bolpv?file=/src/App.vue:1752-1960

Assuming you have your conditions per sub menu (Business laptops, Acer, ...) on the frontend,
you can specify initialUiState like

```js
      {
        [indexName]: {
          query: 'a',
          refinementList: {
            brand: ['Apple', 'Samsung']
          },
          range: {
            price: '100:400'
          }
        }
      }
```

You can hide some facets via `transform-items` if you want. It's addressed in the example.
Let me know if it works for you and if you have any question.
