### ISSUE TITLE
Outdated docs for routing urls in Nuxt.js

### ISSUE THREAD

**Issue by eljass** [algolia/vue-instantsearch#883]
**Bug 🐞**

### What is the current behavior?
[Docs](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/#combining-with-nuxtjs) says that when using Nuxt.js routing server root mixin creation should look like this:
```
...
data() {
    // Create it in `data` to access the Vue Router
    const mixin = createServerRootMixin({
      searchClient,
      indexName: 'instant_search',
      routing: {
        router: nuxtRouter(this.$nuxt.$router),
      },
    });
    return {
      ...mixin.data(),
    };
  },
...
```

This although does not work for me in Nuxt v.2.14.7 since `Cannot read $router of undefined` when trying to render search page in server-side. Client-side rendering worked as expected but refreshing the page or navigating straight to its URL did not.

Fix for this was to change `router: nuxtRouter(this.$nuxt.$router)` to `router: nuxtRouter(this.$router)`

### What is the version you are using?
"algoliasearch": "^4.5.1",
"nuxt": "^2.14.7",
"vue-instantsearch": "^3.4.2"

**Comment by Haroenv** [comment]
Thanks for noticing this, I've made a pr to our documentation, this issue will automatically close when the PR is merged 👍
