### ISSUE TITLE
no results using infinite-scrolling component with ais-configure filters

### ISSUE THREAD

**Issue by gqoew** [algolia/vue-instantsearch#884]
**Bug 🐞**

I followed the [tutorial](https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/infinite-scroll/vue/#overview) for infinite scrolling. I implemented the `infiniteHitsComponent` component, a listener on the scroll event that is called when the list of results reaches.

In parrallel, I use `ais-configure` combined with 2 buttons in a sidebar to filter search results. Here is my code, simplified: 

```vue
    <ais-instant-search :search-client="searchClient" index-name="INDEX_NAME">

        <ais-configure v-if="$store.state.privateTabActive" :filters="$store.getters.filtersPrivate"/>
        <ais-configure v-else-if="$store.state.publicTabActive" :filters="$store.state.filtersPublic"/>

        <button @click="$store.state.privateTabActive = true; $store.state.publicTabActive = false;">private<button>
        <button @click="$store.state.privateTabActive = false; $store.state.publicTabActive = true;">public<button>

        <ais-state-results>
            <infiniteHitsComponent/>
        </ais-state-results>

    </ais-instant-search>
```

Here are my filters:

```
filtersPublic: 'visibility: "public"'
filtersPrivate: state => {
    return `author:${state.user.uid}`;
}
```

The infinite scroll works great when I use it within the same sidebar filtering button, but as soon `this.state.showMore()` is called by the `infiniteHitsComponent` component, clicking on the other sidebar button generate no results where I should have a non-empty list of filtered-results. Also, if I start typing in the searchbar a keyword afterwards, filtered results are re-appearing.

Is this a problem coming from using `ais-configure `? Is there a way to reset the `state`? I to solve this by [refreshing the cache](https://www.algolia.com/doc/guides/building-search-ui/going-further/improve-performance/vue/#refresh-the-cache-triggered-by-an-action-from-the-user) but it did not work.

Thank you for your help

**Comment by Haroenv** [comment]
Could you reproduce this in a sandbox? We have a starter available here: https://codesandbox.io/s/ecstatic-matsumoto-hbuzw?file=/src/App.vue

I wonder if it might be related to nesting in ais-state-results without using the slot-scope, is that on purpose?

**Comment by gqoew** [comment]
hi @Haroenv Here is the sandbox: https://codesandbox.io/s/white-lake-0slup

For some reasons it works well, except when I scroll down very quickly to 100+ results in Apple tab then switch to Sony tab 😮 

Not sure where the problem is from... maybe the index itself?

**Comment by eunjae-lee** [comment]
Hey @gqoew , from what I'm seeing, when switching tabs, `page` parameter remains the same.
For example, you go to the last page of apple results (let's say page=25), and if you go to sony tab, it requests for the result of page=25 and it doesn't exist.

I've updated your example to reset to the first page when switching tab.
https://codesandbox.io/s/objective-cerf-gwikd?file=/src/App.vue:357-700

Let me know how it goes.

**Comment by gqoew** [comment]
Hi @eunjae-lee 

Thank you for taking the time to look at my issue 🙏 Reseting to the first page when switchting tabs made the trick 👌
