### ISSUE TITLE
AisSearchBox is not showing when using a :search-function prop on ais-instant-search

### ISSUE THREAD

**Issue by teundirectlease** [algolia/vue-instantsearch#885]
**Bug 🐞**

### What is the current behavior?
When adding a searchFunction to ais-instantsearch:
```
 <ais-instant-search
            :search-client="searchClient"  :index-name="indexUrl"
            :search-function="myFunction"
        >
```
The searchBox only shows when i call helper.search() So in this case my searchbox won't show:
```
This does not work:
  myFunction(helper) {
                if(helper.state.query) {
                    helper.search();
                }
            },
```
But when i call helper.search() directly the searchbox will show

My layout:
 ```
<ais-instant-search
            :search-client="searchClient"  :index-name="indexUrl"
            :search-function="myFunction">
            <ais-search-box :placeholder="searchBalkPlaceHolder"/>
            <ais-configure :restrictSearchableAttributes="searchAttributes" />
            <ais-state-results class="position-absolute white ais-state-results-wrapper" v-if="aboveBreakpoint">
                <search-bar-list slot-scope="{ state: { query }, results: { hits } }" :items="hits" v-show="query"></search-bar-list>
            </ais-state-results>
             <ais-state-results v-else class="col-12 position-fixed white ais-state-results-wrapper">
                <search-bar-list slot-scope="{ state: { query }, results: { hits } }" :items="hits" v-show="query"></search-bar-list>
             </ais-state-results>
        </ais-instant-search>
```

Im not getting any console ERROR logs in the browser. 

### What is the expected behavior?
To show the search box but do not a query call on start.

### What is the version you are using?
    "algoliasearch": "^4.6.0",
    "vue-instantsearch": "^3.4.2",
    "vue": "^2.6.10",

> Always try the latest one before opening an issue.

**Comment by Haroenv** [comment]
If you do not search with the search function, none of the widgets will render, since they need results to display. What's the use case you're using search-function for? It likely can be solved more efficiently with a custom search client like this: https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-requests/vue/

**Comment by teundirectlease** [comment]
@Haroenv You are right that will fix my problem, all i want to do is basicly check if my query is empty so that i not fire a query on page mount.

But is it just me or are the docs here telling me it should work: 
https://www.algolia.com/doc/api-reference/widgets/instantsearch/vue/#widget-param-search-function

**Comment by Haroenv** [comment]
Ah yes, that example is bad indeed, I'll update it to be something more fitting

**Comment by teundirectlease** [comment]
@Haroenv thanks, the problem with the https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-requests/vue/ solution is that i can now not acces my variables given to the vue component. In my case i serverside render a template parsing props from a yaml with php so that only not trusted data goes to the client. Outside the export default tags i can't acces it the freaking keys :P. Setting the keys later on mount does not seem to work and with vue accessing props outside the export default scope is not possible.

**Comment by Haroenv** [comment]
I'm not sure I understand your issue @teundirectlease, where are the credentials created and where can't you access them?

**Comment by teundirectlease** [comment]
@Haroenv A collega fixed it for me, i had to use an arrow function to parse props but it works now. many thanks :-D
