### ISSUE TITLE
How can I performed a search on submit

### ISSUE THREAD

**Issue by DavidStrada** [algolia/vue-instantsearch#889]
Currently I'm using `ais-menu-select` to filter data base on `attributes` plus have an `ais-search-box`, everything works, but I have a requirement to performed a search + filters on submit, I've gone over docs and examples but haven't been able to find anything on regards to this use-case.

Any advice, 
Thanks.

**Comment by Haroenv** [comment]
I'm not sure what kind of experience you're describing, do you have an example of what the submit button should do? Could something like routing be what you're looking for?

**Comment by DavidStrada** [comment]
@Haroenv the experience is the following instead of doing everything when you click on a filter, display results or searching for something, wait until you hit submit and do the action.

**Comment by Haroenv** [comment]
This isn't something that the instantsearch family has out of the box, on purpose, since the instant search experience is possible. The way to go if you want submit buttons is to make custom widgets that each have their submit button, or to not use InstantSearch at all :)
