### ISSUE TITLE
Filters are behaving differently than facet filters

### ISSUE THREAD

**Issue by ashwinmram** [algolia/vue-instantsearch#897]
**Bug 🐞**
I'm not sure if this is a syntax issue on my part, but here goes!

### What is the current behavior?
```jsx
<ais-configure
      filters="hotel_id:1 AND status:checked_in OR status:due_out"
></ais-configure>
```

Using the above code I start out with a filtered set based on the above parameters, then the refinement list components will work in conjunction with the above filters.

When I use facet filters it doesn't have the same behavior.  It filters based on the parameters, and when I apply the refinement it filters further, but when I untick the refinement it doesn't change back.

```jsx
<ais-configure
      :facet-filters.camel="['hotel_id:1',['status:checked_in','status:due_out']]"
></ais-configure>
```

### Make a sandbox with the current behavior

Template: https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch

I've never created a code sandbox so please give me some time to add this for you.

### What is the expected behavior?

I expect both `<ais-configure>` components above to be interchangeable.

### Does this happen only in specific situations?

It seems to be in general (not specific situations).

### What is the proposed solution?

I think the combination of the facet filters from `<ais-configure>` to be combined with the refinement list filters as a new facet filter set.  When the refinement list is reverted back the facet filter set doesn't appear to change back.

### What is the version you are using?

2.7.1 but I'm using Vue 2

I tried upgrading the the latest version but it broke my app :(

Wait I see that the latest version is compatible with Vue 2.  Please allow me to keep this open while I attempt the upgrade with the proper peer dependencies etc.

> Always try the latest one before opening an issue.

**Comment by ashwinmram** [comment]
Fixed with upgrade... so sorry!!

**Comment by Haroenv** [comment]
No worries, glad you found the solution!
