### ISSUE TITLE
select multiple compatibility

### ISSUE THREAD

**Issue by MohamedAhmed12** [algolia/vue-instantsearch#901]
I'm using vue-multiselect and I want to use the method refine() with it but I can't do it, I don't know how and I've tried many things but didn't work,

**Comment by yannickcr** [comment]
The `refine` function is available in the default scope for the ais-refinement-list widget https://www.algolia.com/doc/api-reference/widgets/refinement-list/vue/#widget-param-default.

Here's an example of Vue InstantSearch with vue-multiselect: https://codesandbox.io/s/beautiful-clarke-otlxm?file=/src/App.vue
