### ISSUE TITLE
Hi @msassa, sorry about the delayed answer. We didn't find a proper solution to fix the issue yet inside Vue InstantSearch. The root of the issue come from [an internal function of InstantSearch.js](https://github.com/algolia/instantsearch.js/issues/3278). It happens because the `ais-configure` widget triggers a useless re-render. Most of the time, this is because a value is inlined inside the template. Here it's not the case. It happens because we use `$attrs` to allow any props provided to the widget to be used as parameters. The downside of this is that the reference change between render which triggers an internal update for Vue InstantSearch.

### ISSUE THREAD

**Issue by profhouse** [algolia/vue-instantsearch#902]
Hi @msassa, sorry about the delayed answer. We didn't find a proper solution to fix the issue yet inside Vue InstantSearch. The root of the issue come from [an internal function of InstantSearch.js](https://github.com/algolia/instantsearch.js/issues/3278). It happens because the `ais-configure` widget triggers a useless re-render. Most of the time, this is because a value is inlined inside the template. Here it's not the case. It happens because we use `$attrs` to allow any props provided to the widget to be used as parameters. The downside of this is that the reference change between render which triggers an internal update for Vue InstantSearch.

The only workaround we've found is to re-implement the `ais-configure` widget with the mixin that we expose with Vue InstantSearch. With this solution, you can expose a prop on the widget that takes an object which contains a list of search parameters to apply on the request. Here is the implementation (see below). You can find a complete example on [CodeSandbox](https://codesandbox.io/s/yj2n2k79xz).

```js
import { createWidgetMixin } from 'vue-instantsearch';
import { connectConfigure } from 'instantsearch.js/es/connectors';

export default {
  name: 'CustomConfigure',
  mixins: [createWidgetMixin({ connector: connectConfigure })],
  props: {
    parameters: {
      type: Object,
      required: true,
    },
  },
  computed: {
    widgetParams() {
      return {
        searchParameters: this.parameters,
      };
    },
  },
  render() {
    return null;
  },
};
```

You can use it like this:

```vue
<template>
  <!-- ... -->
  <custom-configure :parameters="parameters" />
</template>

<script>
export default {
  data() {
    return {
      //...
      parameters: {
        hitsPerPage: 4
      }
    };
  }
};
</script>
```

Hope that helps, let us know if it fixes your issue or if you have any questions.

_Originally posted by @samouss in https://github.com/algolia/vue-instantsearch/issues/663#issuecomment-489695804_

**Comment by Haroenv** [comment]
Closing this, since it's a copy of a different issue. Please feel free to open a new issue with the problem you're having, following the template!
