### ISSUE TITLE
line breaks in ais-highlight

### ISSUE THREAD

**Issue by dseeger** [algolia/vue-instantsearch#903]
Is there a way to display line breaks in ais-highlight?

I tried the following, but that also doens't work as it will all be wrapped as a string, so the <br> will be printed

```
transformItems(items) {
    return items.map(item => {
        item._highlightResult.fakeName = {
            value: item._highlightResult['description'].value.replace(/(?:\r\n|\r|\n)/g, '<br>'),
        };

        return item;
    });
},
```

**Comment by yannickcr** [comment]
It is not possible with the existing `ais-highlight` widget. It only displays plain text to avoid XSS. 

If you want to display some HTML you may want to create your own component for that using the [`v-html` directive](https://vuejs.org/v2/guide/syntax.html#Raw-HTML ). You can also use the [existing `ais-highlight` component](https://github.com/algolia/vue-instantsearch/blob/master/src/components/Highlight.vue) as an inspiration.

**Comment by Haroenv** [comment]
If you want to display newlines (the unicode style), you can also set `white-space: pre` to the container, which should display the requested newlines.

**Comment by dseeger** [comment]
Thanks for the input! I guess I'll make a new component for that.
