### ISSUE TITLE
nuxt jest unexpected token export

### ISSUE THREAD

**Issue by toyflish** [algolia/vue-instantsearch#910]
**Bug 🐞**

### What is the current behavior?
on `yarn test` jest runner throws error when importing instantsearch

    /Users/kai/dev/nuxt-jest-instantsearch/node_modules/instantsearch.js/es/lib/routers/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { default as history } from './history';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'

     import { history as historyRouter } from 'instantsearch.js/es/lib/routers'

### Make a sandbox with the current behavior

a minimal repo can be found here [nuxt-jest-instantsearch](https://github.com/toyflish/nuxt-jest-instantsearch)
the import to instantsearch is  [instantsearch.spec.js](https://github.com/toyflish/nuxt-jest-instantsearch/blob/main/test/instantsearch.spec.js) 

the transformIgnorePatterns fix from #588 is already applied to jest.config.js 

### What is the expected behavior?
no error Syntaxerror should occur

### Does this happen only in specific situations?
on running jest

### What is the version you are using?

    ├─ instantsearch.js@4.10.0
    ├─ vue-instantsearch@3.4.3
    │  └─ instantsearch.js@^4.7.0

**Comment by eunjae-lee** [comment]
Hello @toyflish 
It seems like you need to convert your `.babelrc` to `babel.config.js`.
https://github.com/facebook/jest/issues/10256

**Comment by toyflish** [comment]
@eunjae-lee that fixed it, thanks so much!
