### ISSUE TITLE
Nuxt Routing issue when I follow vue-instantsearch document?

### ISSUE THREAD

**Issue by gfd6th** [algolia/vue-instantsearch#911]
https://codesandbox.io/s/sweet-haslett-y7lnq?file=/pages/index.vue
I made this codesandbox to debug.
I checked twice with document, https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/#combining-with-nuxtjs
 I think I do the same with document, but I could not get result as desire.

Issue 1: The searchbox input only allow one charactor.
Issue 2: Refine and menu could not work

**Comment by eunjae-lee** [comment]
Hello @gfd6th, sorry for the trouble. I'm taking a look into the issue right now. I'll let you know as soon as I figure out something.

**Comment by Haroenv** [comment]
I found that this behaviour only shows up with InstantSearch 4.9.0+, so if you want a quick workaround, you can install `instantsearch.js@4.8.7` in your project, and that will not have the issue!

**Comment by Haroenv** [comment]
We have pointed the bug down to this change, but not yet what's the correct behaviour: https://github.com/algolia/instantsearch.js/commit/c2f35464b347817152d5936e66252ac03e38794e#diff-fc3d2403c81ac8eda4a7c4982cfbfff1017b041f08bba731cac19cd47bb8e33d

**Comment by gfd6th** [comment]
@halley124 ha 
Thanks for your help, I return vue-instancesearch back to 3.4.2

**Comment by Haroenv** [comment]
here's how to fix it temporarily (using yarn): https://codesandbox.io/s/repro-without-issues-uohwg @gfd6th

**Comment by Haroenv** [comment]
If you reinstall your project now (make sure you have InstantSearch.js 4.13.1 in your lock file), the issue will have disappeared :)

**Comment by gfd6th** [comment]
@Haroenv Will it be fixed in the next version of vue-instantsearch?

**Comment by Haroenv** [comment]
It's already fixed in the current version of Vue InstantSearch @gfd6th, the downstream fix is done in InstantSearch.js, and since Vue InstantSearch has InstantSearch.js as a dependency, you will get the fix by updating your lockfile :)

**Comment by gfd6th** [comment]
It seems have some issue when you go back at router history. 
see your fork  https://codesandbox.io/s/zealous-firefly-2vktb?file=/package.json
If you change menu category, and then click browser back button. 
The url changed, but the state keep same
