### ISSUE TITLE
Can I use vue-instantsearch with other search libraries like Elasticsearch?

### ISSUE THREAD

**Issue by 684efs3** [algolia/vue-instantsearch#915]
Can I use vue-instantsearch with other search libraries like Elasticsearch? Or is this only for Algolia?

**Comment by Haroenv** [comment]
Sorry, I can't answer that question, since we haven't made an official policy. In theory it's possible to use with any backend if you translate the parameters and the response.

**Comment by francoischalifour** [comment]
The [**Backend InstantSearch**](https://www.algolia.com/doc/guides/building-search-ui/going-further/backend-search/in-depth/backend-instantsearch/vue/) guide should be helpful.
