### ISSUE TITLE
SSR with initialization on layout

### ISSUE THREAD

**Issue by nothaldir** [algolia/vue-instantsearch#917]
Hi!
I'm trying to develop a particuliar behaviour with instant-search-ssr and nuxt.

Basically, instead of having the search-box alongside the results on a page, I want it inside my header, which is in my default layout (clicking on the search bar is redirecting to the results page).

And I'm having troubles making everything work smoothly between my layout and my results page with the different ssr functions (`createServerRootMixin`, `beforeMount` and `serverPrefetch`). Is there a specific documentation/example for such an implementation?

If I try having `beforeMount` and `serverPrefetch` inside the results page, then I'm having a `this.instantsearch is undefined` error.

**Comment by eunjae-lee** [comment]
Hello @nothaldir ,
One thing I can think of is having a dedicated layout for the search result page. The layout will contain the same header from the default layout (you may want to extract them as a component).
Inside the `SearchLayout.vue` you can wrap things with `<ais-instant-search-ssr>...</ais-instant-search-ssr>`. Will it work for you?
