### ISSUE TITLE
Allow multiple attributes for "ais-refinement-list"

### ISSUE THREAD

**Issue by ssws** [algolia/vue-instantsearch#929]
**Feature ⚡️**

### What is your use case for such a feature?

We would like to have a single list made from multiple attributes.
In our specific case we have two attributes "Region" and "Municipality" and we would like to have a single search box that searches through both.

### What is your proposal

The 'attribute' props should accept an array of attributes. 

### What is the version you are using?

>   "vue-instantsearch": "3.0.3"

**Comment by Haroenv** [comment]
Unfortunately this isn't possible on the engine side, only a single facet is searchable per query. If you want to combine the values, you can create a third "location" attribute that could be an array of [region, municipality]. At that point you will be able to search on the location facet in Vue InstantSearch

**Comment by ssws** [comment]
Thanks for the answer,
we're now evaluating the benefits of creating another attribute VS going for another type of UI/Widget.

For example: would it be possible to specify an hierarchy "Region > Municipality" and use a <ais-hierarchical-menu> with a custom UI to display all options in one list?

**Comment by Haroenv** [comment]
Do you have a mockup of the final UI you want to create here? I think there's some options, but would like to be sure before making a wrong example :)

**Comment by MTxx87** [comment]
Sure. I hope the image below clarifies.

![filter-list](https://user-images.githubusercontent.com/12138301/111287356-704da680-8643-11eb-8b56-d8a3bb13bc25.jpg)

**Comment by Haroenv** [comment]
Thanks, that makes sense. In that case I would suggest creating a third attribute which is the flat combination of region and municipality as I initially suggested!
