### ISSUE TITLE
Hierarchical Menu including `?page` data when in the route state

### ISSUE THREAD

**Issue by jonathan-bird** [algolia/vue-instantsearch#932]
**Bug 🐞**

### What is the current behavior?
`<ais-hierarchical-menu />` is including the `?page=X` data when it's in the route state. I've had issues where Google is crawling through this ?page=X data through all the categories because of this. It doesn't make sense if you go from `?page=5` to another category, that it stays on page 5.

Maybe I have set something up wrong? I have recreated (roughly) a demo sandbox below.

I understand the entire app all uses the `createURL` method, however I couldn't find a way to basically disable the inclusion of the `page` parameter for the sidebar `<ais-hierarchical-menu />`.

I noticed on my live site, when clicked, it does remove the ?page=X param, but if I open it in a new tab (as Google would crawl it), it stays in it. Really strange.

I have noticed other demo's also have this behaviour (set to page 3, then hover over sidebar categories to see that all URLs now include page 3 which you cannot assume since one category might have 1 page, also logically it makes no sense to be on page 3 on other categories): https://v2--vue-instantsearch.netlify.app/examples/ecommerce/index.html?page=3

If you test the behaviour in Algolia UI in the Browse screen in the index, it responds correctly and this case doesn't happen. If you're on page 3, and you set a category, it resets back to page 1 which is correct behaviour.

Any help appreciated!

### Make a sandbox with the current behavior
Click on the link below, click Page 3 down the bottom, and then you see the sidebar categories now all include ?page=3.

https://codesandbox.io/s/vue-instantsearch-broken-page-query-param-forked-nwh3u?file=/src/App.vue

### What is the expected behavior?
Hierarchical Menu URL does not include `?page=X` as part of the URL when created.

**Comment by Haroenv** [comment]
Hey @jonathan-bird, you're right, this is indeed a bug. I'm investigating to find on which level it should be fixed. Thanks for reporting!

**Comment by jonathan-bird** [comment]
Great, thanks @Haroenv! I managed to get a temp fix in locally but it was so hacky, so glad it is a bug that can be fixed. I got as deep as the HierarchicalMenuList createURL method that handles it all.

**Comment by jonathan-bird** [comment]
Hey @Haroenv, did you end up finding out on what level the bug is in? I found a demo using instantsearch.js today that didn't have the bug so maybe in this repo. Let me know if I can help at all

**Comment by Haroenv** [comment]
Yes, the bug is at the level of InstantSearch connectors, and as far as I can tell it isn't only hierarchical menu. I'm surprised you saw a url where this isn't the case, do you have that online somewhere?

**Comment by jonathan-bird** [comment]
@Haroenv Yeah it was here: https://instantsearchjs.netlify.app/examples/e-commerce/search/Cars/?page=3

The page is set in the URL, hover over the hierarchical menu items and you won't see any page parameter.

**Comment by Haroenv** [comment]
It would be cool if you could try out https://github.com/algolia/instantsearch.js/pull/4679 (the codesandbox install link will be commented soon) in your application :)

**Comment by jonathan-bird** [comment]
Looks to work @Haroenv! 

Here's a tweaked rough code sandbox showing it in action with routing & hierarchical menu: https://codesandbox.io/s/instantsearchjs-forked-pgrci?file=/src/app.js

**Comment by jonathan-bird** [comment]
Hey @Haroenv, do you know if it'd be long for a release of this one? Just working out whether I should add my temp fix live or wait for a release. Thanks! 😊

**Comment by Haroenv** [comment]
The PR touches a lot of moving parts, which makes reviewing complicated, so best to rely on the patch InstantSearch version for your version, but I'll make sure to close this issue once it's ready!
