### ISSUE TITLE
Documentation inclusion of rel=prev & rel=next into page head when using pagination.

### ISSUE THREAD

**Issue by jonathan-bird** [algolia/vue-instantsearch#933]
Feature request to include documentation on having InstantSearch include `rel="prev"` and `rel="next"` into the <head> of the page when using the pagination module.

I read the documentation and found brief information on this, but there was no demo or documentation on how to actually achieve this.

Although Google have stated they don't use this as a factor anymore, we have found their indexing gets confused on large sites. We've also heard from Google that they highly recommend keeping this as they *do* still use it, as do Bing.

Do you have any suggestions on how best to achieve this?

**Comment by Haroenv** [comment]
Good question, the default component indeed doesn't use this, since it's not a standard tag, but you can fill in the slot="previous" and slot="next" in the ais-pagination to add these rel props. Is this something you've tried and got stuck on?

**Comment by jonathan-bird** [comment]
@Haroenv I didn't really know where to start to be honest since the InstantSearch component is within the body, and this needs to basically be injected into the `<head>` of the page. I figured anything that used the slots would just go into that section.

**Comment by Haroenv** [comment]
Wait, could you clarify which rel=next and previous you want? I thought you could add it to any link on the page (in this case using the slots.

Maybe something like Vue-meta in an additional pagination component could work?

**Comment by jonathan-bird** [comment]
@Haroenv Great thinking. This is what I've come up with. Unsure about my approach to accessing the state, but seems to work nicely.

Simply add it as a component in the main InstantSearch component and include it as you would any other one.

Then in the `instantsearch-rel-prev-next.js` file:

```
import { connectPagination } from 'instantsearch.js/es/connectors';
import { createWidgetMixin } from 'vue-instantsearch';

export default {
    mixins: [createWidgetMixin({ connector: connectPagination })],
    data() {
        return {
            rel: {
                prev: false,
                next: false,
            }
        };
    },
    computed: {
        paginationLinks () {
            const nextUrl = { rel: 'next', href: this.rel.next }
            const previousUrl = { rel: 'prev', href: this.rel.prev }

            return [nextUrl, previousUrl].filter(({ href }) => !!href)
        }
    },
    metaInfo () {
        return {
            link: this.paginationLinks
        }
    },
    watch: {
        'state.currentRefinement'(currentRefinement) {
            const indexName = this.instantSearchInstance.indexName;
            const pagination = this.instantSearchInstance.renderState[indexName].pagination;

            this.rel.prev = !pagination.isFirstPage ? pagination.createURL(currentRefinement - 1) : false;
            this.rel.next = !pagination.isLastPage ? pagination.createURL(currentRefinement + 1) : false;
        },
    },
    render() {
        return null;
    },
};
```

What do you think?

**Comment by jonathan-bird** [comment]
Quick update, I found this worked better as I found an edge case in my one above that when you change your query param, the current refinement doesn't change (obviously) so watching for change of both current refinement + pages works well.

```
import { connectPagination } from 'instantsearch.js/es/connectors';
import { createWidgetMixin } from 'vue-instantsearch';

export default {
    mixins: [
        createWidgetMixin({ connector: connectPagination }),
    ],
    data() {
        return {
            rel: {
                prev: false,
                next: false,
                canonical: false,
            }
        };
    },
    computed: {
        paginationLinks () {
            const nextUrl = { rel: 'next', href: this.rel.next }
            const previousUrl = { rel: 'prev', href: this.rel.prev }
            const canonicalUrl = { rel: 'canonical', href: this.rel.canonical }

            return [nextUrl, previousUrl, canonicalUrl].filter(({ href }) => !!href)
        }
    },
    metaInfo () {
        return {
            link: this.paginationLinks
        }
    },
    methods: {
        handleSeoLinkRel() {
            const indexName = this.instantSearchInstance.indexName;
            const pagination = this.instantSearchInstance.renderState[indexName].pagination;
            const currentRefinement = pagination.currentRefinement;

            this.rel.prev = !pagination.isFirstPage ? pagination.createURL(currentRefinement - 1) : false;
            this.rel.next = !pagination.isLastPage ? pagination.createURL(currentRefinement + 1) : false;
            this.rel.canonical = pagination.createURL(currentRefinement);
        }
    },
    watch: {
        'state.currentRefinement'(currentRefinement) {
            this.handleSeoLinkRel();
        },

        'state.pages'(pages) {
            this.handleSeoLinkRel();
        }
    },
    render() {
        return null;
    },
};
```

**Comment by Haroenv** [comment]
Those look like really good options! If anyone else also is interested in this, could you also add the rendering part?

**Comment by jonathan-bird** [comment]
@Haroenv What do you mean by the rendering part? Vue-meta handles all the management of the <link rel=""> fields in the page <head>.

**Comment by Haroenv** [comment]
I see, I glanced over `metaInfo`. Thanks a lot! for now this issue can be closed I think
