### ISSUE TITLE
Feature: HierarchicalMenu implemented as select option

### ISSUE THREAD

**Issue by CSalih** [algolia/vue-instantsearch#938]
**Feature ⚡️**

Hello guys,

### What is your use case for such a feature?
The HierarchicalMenu(List) component will currently rendered as a `<ul>`/`<li>` with less nesting its fine to use. On mobile/table this is not really handy, specially with long labels.  

### What is your proposal
How about implementing something like HierarchicalMenuSelectList, using multiple MenuSelect's instead of a nested List?
An example output would something like:  

`<div><select>**lvl0 items**</select></div>`

After selecting a lvl0 item  and with a not empty item.data

`<div><select>**lvl0 items**</select><select>**lvl1 items**</select></div>`

**Comment by Haroenv** [comment]
This can be done quite easily using the slot of hierarchical menu like this: https://codesandbox.io/s/elastic-tree-1d074?file=/src/List.vue

Is this what you were looking for?

**Comment by CSalih** [comment]
Thank you for the quick response! Thats what i'm looking for. 

That's much easier than i thought.

**Comment by Haroenv** [comment]
Perfect, have a nice day!
