### ISSUE TITLE
Aisinstantsearch SSR loadmore and loadprevious not working smoothly

### ISSUE THREAD

**Issue by sabir-jamia** [algolia/vue-instantsearch#945]
**Bug 🐞**

### What is the current behavior?
I am using **connectInfiniteHitsWithInsights** connector with routing url and ssr (nuxt).
First a paginated page is loaded having url "https://localhost:3000/products/search?query=beds&page=10&sortBy=products", the data is correctly shown for the page 10 and "load more" and "load previous" buttons are shown. when "load more" is clicked 2 times, still data is loaded and shown correctly. after that when a "load previous" is called, data is not loaded, we have to click 2 times more to get the previous data.   

### Make a sandbox with the current behavior

https://codesandbox.io/s/gracious-ardinghelli-dxncb

### What is the expected behavior?
load previous should work smoothly every time

### Does this happen only in specific situations?
yes only when we are on a specifice page like page=3 and delete the sessionstorage data.

### What is the proposed solution?
retrieve the cached hits inside "getShowPrevious" and "getShowMore" inside connectors/connectInfiniteHits.js

we need to fetch cached data inside  getShowPrevious like below.

```
const getShowPrevious = (
      helper: Helper,
      state: Any
    ): (() => void) => () => {
      // Using the helper's `overrideStateWithoutTriggeringChangeEvent` method
      // avoid updating the browser URL when the user displays the previous page.
       var cachedHits = cache.read({
          state: state
        }) || {};

      helper
        .overrideStateWithoutTriggeringChangeEvent({
          ...helper.state,
          page: getFirstReceivedPage(helper.state, cachedHits) - 1,
        })
        .searchWithoutTriggeringOnStateChange();
    };
```

### What is the version you are using?
Nuxt: 2.15.0
vue-instantsearch: 3.6.0
algoliasearch: 4.8.4,

> Always try the latest one before opening an issue.

**Comment by nagarro-parth** [comment]
Thanks Sabir,

This helped me in solving a long standing bug in my application

**Comment by eunjae-lee** [comment]
Thanks @sabir-jamia for reporting the issue. I've created a PR to fix this in InstantSearch.js repo. Once it's merged & released, you can update the dependency in your project. cc @nagarro-parth
