### ISSUE TITLE
refinePrevious button doesnt work properly

### ISSUE THREAD

**Issue by slaetthult** [algolia/vue-instantsearch#947]
I'm using the ais-infinite-hits widget and I have integrated the refinePrevious button and the refineNext button. If im starting on page 2 and click at the refinePrevious button everything works so far. But if i want to click on the refineNext button afterwards, nothing happens. I have to click the refineNext button twice to get the next results.

**Comment by Haroenv** [comment]
Thanks for opening an issue, but this is already tracked in https://github.com/algolia/instantsearch.js/issues/4729 and some other places :)
