### ISSUE TITLE
I want accessing data inside dynamically

### ISSUE THREAD

**Issue by finnpham** [algolia/vue-instantsearch#978]
**Question :question: **

#### Now i'm migration library from v1.7.0 => 3.7.0. And i read docs upgrade but still have some mistake.

In old version i using: 
>import { createFromAlgoliaCredentials } from 'vue-instantsearch'; 
  searchStore : createFromAlgoliaCredentials(config.ALGOLIA.APPLICATION_ID, config.ALGOLIA.API_KEY),
  And in there, i can watch state from searchStore value => it contain totalPages, results,.....

But it was 3 years, many changed, so i want ask. How can i watch data inside run? like pagination, results,.....
I try and using injector components into it.  But it too difficult to manage. 

#### My follow now. In 1 components using algolia-search i defined

-  Component injector (`HitsInjector`, `PaginationInjector`, `StatsInjector`,....)
- Component `.vue` using it. 
- And 1 mixin component to reuse logic methods.

But from here, i see i use too much code, it bad for me :( 
Images Ex: 

![image](https://user-images.githubusercontent.com/76545073/118251769-2f9ecc00-b4d2-11eb-983a-5eb210899898.png)
![image](https://user-images.githubusercontent.com/76545073/118251828-434a3280-b4d2-11eb-8d69-175c613a31cf.png)

### Second Question:
![image](https://user-images.githubusercontent.com/76545073/118251990-75f42b00-b4d2-11eb-91b4-184b2cd03f7c.png)

How can i add dynamically numberic-refinement in new version?

### What is the version you are using?

Version: `3.7.0`

**Comment by Haroenv** [comment]
Sorry, I don't understand what you are trying to do. Do you have a sandbox with the older code?

If you want to reach the helper (equivalent of search store), you can create a custom connector and use that with widget mixin, or even with `{ connector: true }` to read the properties directly in render without connector
