### ISSUE TITLE
Double query with either ais-hits or ais-pagination

### ISSUE THREAD

**Issue by joepagan** [algolia/vue-instantsearch#979]
**Bug 🐞**

Appreciate this has [_somewhat_ been discussed previously](https://github.com/algolia/vue-instantsearch/issues/935), however, that was where `ais-hits` was nested inside `ais-state-results`, here this is not using `ais-state-results` though maybe the issue is the same? This also occurs just with `ais-pagination`.

### What is the current behavior?

Multiple algolia queries are made on page load where I include ais-hits or/and ais-pagination widgets
For some context I am using `ais-configure` with a query param as this is for a search results page. This is not using the search box widget.

### Make a sandbox with the current behavior

I can't reproducible sandbox with duplicate requests as setup is different, php loading vue via templates.
I have made a reproducible repo here with just an index.html and js file in parcel: https://github.com/joepagan/vue-algolia-test

### What is the expected behavior?

1 request not 2 on page load

### Does this happen only in specific situations?

page load

### What is the proposed solution?

1 request

### What is the version you are using?

```
"algoliasearch": "4.9.1",
    "vue": "2.6.12",
    "vue-instantsearch": "3.7.0"
```

**Comment by francoischalifour** [comment]
The [joepagan/vue-algolia-test](https://github.com/joepagan/vue-algolia-test) repo doesn't seem too representative of your issue, or is it?

When a widget is mounted, it triggers a new network request. Could it be that in your real environment, you're adding one widget after the other?

**Comment by joepagan** [comment]
Hi @francoischalifour thanks for getting back.

>The joepagan/vue-algolia-test repo doesn't seem too representative of your issue, or is it?

I have just loaded up my test repo again and on page load it is definitely making 2 requests:
![image](https://user-images.githubusercontent.com/2337910/119374044-04c22e00-bcb1-11eb-89a4-322491737c97.png)
request 1: `{"requests":[{"indexName":"index_name","params":"hitsPerPage=10&query=apple&facets=%5B%5D&tagFilters="}]}`
request 2: `{"requests":[{"indexName":"index_name","params":"hitsPerPage=10&query=apple&highlightPreTag=__ais-highlight__&highlightPostTag=__%2Fais-highlight__&page=0&facets=%5B%5D&tagFilters="}]}`

>When a widget is mounted, it triggers a new network request. Could it be that in your real environment, you're adding one widget after the other?

I am using multiple widgets here which you can see in the [index.html](https://github.com/joepagan/vue-algolia-test/blob/master/index.html): `ais-configure`, `ais-stats`, `ais-hits`, `ais-pagination`, is that just how it works? Sorry if this is a stupid question though it seems like this should only need 1 request?
I can see this same behavior on multiple environments at the moment.

**Comment by eunjae-lee** [comment]
Hello @joepagan I'm sorry but I can't get this repo to work.

<img width="1458" alt="CleanShot 2021-05-25 at 11 08 43@2x" src="https://user-images.githubusercontent.com/499898/119471523-a8f7b380-bd49-11eb-9b23-d60a24c28f2c.png">

FYI, I'm using node@v12.19.0. Can you help me run it?

**Comment by joepagan** [comment]
Of course I'll help, as I hope you can help me lol! Forgive me if you already have done this, but did you update the [app](https://github.com/joepagan/vue-algolia-test/blob/master/index.html#L11) & [key](https://github.com/joepagan/vue-algolia-test/blob/master/index.html#L12) data attributes to real app & key values? and the same with the [index-name](https://github.com/joepagan/vue-algolia-test/blob/master/index.html#L16) attribute to a working index?

**Comment by Haroenv** [comment]
Hi! This issue has been opened without reply for a while. I'll close it now, but feel free to reply to our initial questions, and we'll gladly reopen if the original issue isn't solved yet.

Have a nice day!
