### ISSUE TITLE
disable searchAsYouType 

### ISSUE THREAD

**Issue by rafaelmonroy** [algolia/vue-instantsearch#985]
**Feature ⚡️**

### What is your use case for such a feature?
The React and Angular algolia packages both come with the option to disable `searchAsYouType` but we don't get that in the vue version. 

### What is your proposal
add the `searchAsYouType` boolean to `vue-instantsearch` similar to how the packages below have it. 

React: https://github.com/algolia/react-instantsearch/blob/7520e893bbec8816f6e283438610ad845616b0b4/packages/react-instantsearch-dom/src/components/SearchBox.js#L77

Angular: https://github.com/algolia/angular-instantsearch/blob/65830ea77646bec4832d91e0890684daca3bed3f/src/search-box/search-box.ts#L81

### What is the version you are using?
"vue-instantsearch": "^3.7.0"

**Comment by shortcuts** [comment]
Hi,

Thanks for the feedback. This is indeed something we could add to the library, I'll talk to the team about it but any PR are welcome :D.

In the meantime, you can create a custom search box and call the `refine` function only when submitting the form. [doc](https://www.algolia.com/doc/guides/building-search-ui/widgets/create-your-own-widgets/vue/)

cc @Haroenv

**Comment by rafaelmonroy** [comment]
@shortcuts @Haroenv thanks for looking into it! the custom input with `refine` on submit works well
